/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";
import { PredexonError } from "./predexon-error.js";

export type DataErrorResponseData = {
  detail: models.Detail;
};

export class DataErrorResponse extends PredexonError {
  detail: models.Detail;
  // hoisted from detail.error for cross-plane parity
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DataErrorResponseData;

  constructor(
    err: DataErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    // read message from detail.message (data plane shape)
    const message = err.detail?.message
      ?? err.detail?.error
      ?? `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.detail = err.detail;
    this.error = err.detail.error;

    this.name = "DataErrorResponse";
  }
}

/** @internal */
export const DataErrorResponse$inboundSchema: z.ZodMiniType<
  DataErrorResponse,
  unknown
> = z.pipe(
  z.object({
    detail: z.lazy(() => models.Detail$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new DataErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
