/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { PredexonCore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as data from "../models/data/index.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { PredexonError } from "../models/errors/predexon-error.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { PolymarketGetMarketLeaderboardServerList } from "../models/operations/polymarket-get-market-leaderboard.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Get Market Leaderboard
 *
 * @remarks
 * Get leaderboard for a specific market.
 *
 * Shows wallet rankings for trading performance within a single market.
 *
 * If set, this operation will use {@link Security.dataApiKey} from the global security.
 */
export function polymarketGetMarketLeaderboard(
  client: PredexonCore,
  request: operations.PolymarketGetMarketLeaderboardRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    data.MarketLeaderboardResponse,
    | errors.DataErrorResponse
    | data.HTTPValidationError
    | PredexonError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: PredexonCore,
  request: operations.PolymarketGetMarketLeaderboardRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      data.MarketLeaderboardResponse,
      | errors.DataErrorResponse
      | data.HTTPValidationError
      | PredexonError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      z.parse(
        operations.PolymarketGetMarketLeaderboardRequest$outboundSchema,
        value,
      ),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const baseURL = options?.serverURL
    || pathToFunc(PolymarketGetMarketLeaderboardServerList[0], {
      charEncoding: "percent",
    })();

  const pathParams = {
    condition_id: encodeSimple("condition_id", payload.condition_id, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path = pathToFunc("/v2/polymarket/leaderboard/market/{condition_id}")(
    pathParams,
  );

  const query = encodeFormQuery({
    "limit": payload.limit,
    "max_avg_buy_price": payload.max_avg_buy_price,
    "max_avg_sell_price": payload.max_avg_sell_price,
    "max_entry_edge": payload.max_entry_edge,
    "max_total_pnl": payload.max_total_pnl,
    "max_trades": payload.max_trades,
    "max_volume": payload.max_volume,
    "min_avg_buy_price": payload.min_avg_buy_price,
    "min_avg_sell_price": payload.min_avg_sell_price,
    "min_entry_edge": payload.min_entry_edge,
    "min_total_pnl": payload.min_total_pnl,
    "min_trades": payload.min_trades,
    "min_volume": payload.min_volume,
    "order": payload.order,
    "pagination_key": payload.pagination_key,
    "sort_by": payload.sort_by,
    "window": payload.window,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput, [0]);

  const context = {
    options: client._options,
    baseURL: baseURL ?? "",
    operationID: "polymarketGetMarketLeaderboard",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: baseURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    data.MarketLeaderboardResponse,
    | errors.DataErrorResponse
    | data.HTTPValidationError
    | PredexonError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, data.MarketLeaderboardResponse$inboundSchema),
    M.jsonErr([400, 404], errors.DataErrorResponse$inboundSchema),
    M.jsonErr(422, data.HTTPValidationError$inboundSchema),
    M.jsonErr(503, errors.DataErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
