/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { PredexonCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as data from "../models/data/index.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as errors from "../models/errors/index.js";
import { PredexonError } from "../models/errors/predexon-error.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { PolymarketGetLeaderboardServerList } from "../models/operations/polymarket-get-leaderboard.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Get Leaderboard
 *
 * @remarks
 * Get global leaderboard of smart wallets.
 *
 * Supports filtering by trading styles and numeric thresholds.
 *
 * If set, this operation will use {@link Security.dataApiKey} from the global security.
 */
export function polymarketGetLeaderboard(
  client: PredexonCore,
  request?: operations.PolymarketGetLeaderboardRequest | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    data.LeaderboardResponse,
    | errors.DataErrorResponse
    | data.HTTPValidationError
    | PredexonError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: PredexonCore,
  request?: operations.PolymarketGetLeaderboardRequest | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      data.LeaderboardResponse,
      | errors.DataErrorResponse
      | data.HTTPValidationError
      | PredexonError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      z.parse(
        z.optional(operations.PolymarketGetLeaderboardRequest$outboundSchema),
        value,
      ),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const baseURL = options?.serverURL
    || pathToFunc(PolymarketGetLeaderboardServerList[0], {
      charEncoding: "percent",
    })();

  const path = pathToFunc("/v2/polymarket/leaderboard")();

  const query = encodeFormQuery({
    "exclude_style": payload?.exclude_style,
    "limit": payload?.limit,
    "max_avg_buy_price": payload?.max_avg_buy_price,
    "max_avg_sell_price": payload?.max_avg_sell_price,
    "max_avg_trade_usd": payload?.max_avg_trade_usd,
    "max_entry_edge": payload?.max_entry_edge,
    "max_profit_factor": payload?.max_profit_factor,
    "max_realized_pnl": payload?.max_realized_pnl,
    "max_roi": payload?.max_roi,
    "max_total_pnl": payload?.max_total_pnl,
    "max_trades": payload?.max_trades,
    "max_volume": payload?.max_volume,
    "max_wallet_age_days": payload?.max_wallet_age_days,
    "max_win_rate": payload?.max_win_rate,
    "min_avg_buy_price": payload?.min_avg_buy_price,
    "min_avg_sell_price": payload?.min_avg_sell_price,
    "min_avg_trade_usd": payload?.min_avg_trade_usd,
    "min_entry_edge": payload?.min_entry_edge,
    "min_profit_factor": payload?.min_profit_factor,
    "min_realized_pnl": payload?.min_realized_pnl,
    "min_roi": payload?.min_roi,
    "min_total_pnl": payload?.min_total_pnl,
    "min_trades": payload?.min_trades,
    "min_volume": payload?.min_volume,
    "min_wallet_age_days": payload?.min_wallet_age_days,
    "min_win_rate": payload?.min_win_rate,
    "order": payload?.order,
    "pagination_key": payload?.pagination_key,
    "sort_by": payload?.sort_by,
    "style": payload?.style,
    "window": payload?.window,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput, [0]);

  const context = {
    options: client._options,
    baseURL: baseURL ?? "",
    operationID: "polymarketGetLeaderboard",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: baseURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    data.LeaderboardResponse,
    | errors.DataErrorResponse
    | data.HTTPValidationError
    | PredexonError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, data.LeaderboardResponse$inboundSchema),
    M.jsonErr(400, errors.DataErrorResponse$inboundSchema),
    M.jsonErr(422, data.HTTPValidationError$inboundSchema),
    M.jsonErr(503, errors.DataErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
