/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";
import {
  MarketBag,
  MarketBag$Outbound,
  MarketBag$outboundSchema,
} from "./market-bag.js";

export const AccountRedeemRequestVenue = {
  Polymarket: "polymarket",
  Predict: "predict",
  Opinion: "opinion",
  Limitless: "limitless",
  Hyperliquid: "hyperliquid",
} as const;
export type AccountRedeemRequestVenue = ClosedEnum<
  typeof AccountRedeemRequestVenue
>;

/**
 * Identify the position with either a canonical `predexonId` (recommended) or a venue-specific `market` bag. When both are supplied, `predexonId` wins. Provide one or the other.
 */
export type AccountRedeemRequest = {
  venue: AccountRedeemRequestVenue;
  /**
   * Canonical per-outcome identifier (`px-` + 12 base32 chars).
   */
  predexonId?: string | undefined;
  /**
   * Venue-specific market identification. Populate the fields the target venue requires: Polymarket needs `tokenId`; Predict, Opinion, and Limitless need `tokenId` and one other field (`marketId` for Predict and Opinion; `marketSlug` for Limitless); Hyperliquid needs `assetId`. On responses, the bag contains only the fields the venue surfaces (`tokenId`, `marketId`, `ticker`, `outcome`, `assetId`) — request-only fields like `marketSlug` are not echoed back, and Opinion order-list responses contain `marketId` only (placement responses include both).
   */
  market?: MarketBag | undefined;
};

/** @internal */
export const AccountRedeemRequestVenue$outboundSchema: z.ZodMiniEnum<
  typeof AccountRedeemRequestVenue
> = z.enum(AccountRedeemRequestVenue);

/** @internal */
export type AccountRedeemRequest$Outbound = {
  venue: string;
  predexonId?: string | undefined;
  market?: MarketBag$Outbound | undefined;
};

/** @internal */
export const AccountRedeemRequest$outboundSchema: z.ZodMiniType<
  AccountRedeemRequest$Outbound,
  AccountRedeemRequest
> = z.object({
  venue: AccountRedeemRequestVenue$outboundSchema,
  predexonId: z.optional(z.string()),
  market: z.optional(MarketBag$outboundSchema),
});

export function accountRedeemRequestToJSON(
  accountRedeemRequest: AccountRedeemRequest,
): string {
  return JSON.stringify(
    AccountRedeemRequest$outboundSchema.parse(accountRedeemRequest),
  );
}
