/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";
import {
  MarketBag,
  MarketBag$Outbound,
  MarketBag$outboundSchema,
} from "./market-bag.js";

export const AccountPlaceOrderRequestVenue = {
  Polymarket: "polymarket",
  Predict: "predict",
  Opinion: "opinion",
  Limitless: "limitless",
  Hyperliquid: "hyperliquid",
} as const;
export type AccountPlaceOrderRequestVenue = ClosedEnum<
  typeof AccountPlaceOrderRequestVenue
>;

export const AccountPlaceOrderRequestSide = {
  Buy: "buy",
  Sell: "sell",
} as const;
export type AccountPlaceOrderRequestSide = ClosedEnum<
  typeof AccountPlaceOrderRequestSide
>;

export const AccountPlaceOrderRequestType = {
  Limit: "limit",
  Market: "market",
} as const;
export type AccountPlaceOrderRequestType = ClosedEnum<
  typeof AccountPlaceOrderRequestType
>;

/**
 * Identify the market with either a canonical `predexonId` (recommended) or a venue-specific `market` bag. When both are supplied, `predexonId` wins. Provide one or the other. Hyperliquid orders must meet a $10 minimum notional (`size` * `price` >= 10), enforced by the venue; smaller orders are rejected.
 */
export type AccountPlaceOrderRequest = {
  venue: AccountPlaceOrderRequestVenue;
  /**
   * Canonical per-outcome identifier (`px-` + 12 base32 chars). When supplied, the venue-specific fields (`tokenId`, `marketId`, `marketSlug`, `assetId`) are resolved server-side.
   */
  predexonId?: string | undefined;
  /**
   * Venue-specific market identification. Populate the fields the target venue requires: Polymarket needs `tokenId`; Predict, Opinion, and Limitless need `tokenId` and one other field (`marketId` for Predict and Opinion; `marketSlug` for Limitless); Hyperliquid needs `assetId`. On responses, the bag contains only the fields the venue surfaces (`tokenId`, `marketId`, `ticker`, `outcome`, `assetId`) — request-only fields like `marketSlug` are not echoed back, and Opinion order-list responses contain `marketId` only (placement responses include both).
   */
  market?: MarketBag | undefined;
  side: AccountPlaceOrderRequestSide;
  type: AccountPlaceOrderRequestType;
  /**
   * Stablecoin to spend — pUSD (Polymarket), USDT (Predict / Opinion), USDC (Limitless). Market BUY only. Not accepted on Hyperliquid, which is size-only; use `size` for Hyperliquid market buys.
   */
  amount?: string | undefined;
  /**
   * Number of shares. Required for market SELL and all limit orders. Also required for Hyperliquid market BUY: Hyperliquid is size-only (no notional/`amount` order type), so a market buy fills at the best ask up to this share quantity.
   */
  size?: string | undefined;
  /**
   * Price per share, between 0 and 1 (exclusive). Required for limit orders.
   */
  price?: string | undefined;
};

/** @internal */
export const AccountPlaceOrderRequestVenue$outboundSchema: z.ZodMiniEnum<
  typeof AccountPlaceOrderRequestVenue
> = z.enum(AccountPlaceOrderRequestVenue);

/** @internal */
export const AccountPlaceOrderRequestSide$outboundSchema: z.ZodMiniEnum<
  typeof AccountPlaceOrderRequestSide
> = z.enum(AccountPlaceOrderRequestSide);

/** @internal */
export const AccountPlaceOrderRequestType$outboundSchema: z.ZodMiniEnum<
  typeof AccountPlaceOrderRequestType
> = z.enum(AccountPlaceOrderRequestType);

/** @internal */
export type AccountPlaceOrderRequest$Outbound = {
  venue: string;
  predexonId?: string | undefined;
  market?: MarketBag$Outbound | undefined;
  side: string;
  type: string;
  amount?: string | undefined;
  size?: string | undefined;
  price?: string | undefined;
};

/** @internal */
export const AccountPlaceOrderRequest$outboundSchema: z.ZodMiniType<
  AccountPlaceOrderRequest$Outbound,
  AccountPlaceOrderRequest
> = z.object({
  venue: AccountPlaceOrderRequestVenue$outboundSchema,
  predexonId: z.optional(z.string()),
  market: z.optional(MarketBag$outboundSchema),
  side: AccountPlaceOrderRequestSide$outboundSchema,
  type: AccountPlaceOrderRequestType$outboundSchema,
  amount: z.optional(z.string()),
  size: z.optional(z.string()),
  price: z.optional(z.string()),
});

export function accountPlaceOrderRequestToJSON(
  accountPlaceOrderRequest: AccountPlaceOrderRequest,
): string {
  return JSON.stringify(
    AccountPlaceOrderRequest$outboundSchema.parse(accountPlaceOrderRequest),
  );
}
