/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { MarketBag, MarketBag$inboundSchema } from "./market-bag.js";

/**
 * `won` if the outcome resolved in your favor (pays out 1 stablecoin per share); `lost` otherwise.
 */
export const AccountRedeemResponseResult = {
  Won: "won",
  Lost: "lost",
} as const;
/**
 * `won` if the outcome resolved in your favor (pays out 1 stablecoin per share); `lost` otherwise.
 */
export type AccountRedeemResponseResult = OpenEnum<
  typeof AccountRedeemResponseResult
>;

/**
 * Redemption is synchronous — completes inline with the API call.
 */
export const AccountRedeemResponseStatus = {
  Completed: "completed",
} as const;
/**
 * Redemption is synchronous — completes inline with the API call.
 */
export type AccountRedeemResponseStatus = ClosedEnum<
  typeof AccountRedeemResponseStatus
>;

export type AccountRedeemResponse = {
  /**
   * On-chain transaction hash of the redemption.
   */
  transactionHash?: string | undefined;
  venue?: string | undefined;
  /**
   * Canonical per-outcome identifier — same value as on the position you redeemed.
   */
  predexonId?: string | null | undefined;
  title?: string | undefined;
  outcome?: string | undefined;
  /**
   * Number of outcome shares burned.
   */
  sizeRedeemed?: string | undefined;
  /**
   * `won` if the outcome resolved in your favor (pays out 1 stablecoin per share); `lost` otherwise.
   */
  result?: AccountRedeemResponseResult | undefined;
  /**
   * Stablecoin amount credited back to the trading wallet. `0` when `result` is `lost`.
   */
  amountRedeemed?: string | undefined;
  /**
   * Redemption is synchronous — completes inline with the API call.
   */
  status?: AccountRedeemResponseStatus | undefined;
  /**
   * Venue-specific market identification. Populate the fields the target venue requires: Polymarket needs `tokenId`; Predict, Opinion, and Limitless need `tokenId` and one other field (`marketId` for Predict and Opinion; `marketSlug` for Limitless); Hyperliquid needs `assetId`. On responses, the bag contains only the fields the venue surfaces (`tokenId`, `marketId`, `ticker`, `outcome`, `assetId`) — request-only fields like `marketSlug` are not echoed back, and Opinion order-list responses contain `marketId` only (placement responses include both).
   */
  market?: MarketBag | undefined;
  message?: string | undefined;
};

/** @internal */
export const AccountRedeemResponseResult$inboundSchema: z.ZodMiniType<
  AccountRedeemResponseResult,
  unknown
> = openEnums.inboundSchema(AccountRedeemResponseResult);

/** @internal */
export const AccountRedeemResponseStatus$inboundSchema: z.ZodMiniEnum<
  typeof AccountRedeemResponseStatus
> = z.enum(AccountRedeemResponseStatus);

/** @internal */
export const AccountRedeemResponse$inboundSchema: z.ZodMiniType<
  AccountRedeemResponse,
  unknown
> = z.object({
  transactionHash: types.optional(types.string()),
  venue: types.optional(types.string()),
  predexonId: z.optional(z.nullable(types.string())),
  title: types.optional(types.string()),
  outcome: types.optional(types.string()),
  sizeRedeemed: types.optional(types.string()),
  result: types.optional(AccountRedeemResponseResult$inboundSchema),
  amountRedeemed: types.optional(types.string()),
  status: types.optional(AccountRedeemResponseStatus$inboundSchema),
  market: types.optional(MarketBag$inboundSchema),
  message: types.optional(types.string()),
});

export function accountRedeemResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountRedeemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountRedeemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountRedeemResponse' from JSON`,
  );
}
