/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const AggregationMetaStatus = {
  Ok: "ok",
  Timeout: "timeout",
  Error: "error",
} as const;
export type AggregationMetaStatus = OpenEnum<typeof AggregationMetaStatus>;

export type AggregationMetaVenue = {
  venue?: string | undefined;
  status?: AggregationMetaStatus | undefined;
};

/**
 * Per-plane status metadata on aggregated responses. Surfaces partial failures so clients can detect when a venue timed out or errored while others succeeded.
 */
export type AggregationMeta = {
  venues?: Array<AggregationMetaVenue> | undefined;
};

/** @internal */
export const AggregationMetaStatus$inboundSchema: z.ZodMiniType<
  AggregationMetaStatus,
  unknown
> = openEnums.inboundSchema(AggregationMetaStatus);

/** @internal */
export const AggregationMetaVenue$inboundSchema: z.ZodMiniType<
  AggregationMetaVenue,
  unknown
> = z.object({
  venue: types.optional(types.string()),
  status: types.optional(AggregationMetaStatus$inboundSchema),
});

export function aggregationMetaVenueFromJSON(
  jsonString: string,
): SafeParseResult<AggregationMetaVenue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AggregationMetaVenue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AggregationMetaVenue' from JSON`,
  );
}

/** @internal */
export const AggregationMeta$inboundSchema: z.ZodMiniType<
  AggregationMeta,
  unknown
> = z.object({
  venues: types.optional(
    z.array(z.lazy(() => AggregationMetaVenue$inboundSchema)),
  ),
});

export function aggregationMetaFromJSON(
  jsonString: string,
): SafeParseResult<AggregationMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AggregationMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AggregationMeta' from JSON`,
  );
}
