/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const AggregationCancelMetaStatus = {
  Ok: "ok",
  Timeout: "timeout",
  Error: "error",
} as const;
export type AggregationCancelMetaStatus = OpenEnum<
  typeof AggregationCancelMetaStatus
>;

export type AggregationCancelMetaVenue = {
  venue?: string | undefined;
  status?: AggregationCancelMetaStatus | undefined;
  /**
   * Orders cancelled on this venue (present when status is `ok`)
   */
  cancelled?: number | undefined;
};

/**
 * Per-plane status metadata on aggregated cancel-all responses. Each venue entry also reports how many of its orders were cancelled.
 */
export type AggregationCancelMeta = {
  venues?: Array<AggregationCancelMetaVenue> | undefined;
};

/** @internal */
export const AggregationCancelMetaStatus$inboundSchema: z.ZodMiniType<
  AggregationCancelMetaStatus,
  unknown
> = openEnums.inboundSchema(AggregationCancelMetaStatus);

/** @internal */
export const AggregationCancelMetaVenue$inboundSchema: z.ZodMiniType<
  AggregationCancelMetaVenue,
  unknown
> = z.object({
  venue: types.optional(types.string()),
  status: types.optional(AggregationCancelMetaStatus$inboundSchema),
  cancelled: types.optional(types.number()),
});

export function aggregationCancelMetaVenueFromJSON(
  jsonString: string,
): SafeParseResult<AggregationCancelMetaVenue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AggregationCancelMetaVenue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AggregationCancelMetaVenue' from JSON`,
  );
}

/** @internal */
export const AggregationCancelMeta$inboundSchema: z.ZodMiniType<
  AggregationCancelMeta,
  unknown
> = z.object({
  venues: types.optional(
    z.array(z.lazy(() => AggregationCancelMetaVenue$inboundSchema)),
  ),
});

export function aggregationCancelMetaFromJSON(
  jsonString: string,
): SafeParseResult<AggregationCancelMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AggregationCancelMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AggregationCancelMeta' from JSON`,
  );
}
