/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Balance = {
  /**
   * Trading venue
   */
  venue?: string | undefined;
  /**
   * Funds available for trading (not locked in orders)
   */
  available?: string | undefined;
  /**
   * Funds locked in open orders
   */
  locked?: string | undefined;
  /**
   * Total balance (available + locked)
   */
  total?: string | undefined;
};

/** @internal */
export const Balance$inboundSchema: z.ZodMiniType<Balance, unknown> = z.object({
  venue: types.optional(types.string()),
  available: types.optional(types.string()),
  locked: types.optional(types.string()),
  total: types.optional(types.string()),
});

export function balanceFromJSON(
  jsonString: string,
): SafeParseResult<Balance, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Balance$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Balance' from JSON`,
  );
}
