/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const EnableVenueRequestVenue = {
  Polymarket: "polymarket",
  Predict: "predict",
  Opinion: "opinion",
  Limitless: "limitless",
  Hyperliquid: "hyperliquid",
} as const;
export type EnableVenueRequestVenue = ClosedEnum<
  typeof EnableVenueRequestVenue
>;

export type EnableVenueRequest = {
  venue: EnableVenueRequestVenue;
};

/** @internal */
export const EnableVenueRequestVenue$outboundSchema: z.ZodMiniEnum<
  typeof EnableVenueRequestVenue
> = z.enum(EnableVenueRequestVenue);

/** @internal */
export type EnableVenueRequest$Outbound = {
  venue: string;
};

/** @internal */
export const EnableVenueRequest$outboundSchema: z.ZodMiniType<
  EnableVenueRequest$Outbound,
  EnableVenueRequest
> = z.object({
  venue: EnableVenueRequestVenue$outboundSchema,
});

export function enableVenueRequestToJSON(
  enableVenueRequest: EnableVenueRequest,
): string {
  return JSON.stringify(
    EnableVenueRequest$outboundSchema.parse(enableVenueRequest),
  );
}
