/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const RouterCancelStatus = {
  Cancelled: "cancelled",
  NotFound: "not_found",
  AlreadyFilled: "already_filled",
  Failed: "failed",
} as const;
export type RouterCancelStatus = OpenEnum<typeof RouterCancelStatus>;

export type RouterCancelResult = {
  venue?: string | undefined;
  orderId?: string | undefined;
  status?: RouterCancelStatus | undefined;
  /**
   * Present only on `failed` status.
   */
  error?: string | undefined;
};

export type RouterCancel = {
  routerOrderId?: string | undefined;
  results?: Array<RouterCancelResult> | undefined;
};

/** @internal */
export const RouterCancelStatus$inboundSchema: z.ZodMiniType<
  RouterCancelStatus,
  unknown
> = openEnums.inboundSchema(RouterCancelStatus);

/** @internal */
export const RouterCancelResult$inboundSchema: z.ZodMiniType<
  RouterCancelResult,
  unknown
> = z.object({
  venue: types.optional(types.string()),
  orderId: types.optional(types.string()),
  status: types.optional(RouterCancelStatus$inboundSchema),
  error: types.optional(types.string()),
});

export function routerCancelResultFromJSON(
  jsonString: string,
): SafeParseResult<RouterCancelResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RouterCancelResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RouterCancelResult' from JSON`,
  );
}

/** @internal */
export const RouterCancel$inboundSchema: z.ZodMiniType<RouterCancel, unknown> =
  z.object({
    routerOrderId: types.optional(types.string()),
    results: types.optional(
      z.array(z.lazy(() => RouterCancelResult$inboundSchema)),
    ),
  });

export function routerCancelFromJSON(
  jsonString: string,
): SafeParseResult<RouterCancel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RouterCancel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RouterCancel' from JSON`,
  );
}
