/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const RouterOrderSide = {
  Buy: "buy",
  Sell: "sell",
} as const;
export type RouterOrderSide = OpenEnum<typeof RouterOrderSide>;

export const RouterOrderType = {
  Market: "market",
  Limit: "limit",
} as const;
export type RouterOrderType = OpenEnum<typeof RouterOrderType>;

/**
 * Roll-up across legs. `failed` when every dispatched leg returned a terminal failure (no fills, no opens); `partial` whenever any leg filled or partial-filled while at least one leg is still open or another mix produced movement; `filled` when every leg filled; `cancelled` when all legs cancelled with no fills; `open` while at least one leg is still resting. Per-leg failure reasons are on `fills[].error`.
 */
export const RouterOrderStatus = {
  Open: "open",
  Partial: "partial",
  Filled: "filled",
  Cancelled: "cancelled",
  Failed: "failed",
} as const;
/**
 * Roll-up across legs. `failed` when every dispatched leg returned a terminal failure (no fills, no opens); `partial` whenever any leg filled or partial-filled while at least one leg is still open or another mix produced movement; `filled` when every leg filled; `cancelled` when all legs cancelled with no fills; `open` while at least one leg is still resting. Per-leg failure reasons are on `fills[].error`.
 */
export type RouterOrderStatus = OpenEnum<typeof RouterOrderStatus>;

export const FillStatus = {
  Open: "open",
  Partial: "partial",
  Filled: "filled",
  Cancelled: "cancelled",
  Failed: "failed",
} as const;
export type FillStatus = OpenEnum<typeof FillStatus>;

export type Fill = {
  venue?: string | undefined;
  /**
   * Venue-native order ID. Use this for venue-side reconciliation.
   */
  orderId?: string | undefined;
  status?: FillStatus | undefined;
  /**
   * Shares filled or resting (6-decimal normalized). `0` for failed legs.
   */
  size?: string | undefined;
  /**
   * Execution price for this leg (6-decimal normalized).
   */
  price?: string | undefined;
  /**
   * Money moved on this leg in the venue's stablecoin (6-decimal normalized).
   */
  amount?: string | undefined;
  /**
   * Present only on `failed` legs.
   */
  error?: string | undefined;
};

/**
 * Aggregate stats across `fills[]`. Embeds the partial/cancelled accounting logic so partners don't have to re-derive it.
 */
export type RouterOrderSummary = {
  /**
   * Sum of filled shares across legs (6-decimal).
   */
  totalSize?: string | undefined;
  /**
   * Sum of money moved across legs (6-decimal).
   */
  totalAmount?: string | undefined;
  /**
   * Size-weighted average execution price (6-decimal). `0` when no legs filled.
   */
  avgPrice?: string | undefined;
  /**
   * Count of legs that moved the user's position (filled, partial, or cancelled-with-partial).
   */
  venuesUsed?: number | undefined;
  /**
   * Count of legs that failed or cancelled with zero fill.
   */
  venuesFailed?: number | undefined;
};

export type Bid = {
  price?: number | undefined;
  size?: number | undefined;
};

export type Ask = {
  price?: number | undefined;
  size?: number | undefined;
};

export type RouterOrderVenue = {
  venue?: string | undefined;
  bids?: Array<Bid> | undefined;
  asks?: Array<Ask> | undefined;
  /**
   * ms since epoch when this venue's book was last updated, or `null` if unknown.
   */
  bookUpdatedAt?: number | null | undefined;
  /**
   * `true` if the venue's stream was disconnected at snapshot time.
   */
  stale?: boolean | undefined;
};

/**
 * GET detail only, for limit orders. Snapshot of the order book at decision time so you can audit the routing choice. `null` for market orders and pre-rollout records.
 */
export type DecisionSnapshot = {
  /**
   * Snapshot timestamp in ms since epoch.
   */
  capturedAt?: number | undefined;
  venues?: Array<RouterOrderVenue> | undefined;
};

export type Considered = {
  venue?: string | undefined;
  /**
   * Projected size-weighted execution price for this venue. `null` on the GET path (not recoverable from a snapshot) and on dropped venues.
   */
  avgPrice?: string | null | undefined;
  /**
   * Top-of-book price on the order's relevant side at decision time.
   */
  topLevelPrice?: string | null | undefined;
  /**
   * Why this venue wasn't routed to (e.g., `min_order_size`, `worse_price`). `null` for venues the router included.
   */
  droppedReason?: string | null | undefined;
  /**
   * Effective fee in basis points at the top of book. `null` on the GET path.
   */
  feeBpsAtTop?: number | null | undefined;
};

/**
 * Opt-in routing audit. Present only when the request included `?explain=true`. Surfaces every venue the router considered, including dropped venues with their reason.
 */
export type Routing = {
  considered?: Array<Considered> | undefined;
};

/**
 * Partner-facing router-order envelope. Same shape across POST /router/orders (market + limit), GET /router/orders (list rows), and GET /router/orders/{routerOrderId}. Always returned at HTTP 201 from POST regardless of fill outcome — read `status` for the rollup (`failed` when no leg filled). GET detail adds `decisionSnapshot` on limit orders.
 */
export type RouterOrder = {
  /**
   * Stable handle for GET/cancel.
   */
  routerOrderId?: string | undefined;
  /**
   * Canonical outcome identifier.
   */
  predexonId?: string | undefined;
  /**
   * Display title for the outcome (the market question).
   */
  title?: string | null | undefined;
  /**
   * Display label for the side bet on (e.g., `Yes`, `Lakers`).
   */
  outcome?: string | null | undefined;
  side?: RouterOrderSide | undefined;
  type?: RouterOrderType | undefined;
  /**
   * Roll-up across legs. `failed` when every dispatched leg returned a terminal failure (no fills, no opens); `partial` whenever any leg filled or partial-filled while at least one leg is still open or another mix produced movement; `filled` when every leg filled; `cancelled` when all legs cancelled with no fills; `open` while at least one leg is still resting. Per-leg failure reasons are on `fills[].error`.
   */
  status?: RouterOrderStatus | undefined;
  /**
   * USD notional the partner sent. Populated on market buys; `null` otherwise.
   */
  requestedAmount?: string | null | undefined;
  /**
   * Share count the partner sent. Populated on market sells and all limit orders; `null` otherwise.
   */
  requestedSize?: string | null | undefined;
  /**
   * Limit price the partner set. `null` on market orders — for the executed price on a market order, read `summary.avgPrice` (weighted across legs) or `fills[].price` (per leg).
   */
  limitPrice?: string | null | undefined;
  /**
   * ISO 8601 timestamp of order creation.
   */
  createdAt?: string | undefined;
  /**
   * Per-venue legs. The source of truth for per-leg status — `status` here can be `open` (limit resting), `partial`, `filled`, `cancelled`, or `failed`. A `cancelled` leg with `size > 0` means partial-fill-then-cancel.
   */
  fills?: Array<Fill> | undefined;
  /**
   * Aggregate stats across `fills[]`. Embeds the partial/cancelled accounting logic so partners don't have to re-derive it.
   */
  summary?: RouterOrderSummary | undefined;
  /**
   * GET detail only, for limit orders. Snapshot of the order book at decision time so you can audit the routing choice. `null` for market orders and pre-rollout records.
   */
  decisionSnapshot?: DecisionSnapshot | null | undefined;
  /**
   * Opt-in routing audit. Present only when the request included `?explain=true`. Surfaces every venue the router considered, including dropped venues with their reason.
   */
  routing?: Routing | undefined;
};

/** @internal */
export const RouterOrderSide$inboundSchema: z.ZodMiniType<
  RouterOrderSide,
  unknown
> = openEnums.inboundSchema(RouterOrderSide);

/** @internal */
export const RouterOrderType$inboundSchema: z.ZodMiniType<
  RouterOrderType,
  unknown
> = openEnums.inboundSchema(RouterOrderType);

/** @internal */
export const RouterOrderStatus$inboundSchema: z.ZodMiniType<
  RouterOrderStatus,
  unknown
> = openEnums.inboundSchema(RouterOrderStatus);

/** @internal */
export const FillStatus$inboundSchema: z.ZodMiniType<FillStatus, unknown> =
  openEnums.inboundSchema(FillStatus);

/** @internal */
export const Fill$inboundSchema: z.ZodMiniType<Fill, unknown> = z.object({
  venue: types.optional(types.string()),
  orderId: types.optional(types.string()),
  status: types.optional(FillStatus$inboundSchema),
  size: types.optional(types.string()),
  price: types.optional(types.string()),
  amount: types.optional(types.string()),
  error: types.optional(types.string()),
});

export function fillFromJSON(
  jsonString: string,
): SafeParseResult<Fill, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fill$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fill' from JSON`,
  );
}

/** @internal */
export const RouterOrderSummary$inboundSchema: z.ZodMiniType<
  RouterOrderSummary,
  unknown
> = z.object({
  totalSize: types.optional(types.string()),
  totalAmount: types.optional(types.string()),
  avgPrice: types.optional(types.string()),
  venuesUsed: types.optional(types.number()),
  venuesFailed: types.optional(types.number()),
});

export function routerOrderSummaryFromJSON(
  jsonString: string,
): SafeParseResult<RouterOrderSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RouterOrderSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RouterOrderSummary' from JSON`,
  );
}

/** @internal */
export const Bid$inboundSchema: z.ZodMiniType<Bid, unknown> = z.object({
  price: types.optional(types.number()),
  size: types.optional(types.number()),
});

export function bidFromJSON(
  jsonString: string,
): SafeParseResult<Bid, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bid$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bid' from JSON`,
  );
}

/** @internal */
export const Ask$inboundSchema: z.ZodMiniType<Ask, unknown> = z.object({
  price: types.optional(types.number()),
  size: types.optional(types.number()),
});

export function askFromJSON(
  jsonString: string,
): SafeParseResult<Ask, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ask$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ask' from JSON`,
  );
}

/** @internal */
export const RouterOrderVenue$inboundSchema: z.ZodMiniType<
  RouterOrderVenue,
  unknown
> = z.object({
  venue: types.optional(types.string()),
  bids: types.optional(z.array(z.lazy(() => Bid$inboundSchema))),
  asks: types.optional(z.array(z.lazy(() => Ask$inboundSchema))),
  bookUpdatedAt: z.optional(z.nullable(types.number())),
  stale: types.optional(types.boolean()),
});

export function routerOrderVenueFromJSON(
  jsonString: string,
): SafeParseResult<RouterOrderVenue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RouterOrderVenue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RouterOrderVenue' from JSON`,
  );
}

/** @internal */
export const DecisionSnapshot$inboundSchema: z.ZodMiniType<
  DecisionSnapshot,
  unknown
> = z.object({
  capturedAt: types.optional(types.number()),
  venues: types.optional(z.array(z.lazy(() => RouterOrderVenue$inboundSchema))),
});

export function decisionSnapshotFromJSON(
  jsonString: string,
): SafeParseResult<DecisionSnapshot, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DecisionSnapshot$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DecisionSnapshot' from JSON`,
  );
}

/** @internal */
export const Considered$inboundSchema: z.ZodMiniType<Considered, unknown> = z
  .object({
    venue: types.optional(types.string()),
    avgPrice: z.optional(z.nullable(types.string())),
    topLevelPrice: z.optional(z.nullable(types.string())),
    droppedReason: z.optional(z.nullable(types.string())),
    feeBpsAtTop: z.optional(z.nullable(types.number())),
  });

export function consideredFromJSON(
  jsonString: string,
): SafeParseResult<Considered, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Considered$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Considered' from JSON`,
  );
}

/** @internal */
export const Routing$inboundSchema: z.ZodMiniType<Routing, unknown> = z.object({
  considered: types.optional(z.array(z.lazy(() => Considered$inboundSchema))),
});

export function routingFromJSON(
  jsonString: string,
): SafeParseResult<Routing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Routing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Routing' from JSON`,
  );
}

/** @internal */
export const RouterOrder$inboundSchema: z.ZodMiniType<RouterOrder, unknown> = z
  .pipe(
    z.object({
      routerOrderId: types.optional(types.string()),
      predexonId: types.optional(types.string()),
      title: z.optional(z.nullable(types.string())),
      outcome: z.optional(z.nullable(types.string())),
      side: types.optional(RouterOrderSide$inboundSchema),
      type: types.optional(RouterOrderType$inboundSchema),
      status: types.optional(RouterOrderStatus$inboundSchema),
      requestedAmount: z.optional(z.nullable(types.string())),
      requestedSize: z.optional(z.nullable(types.string())),
      limitPrice: z.optional(z.nullable(types.string())),
      createdAt: types.optional(types.string()),
      fills: types.optional(z.array(z.lazy(() => Fill$inboundSchema))),
      summary: types.optional(z.lazy(() => RouterOrderSummary$inboundSchema)),
      decisionSnapshot: z.optional(
        z.nullable(z.lazy(() => DecisionSnapshot$inboundSchema)),
      ),
      _routing: types.optional(z.lazy(() => Routing$inboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        "_routing": "routing",
      });
    }),
  );

export function routerOrderFromJSON(
  jsonString: string,
): SafeParseResult<RouterOrder, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RouterOrder$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RouterOrder' from JSON`,
  );
}
