/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { RouterOrder, RouterOrder$inboundSchema } from "./router-order.js";

export type RouterOrdersList = {
  orders?: Array<RouterOrder> | undefined;
};

/** @internal */
export const RouterOrdersList$inboundSchema: z.ZodMiniType<
  RouterOrdersList,
  unknown
> = z.object({
  orders: types.optional(z.array(RouterOrder$inboundSchema)),
});

export function routerOrdersListFromJSON(
  jsonString: string,
): SafeParseResult<RouterOrdersList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RouterOrdersList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RouterOrdersList' from JSON`,
  );
}
