/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Source side of the transfer.
 */
export type TransferFrom = {
  /**
   * `deposit`, a venue name, or `external`.
   */
  wallet?: string | undefined;
  chain?: number | undefined;
  token?: string | undefined;
  address?: string | undefined;
};

/**
 * Destination side of the transfer.
 */
export type TransferTo = {
  wallet?: string | undefined;
  chain?: number | undefined;
  token?: string | undefined;
  address?: string | undefined;
};

/**
 * Partner-facing 3-state status. `pending` includes routes still in active recovery; `failed` includes routes that exhausted recovery (see `substatus`).
 */
export const TransferStatus = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
} as const;
/**
 * Partner-facing 3-state status. `pending` includes routes still in active recovery; `failed` includes routes that exhausted recovery (see `substatus`).
 */
export type TransferStatus = OpenEnum<typeof TransferStatus>;

/**
 * Optional context. `recoveryInProgress` — a transient on-chain step is being retried (poll until terminal). `escalated` — automated recovery exhausted; contact support. `legacyPartial` — historical pre-recovery-worker rows only.
 */
export const Substatus = {
  RecoveryInProgress: "recoveryInProgress",
  Escalated: "escalated",
  LegacyPartial: "legacyPartial",
} as const;
/**
 * Optional context. `recoveryInProgress` — a transient on-chain step is being retried (poll until terminal). `escalated` — automated recovery exhausted; contact support. `legacyPartial` — historical pre-recovery-worker rows only.
 */
export type Substatus = OpenEnum<typeof Substatus>;

/**
 * On-chain transaction hashes for each step that fired. Most routes use only `source`/`dest` (sometimes `approve`); venue-specific routes add `wrap`/`unwrap` (Polymarket), `safeExtract`/`safeDeposit` (Opinion), or `swap` (cross-token routes).
 */
export type TxHashes = {
  source?: string | undefined;
  dest?: string | undefined;
  approve?: string | undefined;
  unwrap?: string | undefined;
  wrap?: string | undefined;
  safeExtract?: string | undefined;
  safeDeposit?: string | undefined;
  swap?: string | undefined;
};

/**
 * A single fund-movement operation. Same envelope returned by `POST /transfers`, `GET /transfers`, and `GET /transfers/{transferId}`. `status` is the partner-facing 3-state enum; `substatus` carries additional context where useful.
 */
export type Transfer = {
  /**
   * Stable identifier (`tfr-...`). Use for `GET /transfers/{transferId}`.
   */
  transferId?: string | undefined;
  accountId?: string | undefined;
  /**
   * Source side of the transfer.
   */
  from?: TransferFrom | undefined;
  /**
   * Destination side of the transfer.
   */
  to?: TransferTo | undefined;
  /**
   * Source-side amount (echo of the request).
   */
  amount?: string | undefined;
  /**
   * Destination-side amount actually delivered. Populated once the transfer settles.
   */
  amountReceived?: string | null | undefined;
  /**
   * Partner-facing 3-state status. `pending` includes routes still in active recovery; `failed` includes routes that exhausted recovery (see `substatus`).
   */
  status?: TransferStatus | undefined;
  /**
   * Optional context. `recoveryInProgress` — a transient on-chain step is being retried (poll until terminal). `escalated` — automated recovery exhausted; contact support. `legacyPartial` — historical pre-recovery-worker rows only.
   */
  substatus?: Substatus | null | undefined;
  /**
   * On-chain transaction hashes for each step that fired. Most routes use only `source`/`dest` (sometimes `approve`); venue-specific routes add `wrap`/`unwrap` (Polymarket), `safeExtract`/`safeDeposit` (Opinion), or `swap` (cross-token routes).
   */
  txHashes?: TxHashes | undefined;
  /**
   * Bridge-explorer URL for cross-chain transfers. `null` for same-chain transfers.
   */
  explorerLink?: string | null | undefined;
  clientReferenceId?: string | null | undefined;
  createdAt?: string | undefined;
  completedAt?: string | null | undefined;
  /**
   * Human-readable failure message. Present iff `status === "failed"`.
   */
  error?: string | null | undefined;
  /**
   * Machine-readable failure code. Present iff `status === "failed"`.
   */
  errorCode?: string | null | undefined;
};

/** @internal */
export const TransferFrom$inboundSchema: z.ZodMiniType<TransferFrom, unknown> =
  z.object({
    wallet: types.optional(types.string()),
    chain: types.optional(types.number()),
    token: types.optional(types.string()),
    address: types.optional(types.string()),
  });

export function transferFromFromJSON(
  jsonString: string,
): SafeParseResult<TransferFrom, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferFrom$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferFrom' from JSON`,
  );
}

/** @internal */
export const TransferTo$inboundSchema: z.ZodMiniType<TransferTo, unknown> = z
  .object({
    wallet: types.optional(types.string()),
    chain: types.optional(types.number()),
    token: types.optional(types.string()),
    address: types.optional(types.string()),
  });

export function transferToFromJSON(
  jsonString: string,
): SafeParseResult<TransferTo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferTo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferTo' from JSON`,
  );
}

/** @internal */
export const TransferStatus$inboundSchema: z.ZodMiniType<
  TransferStatus,
  unknown
> = openEnums.inboundSchema(TransferStatus);

/** @internal */
export const Substatus$inboundSchema: z.ZodMiniType<Substatus, unknown> =
  openEnums.inboundSchema(Substatus);

/** @internal */
export const TxHashes$inboundSchema: z.ZodMiniType<TxHashes, unknown> = z
  .object({
    source: types.optional(types.string()),
    dest: types.optional(types.string()),
    approve: types.optional(types.string()),
    unwrap: types.optional(types.string()),
    wrap: types.optional(types.string()),
    safeExtract: types.optional(types.string()),
    safeDeposit: types.optional(types.string()),
    swap: types.optional(types.string()),
  });

export function txHashesFromJSON(
  jsonString: string,
): SafeParseResult<TxHashes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TxHashes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TxHashes' from JSON`,
  );
}

/** @internal */
export const Transfer$inboundSchema: z.ZodMiniType<Transfer, unknown> = z
  .object({
    transferId: types.optional(types.string()),
    accountId: types.optional(types.string()),
    from: types.optional(z.lazy(() => TransferFrom$inboundSchema)),
    to: types.optional(z.lazy(() => TransferTo$inboundSchema)),
    amount: types.optional(types.string()),
    amountReceived: z.optional(z.nullable(types.string())),
    status: types.optional(TransferStatus$inboundSchema),
    substatus: z.optional(z.nullable(Substatus$inboundSchema)),
    txHashes: types.optional(z.lazy(() => TxHashes$inboundSchema)),
    explorerLink: z.optional(z.nullable(types.string())),
    clientReferenceId: z.optional(z.nullable(types.string())),
    createdAt: types.optional(types.string()),
    completedAt: z.optional(z.nullable(types.string())),
    error: z.optional(z.nullable(types.string())),
    errorCode: z.optional(z.nullable(types.string())),
  });

export function transferFromJSON(
  jsonString: string,
): SafeParseResult<Transfer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Transfer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Transfer' from JSON`,
  );
}
