/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Venue setup status
 */
export const VenueEntitlementStatus = {
  Provisioning: "provisioning",
  Active: "active",
  Inactive: "inactive",
  Failed: "failed",
} as const;
/**
 * Venue setup status
 */
export type VenueEntitlementStatus = OpenEnum<typeof VenueEntitlementStatus>;

/**
 * Predexon manages keys for every supported venue.
 */
export const CustodyMode = {
  Managed: "managed",
} as const;
/**
 * Predexon manages keys for every supported venue.
 */
export type CustodyMode = ClosedEnum<typeof CustodyMode>;

export type VenueEntitlement = {
  /**
   * Venue setup status
   */
  status?: VenueEntitlementStatus | undefined;
  /**
   * Predexon manages keys for every supported venue.
   */
  custodyMode?: CustodyMode | undefined;
  /**
   * On-chain wallet address for the venue. Absent until the venue's `status` is `active`.
   */
  address?: string | null | undefined;
  /**
   * Failure reason. Absent unless the venue's `status` is `failed`.
   */
  error?: string | null | undefined;
};

/** @internal */
export const VenueEntitlementStatus$inboundSchema: z.ZodMiniType<
  VenueEntitlementStatus,
  unknown
> = openEnums.inboundSchema(VenueEntitlementStatus);

/** @internal */
export const CustodyMode$inboundSchema: z.ZodMiniEnum<typeof CustodyMode> = z
  .enum(CustodyMode);

/** @internal */
export const VenueEntitlement$inboundSchema: z.ZodMiniType<
  VenueEntitlement,
  unknown
> = z.object({
  status: types.optional(VenueEntitlementStatus$inboundSchema),
  custodyMode: types.optional(CustodyMode$inboundSchema),
  address: z.optional(z.nullable(types.string())),
  error: z.optional(z.nullable(types.string())),
});

export function venueEntitlementFromJSON(
  jsonString: string,
): SafeParseResult<VenueEntitlement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VenueEntitlement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VenueEntitlement' from JSON`,
  );
}
