/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Source venue
 */
export const WithdrawRequestVenue = {
  Polymarket: "polymarket",
  Predict: "predict",
  Opinion: "opinion",
  Limitless: "limitless",
  Hyperliquid: "hyperliquid",
} as const;
/**
 * Source venue
 */
export type WithdrawRequestVenue = ClosedEnum<typeof WithdrawRequestVenue>;

/**
 * Destination chain — `polygon` for Polymarket, `bsc` for Predict and Opinion, `base` for Limitless, `arbitrum` for Hyperliquid
 */
export const WithdrawRequestChain = {
  Polygon: "polygon",
  Bsc: "bsc",
  Base: "base",
  Arbitrum: "arbitrum",
} as const;
/**
 * Destination chain — `polygon` for Polymarket, `bsc` for Predict and Opinion, `base` for Limitless, `arbitrum` for Hyperliquid
 */
export type WithdrawRequestChain = ClosedEnum<typeof WithdrawRequestChain>;

export type WithdrawRequest = {
  /**
   * Source venue
   */
  venue: WithdrawRequestVenue;
  /**
   * Amount to withdraw (e.g., "100.00"). Hyperliquid: $10 minimum; $1 USDC fee deducted before delivery.
   */
  amount: string;
  /**
   * Recipient wallet address (must match chain format)
   */
  destinationAddress: string;
  /**
   * Destination chain — `polygon` for Polymarket, `bsc` for Predict and Opinion, `base` for Limitless, `arbitrum` for Hyperliquid
   */
  chain: WithdrawRequestChain;
};

/** @internal */
export const WithdrawRequestVenue$outboundSchema: z.ZodMiniEnum<
  typeof WithdrawRequestVenue
> = z.enum(WithdrawRequestVenue);

/** @internal */
export const WithdrawRequestChain$outboundSchema: z.ZodMiniEnum<
  typeof WithdrawRequestChain
> = z.enum(WithdrawRequestChain);

/** @internal */
export type WithdrawRequest$Outbound = {
  venue: string;
  amount: string;
  destinationAddress: string;
  chain: string;
};

/** @internal */
export const WithdrawRequest$outboundSchema: z.ZodMiniType<
  WithdrawRequest$Outbound,
  WithdrawRequest
> = z.object({
  venue: WithdrawRequestVenue$outboundSchema,
  amount: z.string(),
  destinationAddress: z.string(),
  chain: WithdrawRequestChain$outboundSchema,
});

export function withdrawRequestToJSON(
  withdrawRequest: WithdrawRequest,
): string {
  return JSON.stringify(WithdrawRequest$outboundSchema.parse(withdrawRequest));
}
