/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type WithdrawResponse = {
  /**
   * Blockchain transaction hash for the withdrawal. Empty string for Hyperliquid withdrawals, which settle asynchronously (use `withdrawalId` to track).
   */
  transactionHash?: string | undefined;
  /**
   * Amount withdrawn, in the venue's stablecoin — USDC.e (Polymarket), USDT (Predict / Opinion), USDC (Limitless), USDC (Hyperliquid; $1 fee deducted, recipient receives `amount - 1`).
   */
  amount?: string | undefined;
  /**
   * Recipient wallet address
   */
  destinationAddress?: string | undefined;
  /**
   * Destination chain
   */
  chain?: string | undefined;
  /**
   * Withdrawal status: `completed` for synchronously-settled venues, `pending` for Hyperliquid (settlement takes ~3-4 minutes).
   */
  status?: string | undefined;
  /**
   * Tracking ID for asynchronous withdrawals (Hyperliquid). Use it to correlate the request with on-chain settlement.
   */
  withdrawalId?: string | undefined;
};

/** @internal */
export const WithdrawResponse$inboundSchema: z.ZodMiniType<
  WithdrawResponse,
  unknown
> = z.object({
  transactionHash: types.optional(types.string()),
  amount: types.optional(types.string()),
  destinationAddress: types.optional(types.string()),
  chain: types.optional(types.string()),
  status: types.optional(types.string()),
  withdrawalId: types.optional(types.string()),
});

export function withdrawResponseFromJSON(
  jsonString: string,
): SafeParseResult<WithdrawResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WithdrawResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WithdrawResponse' from JSON`,
  );
}
