/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountsCreate } from "../funcs/accounts-create.js";
import { accountsDelete } from "../funcs/accounts-delete.js";
import { accountsEnableVenue } from "../funcs/accounts-enable-venue.js";
import { accountsGetBalance } from "../funcs/accounts-get-balance.js";
import { accountsGet } from "../funcs/accounts-get.js";
import { accountsListPositions } from "../funcs/accounts-list-positions.js";
import { accountsList } from "../funcs/accounts-list.js";
import { accountsRedeem } from "../funcs/accounts-redeem.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import * as trading from "../models/trading/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Accounts extends ClientSDK {
  /**
   * Create Account
   *
   * @remarks
   * Create a new account. No venues are provisioned automatically — call `POST /api/accounts/{accountId}/enable` for each venue the account should trade on.
   */
  async create(
    options?: RequestOptions,
  ): Promise<trading.Account> {
    return unwrapAsync(accountsCreate(
      this,
      options,
    ));
  }

  /**
   * List Accounts
   *
   * @remarks
   * List all accounts owned by the calling API key.
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.ListAccountsResponse> {
    return unwrapAsync(accountsList(
      this,
      options,
    ));
  }

  /**
   * Get Account
   *
   * @remarks
   * Fetch an account's profile and per-venue entitlements.
   */
  async get(
    request: operations.GetAccountRequest,
    options?: RequestOptions,
  ): Promise<trading.Account> {
    return unwrapAsync(accountsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Account
   *
   * @remarks
   * Delete an account. Cleanup runs across every venue the account had enabled.
   */
  async delete(
    request: operations.DeleteAccountRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(accountsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Enable Venue
   *
   * @remarks
   * Provision a venue for an account. Creates the wallet, funds gas, and sets token approvals. Returns `provisioning` while setup runs; poll `GET /api/accounts/{accountId}` until the venue's status becomes `active`.
   */
  async enableVenue(
    request: operations.EnableVenueRequest,
    options?: RequestOptions,
  ): Promise<trading.EnableVenueResponse> {
    return unwrapAsync(accountsEnableVenue(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Balance
   *
   * @remarks
   * Fetch trading balances across all enabled venues, or filter by a single venue.
   */
  async getBalance(
    request: operations.GetBalanceAccountRequest,
    options?: RequestOptions,
  ): Promise<trading.BalanceResponse> {
    return unwrapAsync(accountsGetBalance(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Positions
   *
   * @remarks
   * Fetch current positions across all enabled venues, or filter by a single venue.
   */
  async listPositions(
    request: operations.GetPositionsAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPositionsAccountResponse> {
    return unwrapAsync(accountsListPositions(
      this,
      request,
      options,
    ));
  }

  /**
   * Redeem Position
   *
   * @remarks
   * Redeem a resolved position. For Polymarket, Predict, and Limitless, identify the position via `market.tokenId`. For Opinion, use `market.marketId` — Opinion redeems every outcome of a market in one call.
   */
  async redeem(
    request: operations.RedeemPositionAccountRequest,
    options?: RequestOptions,
  ): Promise<trading.AccountRedeemResponse> {
    return unwrapAsync(accountsRedeem(
      this,
      request,
      options,
    ));
  }
}
