/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { binanceGetCandlesticks } from "../funcs/binance-get-candlesticks.js";
import { binanceGetTicks } from "../funcs/binance-get-ticks.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as data from "../models/data/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Binance extends ClientSDK {
  /**
   * Get Binance Ticks
   *
   * @remarks
   * Fetch raw book ticker data at microsecond granularity.
   *
   * Returns bid/ask/mid/spread for each tick. Use cursor-based pagination
   * to iterate through large time ranges (e.g. a 15m window is ~63K ticks).
   */
  async getTicks(
    request: operations.BinanceGetTicksRequest,
    options?: RequestOptions,
  ): Promise<data.BinanceTicksResponse> {
    return unwrapAsync(binanceGetTicks(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Binance Candles
   *
   * @remarks
   * Fetch OHLCV candlestick data for a Binance trading pair.
   *
   * Candle prices are derived from book ticker mid-prices (not trade prices).
   *
   * **Backtesting crypto up/down markets:**
   * - Use `interval=15m` for 15-minute prediction markets
   * - Use `interval=1h` for 1-hour prediction markets
   * - Use `interval=4h` and `interval=1d` for longer timeframes
   */
  async getCandlesticks(
    request: operations.BinanceGetCandlesticksRequest,
    options?: RequestOptions,
  ): Promise<data.BinanceCandlesResponse> {
    return unwrapAsync(binanceGetCandlesticks(
      this,
      request,
      options,
    ));
  }
}
