/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { dflowGetTrades } from "../funcs/dflow-get-trades.js";
import { dflowGetWalletPnL } from "../funcs/dflow-get-wallet-pn-l.js";
import { dflowGetWalletPositions } from "../funcs/dflow-get-wallet-positions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as data from "../models/data/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Dflow extends ClientSDK {
  /**
   * Get Dflow Trades
   *
   * @remarks
   * Fetch trade history for a wallet on Dflow.
   *
   * Returns trades from the Dflow platform with support for:
   * - Filtering by market_ticker, outcome_mint, or trade_type
   * - Time range filtering
   * - Cursor-based pagination (efficient for deep pagination)
   * - Enriched with market metadata (title, category, side)
   */
  async getTrades(
    request: operations.DflowGetTradesRequest,
    options?: RequestOptions,
  ): Promise<data.DflowTradesResponse> {
    return unwrapAsync(dflowGetTrades(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Dflow Wallet Pnl
   *
   * @remarks
   * Fetch realized profit and loss (PnL) history for a specific wallet address on Dflow.
   *
   * Returns cumulative realized PnL over time with data points for every interval
   * in the specified granularity.
   */
  async getWalletPnL(
    request: operations.DflowGetWalletPnLRequest,
    options?: RequestOptions,
  ): Promise<data.DflowWalletPnLResponse> {
    return unwrapAsync(dflowGetWalletPnL(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Dflow Wallet Positions
   *
   * @remarks
   * Fetch current positions for a wallet address on Dflow.
   *
   * Returns all positions with total cost basis, realized PnL, and fees paid.
   *
   * - **Open positions**: Currently holding tokens (total_qty_bought > total_qty_sold)
   * - **Closed positions**: No longer holding but has trading history
   *
   * Uses cursor-based pagination for efficient deep pagination.
   */
  async getWalletPositions(
    request: operations.DflowGetWalletPositionsRequest,
    options?: RequestOptions,
  ): Promise<data.DflowWalletPositionsResponse> {
    return unwrapAsync(dflowGetWalletPositions(
      this,
      request,
      options,
    ));
  }
}
