/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersCancelAll } from "../funcs/orders-cancel-all.js";
import { ordersCancel } from "../funcs/orders-cancel.js";
import { ordersGet } from "../funcs/orders-get.js";
import { ordersList } from "../funcs/orders-list.js";
import { ordersPlace } from "../funcs/orders-place.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import * as trading from "../models/trading/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Orders extends ClientSDK {
  /**
   * Place Order
   *
   * @remarks
   * Place a buy or sell order. Identify the market with a `market` bag — required fields differ by venue (see the Place Order guide for the per-venue matrix).
   */
  async place(
    request: operations.PlaceOrderAccountRequest,
    options?: RequestOptions,
  ): Promise<trading.AccountOrderResponse> {
    return unwrapAsync(ordersPlace(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Orders
   *
   * @remarks
   * Fetch open orders across all enabled venues, or filter by a single venue.
   */
  async list(
    request: operations.GetOrdersAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.GetOrdersAccountResponse> {
    return unwrapAsync(ordersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel All Orders
   *
   * @remarks
   * Cancel all open orders, optionally scoped to a venue.
   */
  async cancelAll(
    request: operations.CancelAllOrdersAccountRequest,
    options?: RequestOptions,
  ): Promise<trading.CancelAllResponse> {
    return unwrapAsync(ordersCancelAll(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Order
   *
   * @remarks
   * Fetch a specific order by ID. `venue` must match the venue the order was placed on.
   */
  async get(
    request: operations.GetOrderAccountRequest,
    options?: RequestOptions,
  ): Promise<trading.AccountOrderResponse> {
    return unwrapAsync(ordersGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel Order
   *
   * @remarks
   * Cancel a specific open order.
   */
  async cancel(
    request: operations.CancelOrderAccountRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(ordersCancel(
      this,
      request,
      options,
    ));
  }
}
