/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { polymarketFilterWalletsByMarkets } from "../funcs/polymarket-filter-wallets-by-markets.js";
import { polymarketGetActivity } from "../funcs/polymarket-get-activity.js";
import { polymarketGetBuilderLeaderboard } from "../funcs/polymarket-get-builder-leaderboard.js";
import { polymarketGetBuilderMarkets } from "../funcs/polymarket-get-builder-markets.js";
import { polymarketGetBuilderStats } from "../funcs/polymarket-get-builder-stats.js";
import { polymarketGetBuilderTimeSeries } from "../funcs/polymarket-get-builder-time-series.js";
import { polymarketGetCandlesticksByToken } from "../funcs/polymarket-get-candlesticks-by-token.js";
import { polymarketGetCandlesticks } from "../funcs/polymarket-get-candlesticks.js";
import { polymarketGetCohortStats } from "../funcs/polymarket-get-cohort-stats.js";
import { polymarketGetConnectedWallets } from "../funcs/polymarket-get-connected-wallets.js";
import { polymarketGetLeaderboard } from "../funcs/polymarket-get-leaderboard.js";
import { polymarketGetMarketLeaderboard } from "../funcs/polymarket-get-market-leaderboard.js";
import { polymarketGetMarketTopHolders } from "../funcs/polymarket-get-market-top-holders.js";
import { polymarketGetOpenInterestTimeSeries } from "../funcs/polymarket-get-open-interest-time-series.js";
import { polymarketGetOrderbookHistory } from "../funcs/polymarket-get-orderbook-history.js";
import { polymarketGetSimilarWallets } from "../funcs/polymarket-get-similar-wallets.js";
import { polymarketGetSmartMoneyPositioning } from "../funcs/polymarket-get-smart-money-positioning.js";
import { polymarketGetTokenPrice } from "../funcs/polymarket-get-token-price.js";
import { polymarketGetTrades } from "../funcs/polymarket-get-trades.js";
import { polymarketGetUmaMarket } from "../funcs/polymarket-get-uma-market.js";
import { polymarketGetVolumeChart } from "../funcs/polymarket-get-volume-chart.js";
import { polymarketGetVolumeTimeSeries } from "../funcs/polymarket-get-volume-time-series.js";
import { polymarketGetWalletIdentities } from "../funcs/polymarket-get-wallet-identities.js";
import { polymarketGetWalletIdentity } from "../funcs/polymarket-get-wallet-identity.js";
import { polymarketGetWalletMarkets } from "../funcs/polymarket-get-wallet-markets.js";
import { polymarketGetWalletPnL } from "../funcs/polymarket-get-wallet-pn-l.js";
import { polymarketGetWalletPositions } from "../funcs/polymarket-get-wallet-positions.js";
import { polymarketGetWalletProfile } from "../funcs/polymarket-get-wallet-profile.js";
import { polymarketGetWalletProfiles } from "../funcs/polymarket-get-wallet-profiles.js";
import { polymarketGetWalletVolumeChart } from "../funcs/polymarket-get-wallet-volume-chart.js";
import { polymarketListAllPositions } from "../funcs/polymarket-list-all-positions.js";
import { polymarketListCryptoMarkets } from "../funcs/polymarket-list-crypto-markets.js";
import { polymarketListEventsKeyset } from "../funcs/polymarket-list-events-keyset.js";
import { polymarketListEvents } from "../funcs/polymarket-list-events.js";
import { polymarketListMarketsKeyset } from "../funcs/polymarket-list-markets-keyset.js";
import { polymarketListMarkets } from "../funcs/polymarket-list-markets.js";
import { polymarketListSmartActivityMarkets } from "../funcs/polymarket-list-smart-activity-markets.js";
import { polymarketListUmaMarkets } from "../funcs/polymarket-list-uma-markets.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as data from "../models/data/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Polymarket extends ClientSDK {
  /**
   * Get Wallet Pnl
   *
   * @remarks
   * Fetch realized profit and loss (PnL) for a specific wallet address.
   *
   * Returns realized gains only - from confirmed sells or redeems.
   *
   * When condition_id is provided, returns realized PnL for that specific market only.
   * This handles split/merge operations correctly by aggregating both sides.
   */
  async getWalletPnL(
    request: operations.PolymarketGetWalletPnLRequest,
    options?: RequestOptions,
  ): Promise<data.WalletPnLResponse> {
    return unwrapAsync(polymarketGetWalletPnL(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Wallet Positions
   *
   * @remarks
   * Fetch current positions for a wallet address.
   *
   * Returns all open positions with cost basis, current market prices, and P&L calculations.
   * Supports filtering by market_slug or condition_id.
   */
  async getWalletPositions(
    request: operations.PolymarketGetWalletPositionsRequest,
    options?: RequestOptions,
  ): Promise<data.WalletPositionsResponse> {
    return unwrapAsync(polymarketGetWalletPositions(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Wallet Volume Chart
   *
   * @remarks
   * Fetch volume chart data for a wallet, broken down by BUY/SELL side.
   *
   * Returns per-period total, BUY, and SELL volume aggregated from trade events
   * where the wallet was the maker (providing liquidity).
   */
  async getWalletVolumeChart(
    request: operations.PolymarketGetWalletVolumeChartRequest,
    options?: RequestOptions,
  ): Promise<data.WalletVolumeChartResponse> {
    return unwrapAsync(polymarketGetWalletVolumeChart(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Wallet Identity
   *
   * @remarks
   * Fetch identity + profile metadata for a wallet:
   * display name, pseudonym, profile image (pfp), X handle, verified/creator/mod
   * badges, type (proxy/safe/eoa), signer, USDC balance, and timestamps.
   *
   * Lookup matches against either the proxy address (`wallet.id`) or the
   * underlying signer EOA (`wallet.signer`).
   */
  async getWalletIdentity(
    request: operations.PolymarketGetWalletIdentityRequest,
    options?: RequestOptions,
  ): Promise<data.WalletIdentityResponse> {
    return unwrapAsync(polymarketGetWalletIdentity(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Wallet Identities
   *
   * @remarks
   * Bulk identity lookup. Accepts up to 200 addresses (proxy or signer EOA);
   * returns a map of lowercase address → profile. Both `id` and `signer` of each
   * matched row are keys in the result so callers can look up by whichever they
   * queried with. Missing addresses are simply absent from the map.
   */
  async getWalletIdentities(
    request: data.WalletIdentitiesRequest,
    options?: RequestOptions,
  ): Promise<data.WalletIdentitiesResponse> {
    return unwrapAsync(polymarketGetWalletIdentities(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Candlesticks
   *
   * @remarks
   * Fetch historical candlestick data for a market.
   *
   * Returns combined OHLCV data from both YES and NO tokens, normalized to YES perspective.
   * NO token prices are converted as (1 - price) and volumes are combined.
   */
  async getCandlesticks(
    request: operations.PolymarketGetCandlesticksRequest,
    options?: RequestOptions,
  ): Promise<data.CandlesticksResponse> {
    return unwrapAsync(polymarketGetCandlesticks(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Market Price
   *
   * @remarks
   * Fetch the current or historical market price for a token.
   *
   * Uses last 5 trades across both tokens (Yes/No) of the market:
   * - If all prices within $0.10: weighted average by USD amount
   * - Otherwise: last traded price
   */
  async getTokenPrice(
    request: operations.PolymarketGetTokenPriceRequest,
    options?: RequestOptions,
  ): Promise<data.MarketPriceResponse> {
    return unwrapAsync(polymarketGetTokenPrice(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Activity
   *
   * @remarks
   * Fetch activity data for a specific user.
   *
   * Returns SPLIT, MERGE, REDEEM, and CONVERT events from the unified activity table.
   *
   * Note on CONVERT rows: these are NegRisk position conversions (sell NO tokens on a
   * subset of conditions, buy YES tokens on the remainder). Their `condition_id` field
   * actually carries the NegRisk parent market_id, not a CTF condition_id, so the
   * Postgres market-metadata lookup will return empty market_slug/title for them.
   * Filtering by condition_id will not match conversions — conversions are a
   * market-level operation, not a per-outcome one.
   */
  async getActivity(
    request: operations.PolymarketGetActivityRequest,
    options?: RequestOptions,
  ): Promise<data.ActivityResponse> {
    return unwrapAsync(polymarketGetActivity(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Markets
   *
   * @remarks
   * List markets with filtering and sorting.
   *
   * Consolidates active and closed markets into a single endpoint.
   * Use status=open for active markets only.
   *
   * Rolling metrics (volume_1d/7d/30d, trades, OI) are refreshed hourly.
   */
  async listMarkets(
    request?: operations.PolymarketListMarketsRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.PolymarketMarketsResponse> {
    return unwrapAsync(polymarketListMarkets(
      this,
      request,
      options,
    ));
  }

  /**
   * List Markets (Keyset Pagination)
   *
   * @remarks
   * List markets with the same filters and sort options as /v2/polymarket/markets, but use cursor-based keyset pagination via pagination_key instead of offset.
   *
   * Use this endpoint for large backfills and deep pagination. It avoids the performance cost of skipping large offsets and does not return a total count.
   */
  async listMarketsKeyset(
    request?: operations.PolymarketListMarketsKeysetRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.PolymarketMarketsKeysetResponse> {
    return unwrapAsync(polymarketListMarketsKeyset(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Market Volume Time Series
   *
   * @remarks
   * Return historical time series of traded volume for a token (day+ granularity).
   */
  async getVolumeTimeSeries(
    request: operations.PolymarketGetVolumeTimeSeriesRequest,
    options?: RequestOptions,
  ): Promise<data.MarketVolumeTimeSeriesResponse> {
    return unwrapAsync(polymarketGetVolumeTimeSeries(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Market Open Interest Time Series
   *
   * @remarks
   * Provide historical open interest (total value of tokens circulating from split, merge, redeem, and conversion events) with min granularity day.
   */
  async getOpenInterestTimeSeries(
    request: operations.PolymarketGetOpenInterestTimeSeriesRequest,
    options?: RequestOptions,
  ): Promise<data.MarketOpenInterestTimeSeriesResponse> {
    return unwrapAsync(polymarketGetOpenInterestTimeSeries(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Orderbooks
   *
   * @remarks
   * Fetch historical orderbook snapshots for a specific asset (token ID) over a specified time range.
   *
   * Returns snapshots of the order book including bids, asks, and market metadata in order.
   * All timestamps are in milliseconds. Orderbook data has history starting from January 1st, 2026.
   */
  async getOrderbookHistory(
    request: operations.PolymarketGetOrderbookHistoryRequest,
    options?: RequestOptions,
  ): Promise<data.OrderbooksResponse> {
    return unwrapAsync(polymarketGetOrderbookHistory(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Trades
   *
   * @remarks
   * Fetch historical trade data.
   *
   * Returns trades from Polymarket with support for:
   * - Filtering by market_slug, condition_id, token_id, or wallet
   * - Time range filtering (start_time, end_time)
   * - Minimum trade amount filtering (min_total)
   * - Cursor-based pagination
   * - Global "all trades" mode (no filters) - returns trades across all markets
   *
   * **All Trades Mode:**
   * When no market/wallet filter is provided, returns global trades newest-first.
   * - Only DESC order is supported (returns 400 if order=asc)
   * - First page defaults to last 24 hours for fast queries
   * - Pagination automatically extends the time range as you page back
   * - Provide start_time or end_time to query specific time ranges
   */
  async getTrades(
    request?: operations.PolymarketGetTradesRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.TradesResponse> {
    return unwrapAsync(polymarketGetTrades(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Volume Chart
   *
   * @remarks
   * Fetch volume chart data for a market, broken down by YES/NO side.
   *
   * Returns per-period total, YES, and NO volume aggregated from trade events.
   */
  async getVolumeChart(
    request: operations.PolymarketGetVolumeChartRequest,
    options?: RequestOptions,
  ): Promise<data.VolumeChartResponse> {
    return unwrapAsync(polymarketGetVolumeChart(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Wallet Profile
   *
   * @remarks
   * Get complete smart wallet profile.
   *
   * Returns all metrics across all time windows and style classifications.
   */
  async getWalletProfile(
    request: operations.PolymarketGetWalletProfileRequest,
    options?: RequestOptions,
  ): Promise<data.WalletProfileResponse> {
    return unwrapAsync(polymarketGetWalletProfile(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Wallet Profiles Batch
   *
   * @remarks
   * Get wallet profiles for multiple addresses in a single request.
   *
   * Returns the same data as the single wallet profile endpoint, but for multiple wallets.
   * Wallets not found are omitted from the response.
   */
  async getWalletProfiles(
    request: operations.PolymarketGetWalletProfilesRequest,
    options?: RequestOptions,
  ): Promise<Array<data.WalletProfileResponse>> {
    return unwrapAsync(polymarketGetWalletProfiles(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Leaderboard
   *
   * @remarks
   * Get global leaderboard of smart wallets.
   *
   * Supports filtering by trading styles and numeric thresholds.
   */
  async getLeaderboard(
    request?: operations.PolymarketGetLeaderboardRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.LeaderboardResponse> {
    return unwrapAsync(polymarketGetLeaderboard(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Market Leaderboard
   *
   * @remarks
   * Get leaderboard for a specific market.
   *
   * Shows wallet rankings for trading performance within a single market.
   */
  async getMarketLeaderboard(
    request: operations.PolymarketGetMarketLeaderboardRequest,
    options?: RequestOptions,
  ): Promise<data.MarketLeaderboardResponse> {
    return unwrapAsync(polymarketGetMarketLeaderboard(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Market Top Holders
   *
   * @remarks
   * Get top holders for a specific market, ranked by position size.
   *
   * Use the 'side' parameter to filter by Yes or No holders:
   * - side=yes: Top holders betting on Yes outcome
   * - side=no: Top holders betting on No outcome
   *
   * Returns wallets with the largest positions in this market, including
   * their position value, entry price, and realized/unrealized PnL.
   */
  async getMarketTopHolders(
    request: operations.PolymarketGetMarketTopHoldersRequest,
    options?: RequestOptions,
  ): Promise<data.TopHoldersResponse> {
    return unwrapAsync(polymarketGetMarketTopHolders(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Wallet Markets
   *
   * @remarks
   * Get per-market breakdown for a wallet.
   *
   * Shows performance metrics for each market the wallet has traded in.
   */
  async getWalletMarkets(
    request: operations.PolymarketGetWalletMarketsRequest,
    options?: RequestOptions,
  ): Promise<data.WalletMarketsResponse> {
    return unwrapAsync(polymarketGetWalletMarkets(
      this,
      request,
      options,
    ));
  }

  /**
   * Filter Wallets By Markets
   *
   * @remarks
   * Filter wallets by market trades with AND/OR logic, with metric filters on combined performance.
   *
   * **Use Cases:**
   * - Find all wallets that traded Market A AND Market B AND Market C (intersection)
   * - Find all wallets that traded Market A OR Market B OR Market C (union)
   * - Filter by combined performance: wallets with combined win_rate > 50% across these markets
   *
   * **Query Logic:**
   * - AND: Returns wallets that have traded ALL specified markets
   * - OR: Returns wallets that have traded ANY of the specified markets
   *
   * **Metrics:**
   * All metrics (realized_pnl, volume, win_rate, roi, profit_factor) are aggregated across the
   * specified markets only. Derived metrics (win_rate, ROI, profit_factor) are properly
   * calculated from underlying sums, not averaged.
   *
   * Uses ClickHouse for fast aggregation across markets.
   */
  async filterWalletsByMarkets(
    request: operations.PolymarketFilterWalletsByMarketsRequest,
    options?: RequestOptions,
  ): Promise<data.WalletFilterResponse> {
    return unwrapAsync(polymarketFilterWalletsByMarkets(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Smart Activity Markets
   *
   * @remarks
   * Discover markets where high-performing wallets are active.
   *
   * **Use Case:** Find alpha by seeing where profitable traders are putting their money.
   *
   * **How it works:**
   * 1. Define "smart wallets" using the filter criteria (min_realized_pnl, min_total_pnl, min_roi, etc.)
   * 2. Find all markets these wallets have traded
   * 3. Rank markets by smart wallet activity (volume, count, realized PnL)
   *
   * **Filter Requirements:**
   *
   * At least one "strong" filter must meet configured minimum thresholds.
   * Defaults in this service:
   * - `min_realized_pnl >= 5000` ($5,000+ PnL)
   * - `min_total_pnl >= 5000` ($5,000+ net total PnL)
   * - `min_roi >= 0.15` (15%+ ROI)
   * - `min_trades >= 100` (100+ trades)
   * - `min_volume >= 10000` ($10,000+ volume)
   *
   * If using `min_win_rate` or `min_profit_factor` without a strong filter,
   * you must also specify `min_trades >= 50`.
   *
   * These requirements ensure meaningful wallet filtering and fast query performance.
   *
   * Returns markets sorted by smart wallet activity metrics.
   */
  async listSmartActivityMarkets(
    request?: operations.PolymarketListSmartActivityMarketsRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.SmartActivityResponse> {
    return unwrapAsync(polymarketListSmartActivityMarkets(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Smart Money Positioning
   *
   * @remarks
   * Get smart money positioning for a specific market.
   *
   * **Use Case:** See what profitable traders are doing on a specific market.
   *
   * **Filter Requirements:**
   *
   * At least one "strong" filter must meet these minimum thresholds:
   * - `min_realized_pnl >= 1000` ($1,000+ PnL)
   * - `min_total_pnl >= 1000` ($1,000+ net total PnL)
   * - `min_roi >= 0.15` (15%+ ROI)
   * - `min_trades >= 100` (100+ trades)
   * - `min_volume >= 10000` ($10,000+ volume)
   *
   * If using `min_win_rate` or `min_profit_factor` without a strong filter,
   * you must also specify `min_trades >= 50`.
   *
   * **Returns:**
   * - How many smart wallets are net buyers vs net sellers
   * - Average entry prices for smart wallets
   * - Total volume and realized PnL from smart wallets
   */
  async getSmartMoneyPositioning(
    request: operations.PolymarketGetSmartMoneyPositioningRequest,
    options?: RequestOptions,
  ): Promise<data.SmartMoneyResponse> {
    return unwrapAsync(polymarketGetSmartMoneyPositioning(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Similar Wallets
   *
   * @remarks
   * Find wallets with similar market portfolios (copy-trade detection).
   *
   * **Use Case:**
   * - Find wallets that trade similar markets to a target wallet
   * - Detect potential copy-trading patterns
   * - Discover traders with similar strategies
   *
   * **How it works:**
   * 1. Get all markets the target wallet has traded
   * 2. Find other wallets that traded the same markets
   * 3. Rank by overlap percentage and count
   */
  async getSimilarWallets(
    request: operations.PolymarketGetSimilarWalletsRequest,
    options?: RequestOptions,
  ): Promise<data.WalletSimilarityResponse> {
    return unwrapAsync(polymarketGetSimilarWallets(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Cohort Stats
   *
   * @remarks
   * Compare performance across trading style cohorts.
   *
   * **Use Case:** Understand which trading styles perform best.
   *
   * **Cohorts:** Based on primary_trading_style classification:
   * - WHALE: Large position traders
   * - MARKET_MAKER: Balanced buy/sell with frequent trading
   * - ACTIVE_TRADER: High trade frequency
   * - BUY_AND_HOLD: Long holding periods
   * - DEGEN: High-risk patterns
   * - HIGH_CONVICTION: Buys at high prices
   * - CONTRARIAN: Takes unpopular sides
   * - VALUE_HUNTER: Enters at uncertain odds
   *
   * Returns aggregate statistics for each cohort.
   */
  async getCohortStats(
    request?: operations.PolymarketGetCohortStatsRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.CohortComparisonResponse> {
    return unwrapAsync(polymarketGetCohortStats(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Crypto Updown
   *
   * @remarks
   * List crypto up/down prediction markets.
   *
   * Returns Bitcoin, Ethereum, Solana, XRP, HYPE, Dogecoin, and BNB up/down
   * markets across all timeframes (5m, 15m, 1h, 4h, daily). Supports filtering
   * by asset, timeframe, status, and time range.
   *
   * **Common queries:**
   * - Current open markets: `?status=open`
   * - BTC 15m timeline: `?asset=btc&timeframe=15m&sort=asc`
   * - Recent BTC 15m results: `?asset=btc&timeframe=15m&status=closed&limit=20`
   * - Time window: `?end_after=<unix_ts>&end_before=<unix_ts>&sort=asc`
   */
  async listCryptoMarkets(
    request?: operations.PolymarketListCryptoMarketsRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.CryptoUpDownResponse> {
    return unwrapAsync(polymarketListCryptoMarkets(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Events
   *
   * @remarks
   * List events with filtering and sorting.
   *
   * Events are top-level groupings that contain one or more markets.
   * Use status=open for active events only.
   */
  async listEvents(
    request?: operations.PolymarketListEventsRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.PolymarketEventsResponse> {
    return unwrapAsync(polymarketListEvents(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Events Keyset
   *
   * @remarks
   * List events with filtering and sorting using keyset pagination.
   *
   * This mirrors /events but uses pagination_key instead of offset/total to
   * keep deep pagination stable.
   */
  async listEventsKeyset(
    request?: operations.PolymarketListEventsKeysetRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.PolymarketEventsKeysetResponse> {
    return unwrapAsync(polymarketListEventsKeyset(
      this,
      request,
      options,
    ));
  }

  /**
   * Get All Positions
   *
   * @remarks
   * Fetch all user positions with filtering and pagination.
   *
   * Designed for analytics and streaming use cases where clients need to:
   * - Backfill historical position data
   * - Stream new position updates as they come in
   *
   * Use `min_block` to start from a specific block (for backfill).
   * Use `order=asc` to get oldest first (for streaming/backfill).
   * Use `order=desc` to get latest first (for recent data).
   *
   * The pagination cursor encodes the last position's block/timestamp and IDs,
   * allowing efficient continuation from any point.
   */
  async listAllPositions(
    request?: operations.PolymarketListAllPositionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.AllPositionsResponse> {
    return unwrapAsync(polymarketListAllPositions(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Uma Market
   *
   * @remarks
   * Return the current UMA oracle status for a market plus its event timeline.
   *
   * Set `events_limit=0` if you only want the status header.
   */
  async getUmaMarket(
    request: operations.PolymarketGetUmaMarketRequest,
    options?: RequestOptions,
  ): Promise<data.UmaMarketDetailResponse> {
    return unwrapAsync(polymarketGetUmaMarket(
      this,
      request,
      options,
    ));
  }

  /**
   * List Uma Markets
   *
   * @remarks
   * List UMA questions filtered by state. Sorted by `last_event_at DESC`.
   */
  async listUmaMarkets(
    request: operations.PolymarketListUmaMarketsRequest,
    options?: RequestOptions,
  ): Promise<data.UmaMarketsListResponse> {
    return unwrapAsync(polymarketListUmaMarkets(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Candlesticks By Token
   *
   * @remarks
   * Fetch historical candlestick data for a single outcome token.
   *
   * Returns raw OHLCV data for this specific token — no YES/NO normalization is
   * applied, so NO-token prices stay as NO prices (e.g. ~$0.30 in a 70/30 market).
   * Volume is only from trades of this token; summing the YES and NO token volumes
   * over the same window approximates the condition-level volume.
   */
  async getCandlesticksByToken(
    request: operations.PolymarketGetCandlesticksByTokenRequest,
    options?: RequestOptions,
  ): Promise<data.CandlesticksResponse> {
    return unwrapAsync(polymarketGetCandlesticksByToken(
      this,
      request,
      options,
    ));
  }

  /**
   * Connected wallets for an address (graph-based)
   *
   * @remarks
   * Returns sibling wallets discovered via the on-chain transfer graph (USDC, pUSD, CTF) plus identity-proof signals (shared signer, shared X username, shared first funder). Confidence is 0-100; ≥70 indicates strong evidence. On a cache miss the endpoint returns 202 and computes the cluster in the background — the next call returns the full result.
   */
  async getConnectedWallets(
    request: operations.PolymarketGetConnectedWalletsRequest,
    options?: RequestOptions,
  ): Promise<operations.PolymarketGetConnectedWalletsResponse> {
    return unwrapAsync(polymarketGetConnectedWallets(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Builder Leaderboard
   *
   * @remarks
   * Ranked list of builders over the window.
   *
   * Defaults to ranking by attributed volume; `sort_by=fee` ranks by
   * `builder_fee_usd` instead (more useful when looking at revenue-earning
   * builders, since the highest-volume builders often charge 0 bps).
   *
   * Computes builder_fee_usd per row from order_filled_with_builder_fee_view
   * (which joins the current builder_fee_rates_current view), then aggregates.
   * Excludes V1 fills, the zero-sentinel builder, and rows with sign != 1.
   */
  async getBuilderLeaderboard(
    request?: operations.PolymarketGetBuilderLeaderboardRequest | undefined,
    options?: RequestOptions,
  ): Promise<data.BuilderLeaderboardResponse> {
    return unwrapAsync(polymarketGetBuilderLeaderboard(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Builder Stats
   *
   * @remarks
   * Single-builder summary plus full (taker_bps, maker_bps) history.
   */
  async getBuilderStats(
    request: operations.PolymarketGetBuilderStatsRequest,
    options?: RequestOptions,
  ): Promise<data.BuilderStats> {
    return unwrapAsync(polymarketGetBuilderStats(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Builder Markets
   *
   * @remarks
   * Top markets attributed to a builder over the window.
   *
   * Reads volume_by_builder_market_daily_view (per-(builder, market, day)
   * aggregate) for the volume/trade_count/uniq_traders, then joins
   * order_filled_with_builder_fee_view per-market for the precise
   * builder_fee_usd (since the daily MV doesn't track maker/taker split).
   */
  async getBuilderMarkets(
    request: operations.PolymarketGetBuilderMarketsRequest,
    options?: RequestOptions,
  ): Promise<data.BuilderMarketsResponse> {
    return unwrapAsync(polymarketGetBuilderMarkets(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Builder Timeseries
   *
   * @remarks
   * Bucketed volume + builder_fee over a window.
   */
  async getBuilderTimeSeries(
    request: operations.PolymarketGetBuilderTimeSeriesRequest,
    options?: RequestOptions,
  ): Promise<data.BuilderTimeseriesResponse> {
    return unwrapAsync(polymarketGetBuilderTimeSeries(
      this,
      request,
      options,
    ));
  }
}
