/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchMarkets } from "../funcs/search-markets.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Search Markets Across Venues
   *
   * @remarks
   * Search markets across all 5 venues (Polymarket, Kalshi, Limitless, Opinion, Predict.fun) in a single call.
   *
   * **Key behaviors:**
   * - Results are interleaved round-robin across venues (no single venue dominates)
   * - Fields with null values are omitted (Kalshi has no condition_id, Predict has no end_time, etc.)
   * - `venue` param order doesn't matter (`polymarket,kalshi` == `kalshi,polymarket`)
   * - Each venue's results are internally sorted by volume/relevance
   * - Cached for 15 seconds
   * - If a venue's database is unreachable, other venues still return results
   */
  async markets(
    request: operations.SearchMarketsRequest,
    options?: RequestOptions,
  ): Promise<operations.SearchMarketsResponse> {
    return unwrapAsync(searchMarkets(
      this,
      request,
      options,
    ));
  }
}
