/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transfersCreate } from "../funcs/transfers-create.js";
import { transfersGetDepositWallet } from "../funcs/transfers-get-deposit-wallet.js";
import { transfersGet } from "../funcs/transfers-get.js";
import { transfersList } from "../funcs/transfers-list.js";
import { transfersQuote } from "../funcs/transfers-quote.js";
import { transfersWithdrawDirect } from "../funcs/transfers-withdraw-direct.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import * as trading from "../models/trading/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Transfers extends ClientSDK {
  /**
   * Get Deposit Info
   *
   * @remarks
   * Fetch the account's deposit wallet — a Base USDC address that funds every venue except Hyperliquid. Send USDC here, then use Create Transfer with `from: "deposit"` and `to: "<venue>"` to fund a specific venue, or call Quote Transfer with `from: "external"` to bridge USDC in from another chain.
   */
  async getDepositWallet(
    request: operations.GetDepositInfoAccountRequest,
    options?: RequestOptions,
  ): Promise<trading.DepositInfo> {
    return unwrapAsync(transfersGetDepositWallet(
      this,
      request,
      options,
    ));
  }

  /**
   * Withdraw Funds
   *
   * @remarks
   * Withdraw funds from an enabled venue wallet to an external address.
   */
  async withdrawDirect(
    request: operations.WithdrawFundsAccountRequest,
    options?: RequestOptions,
  ): Promise<trading.WithdrawResponse> {
    return unwrapAsync(transfersWithdrawDirect(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Transfer
   *
   * @remarks
   * Move funds between the deposit wallet, a venue trading wallet, or an external address. One verb for every fund-movement direction; see the Transfers guide for the route matrix.
   */
  async create(
    request: operations.CreateTransferRequest,
    options?: RequestOptions,
  ): Promise<trading.Transfer> {
    return unwrapAsync(transfersCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List Transfers
   *
   * @remarks
   * Paginated list of the account's transfers, most-recent first.
   */
  async list(
    request: operations.ListTransfersRequest,
    options?: RequestOptions,
  ): Promise<trading.TransfersList> {
    return unwrapAsync(transfersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Transfer
   *
   * @remarks
   * Fetch a single transfer by ID. Lazy-refreshes pending rows from the bridge provider so the response always reflects the latest state.
   */
  async get(
    request: operations.GetTransferRequest,
    options?: RequestOptions,
  ): Promise<trading.Transfer> {
    return unwrapAsync(transfersGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Quote Transfer
   *
   * @remarks
   * Preview the cost and timing of a transfer before executing. For outbound (`from: "deposit"`) and internal (`from: <venue>`) transfers, accepts the same body as `POST /transfers`. For inbound (`from: "external"`), accepts a `source` object describing the partner's external wallet — the response includes a signed `transactionRequest` the partner submits from their own wallet.
   */
  async quote(
    request: operations.QuoteTransferRequest,
    options?: RequestOptions,
  ): Promise<trading.TransferQuoteResponse> {
    return unwrapAsync(transfersQuote(
      this,
      request,
      options,
    ));
  }
}
