/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const BinanceGetCandlesticksServerList = [
  "https://api.predexon.com",
] as const;

export type BinanceGetCandlesticksRequest = {
  /**
   * Trading pair
   */
  symbol: data.BinanceSymbol;
  /**
   * Candle interval
   */
  interval?: data.BinanceInterval | undefined;
  /**
   * Unix timestamp (seconds) for range start
   */
  startTime?: number | null | undefined;
  /**
   * Unix timestamp (seconds) for range end
   */
  endTime?: number | null | undefined;
  /**
   * Max candles to return
   */
  limit?: number | undefined;
};

/** @internal */
export type BinanceGetCandlesticksRequest$Outbound = {
  symbol: string;
  interval?: string | undefined;
  start_time?: number | null | undefined;
  end_time?: number | null | undefined;
  limit: number;
};

/** @internal */
export const BinanceGetCandlesticksRequest$outboundSchema: z.ZodMiniType<
  BinanceGetCandlesticksRequest$Outbound,
  BinanceGetCandlesticksRequest
> = z.pipe(
  z.object({
    symbol: data.BinanceSymbol$outboundSchema,
    interval: z.optional(data.BinanceInterval$outboundSchema),
    startTime: z.optional(z.nullable(z.int())),
    endTime: z.optional(z.nullable(z.int())),
    limit: z._default(z.int(), 500),
  }),
  z.transform((v) => {
    return remap$(v, {
      startTime: "start_time",
      endTime: "end_time",
    });
  }),
);

export function binanceGetCandlesticksRequestToJSON(
  binanceGetCandlesticksRequest: BinanceGetCandlesticksRequest,
): string {
  return JSON.stringify(
    BinanceGetCandlesticksRequest$outboundSchema.parse(
      binanceGetCandlesticksRequest,
    ),
  );
}
