/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const CancelAllOrdersAccountServerList = [
  "https://trade.predexon.com",
] as const;

export const CancelAllOrdersAccountVenue = {
  Polymarket: "polymarket",
  Predict: "predict",
  Opinion: "opinion",
  Limitless: "limitless",
  Hyperliquid: "hyperliquid",
} as const;
export type CancelAllOrdersAccountVenue = ClosedEnum<
  typeof CancelAllOrdersAccountVenue
>;

export type CancelAllOrdersAccountRequest = {
  accountId: string;
  venue?: CancelAllOrdersAccountVenue | undefined;
};

/** @internal */
export const CancelAllOrdersAccountVenue$outboundSchema: z.ZodMiniEnum<
  typeof CancelAllOrdersAccountVenue
> = z.enum(CancelAllOrdersAccountVenue);

/** @internal */
export type CancelAllOrdersAccountRequest$Outbound = {
  accountId: string;
  venue?: string | undefined;
};

/** @internal */
export const CancelAllOrdersAccountRequest$outboundSchema: z.ZodMiniType<
  CancelAllOrdersAccountRequest$Outbound,
  CancelAllOrdersAccountRequest
> = z.object({
  accountId: z.string(),
  venue: z.optional(CancelAllOrdersAccountVenue$outboundSchema),
});

export function cancelAllOrdersAccountRequestToJSON(
  cancelAllOrdersAccountRequest: CancelAllOrdersAccountRequest,
): string {
  return JSON.stringify(
    CancelAllOrdersAccountRequest$outboundSchema.parse(
      cancelAllOrdersAccountRequest,
    ),
  );
}
