/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const CancelOrderAccountServerList = [
  "https://trade.predexon.com",
] as const;

export const CancelOrderAccountVenue = {
  Polymarket: "polymarket",
  Predict: "predict",
  Opinion: "opinion",
  Limitless: "limitless",
  Hyperliquid: "hyperliquid",
} as const;
export type CancelOrderAccountVenue = ClosedEnum<
  typeof CancelOrderAccountVenue
>;

export type CancelOrderAccountRequest = {
  accountId: string;
  orderId: string;
  venue?: CancelOrderAccountVenue | undefined;
};

/** @internal */
export const CancelOrderAccountVenue$outboundSchema: z.ZodMiniEnum<
  typeof CancelOrderAccountVenue
> = z.enum(CancelOrderAccountVenue);

/** @internal */
export type CancelOrderAccountRequest$Outbound = {
  accountId: string;
  orderId: string;
  venue?: string | undefined;
};

/** @internal */
export const CancelOrderAccountRequest$outboundSchema: z.ZodMiniType<
  CancelOrderAccountRequest$Outbound,
  CancelOrderAccountRequest
> = z.object({
  accountId: z.string(),
  orderId: z.string(),
  venue: z.optional(CancelOrderAccountVenue$outboundSchema),
});

export function cancelOrderAccountRequestToJSON(
  cancelOrderAccountRequest: CancelOrderAccountRequest,
): string {
  return JSON.stringify(
    CancelOrderAccountRequest$outboundSchema.parse(cancelOrderAccountRequest),
  );
}
