/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export const CancelRouterOrderServerList = [
  "https://trade.predexon.com",
] as const;

export type CancelRouterOrderRequest = {
  accountId: string;
  routerOrderId: string;
};

/** @internal */
export type CancelRouterOrderRequest$Outbound = {
  accountId: string;
  routerOrderId: string;
};

/** @internal */
export const CancelRouterOrderRequest$outboundSchema: z.ZodMiniType<
  CancelRouterOrderRequest$Outbound,
  CancelRouterOrderRequest
> = z.object({
  accountId: z.string(),
  routerOrderId: z.string(),
});

export function cancelRouterOrderRequestToJSON(
  cancelRouterOrderRequest: CancelRouterOrderRequest,
): string {
  return JSON.stringify(
    CancelRouterOrderRequest$outboundSchema.parse(cancelRouterOrderRequest),
  );
}
