/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as trading from "../trading/index.js";

export const CreateTransferServerList = [
  "https://trade.predexon.com",
] as const;

export type CreateTransferRequest = {
  accountId: string;
  body: trading.CreateTransferRequest;
};

/** @internal */
export type CreateTransferRequest$Outbound = {
  accountId: string;
  body: trading.CreateTransferRequest$Outbound;
};

/** @internal */
export const CreateTransferRequest$outboundSchema: z.ZodMiniType<
  CreateTransferRequest$Outbound,
  CreateTransferRequest
> = z.object({
  accountId: z.string(),
  body: trading.CreateTransferRequest$outboundSchema,
});

export function createTransferRequestToJSON(
  createTransferRequest: CreateTransferRequest,
): string {
  return JSON.stringify(
    CreateTransferRequest$outboundSchema.parse(createTransferRequest),
  );
}
