/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export const DeleteAccountServerList = [
  "https://trade.predexon.com",
] as const;

export type DeleteAccountRequest = {
  accountId: string;
};

/** @internal */
export type DeleteAccountRequest$Outbound = {
  accountId: string;
};

/** @internal */
export const DeleteAccountRequest$outboundSchema: z.ZodMiniType<
  DeleteAccountRequest$Outbound,
  DeleteAccountRequest
> = z.object({
  accountId: z.string(),
});

export function deleteAccountRequestToJSON(
  deleteAccountRequest: DeleteAccountRequest,
): string {
  return JSON.stringify(
    DeleteAccountRequest$outboundSchema.parse(deleteAccountRequest),
  );
}
