/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const DflowGetWalletPositionsServerList = [
  "https://api.predexon.com",
] as const;

export type DflowGetWalletPositionsRequest = {
  /**
   * Solana wallet address (base58-encoded, 32-44 chars)
   */
  wallet: string;
  /**
   * Filter by position status: open, closed, or all (default)
   */
  status?: data.DflowPositionStatus | null | undefined;
  /**
   * Filter by specific outcome mint address
   */
  outcomeMint?: string | null | undefined;
  /**
   * Filter by market ticker (case-insensitive)
   */
  marketTicker?: string | null | undefined;
  /**
   * Sort by: total_qty_bought, total_cost_basis, or realized_pnl
   */
  sortBy?: data.DflowPositionSortBy | undefined;
  /**
   * Sort order: asc or desc
   */
  order?: data.OrderDirection | undefined;
  /**
   * Maximum number of positions to return (1-500)
   */
  limit?: number | undefined;
  /**
   * Base64-encoded cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type DflowGetWalletPositionsRequest$Outbound = {
  wallet: string;
  status?: string | null | undefined;
  outcome_mint?: string | null | undefined;
  market_ticker?: string | null | undefined;
  sort_by?: string | undefined;
  order?: string | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const DflowGetWalletPositionsRequest$outboundSchema: z.ZodMiniType<
  DflowGetWalletPositionsRequest$Outbound,
  DflowGetWalletPositionsRequest
> = z.pipe(
  z.object({
    wallet: z.string(),
    status: z.optional(z.nullable(data.DflowPositionStatus$outboundSchema)),
    outcomeMint: z.optional(z.nullable(z.string())),
    marketTicker: z.optional(z.nullable(z.string())),
    sortBy: z.optional(data.DflowPositionSortBy$outboundSchema),
    order: z.optional(data.OrderDirection$outboundSchema),
    limit: z._default(z.int(), 100),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      outcomeMint: "outcome_mint",
      marketTicker: "market_ticker",
      sortBy: "sort_by",
      paginationKey: "pagination_key",
    });
  }),
);

export function dflowGetWalletPositionsRequestToJSON(
  dflowGetWalletPositionsRequest: DflowGetWalletPositionsRequest,
): string {
  return JSON.stringify(
    DflowGetWalletPositionsRequest$outboundSchema.parse(
      dflowGetWalletPositionsRequest,
    ),
  );
}
