/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const DflowGetWalletPnLServerList = [
  "https://api.predexon.com",
] as const;

export type DflowGetWalletPnLRequest = {
  /**
   * Solana wallet address (base58-encoded, 32-44 chars)
   */
  wallet: string;
  /**
   * Time granularity: day, week, month, year, or all
   */
  granularity: data.PnLGranularity;
  /**
   * Unix timestamp (seconds) for start of range
   */
  startTime?: number | null | undefined;
  /**
   * Unix timestamp (seconds) for end of range
   */
  endTime?: number | null | undefined;
};

/** @internal */
export type DflowGetWalletPnLRequest$Outbound = {
  wallet: string;
  granularity: string;
  start_time?: number | null | undefined;
  end_time?: number | null | undefined;
};

/** @internal */
export const DflowGetWalletPnLRequest$outboundSchema: z.ZodMiniType<
  DflowGetWalletPnLRequest$Outbound,
  DflowGetWalletPnLRequest
> = z.pipe(
  z.object({
    wallet: z.string(),
    granularity: data.PnLGranularity$outboundSchema,
    startTime: z.optional(z.nullable(z.int())),
    endTime: z.optional(z.nullable(z.int())),
  }),
  z.transform((v) => {
    return remap$(v, {
      startTime: "start_time",
      endTime: "end_time",
    });
  }),
);

export function dflowGetWalletPnLRequestToJSON(
  dflowGetWalletPnLRequest: DflowGetWalletPnLRequest,
): string {
  return JSON.stringify(
    DflowGetWalletPnLRequest$outboundSchema.parse(dflowGetWalletPnLRequest),
  );
}
