/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const GetBalanceAccountServerList = [
  "https://trade.predexon.com",
] as const;

export const GetBalanceAccountVenue = {
  Polymarket: "polymarket",
  Predict: "predict",
  Opinion: "opinion",
  Limitless: "limitless",
  Hyperliquid: "hyperliquid",
} as const;
export type GetBalanceAccountVenue = ClosedEnum<typeof GetBalanceAccountVenue>;

export type GetBalanceAccountRequest = {
  accountId: string;
  venue?: GetBalanceAccountVenue | undefined;
  /**
   * When `true` (and `venue` is omitted), collapses per-venue balances into a single USD-equivalent row. The `balances` array shape is unchanged — it just contains one row instead of one per venue.
   */
  aggregated?: boolean | undefined;
};

/** @internal */
export const GetBalanceAccountVenue$outboundSchema: z.ZodMiniEnum<
  typeof GetBalanceAccountVenue
> = z.enum(GetBalanceAccountVenue);

/** @internal */
export type GetBalanceAccountRequest$Outbound = {
  accountId: string;
  venue?: string | undefined;
  aggregated?: boolean | undefined;
};

/** @internal */
export const GetBalanceAccountRequest$outboundSchema: z.ZodMiniType<
  GetBalanceAccountRequest$Outbound,
  GetBalanceAccountRequest
> = z.object({
  accountId: z.string(),
  venue: z.optional(GetBalanceAccountVenue$outboundSchema),
  aggregated: z.optional(z.boolean()),
});

export function getBalanceAccountRequestToJSON(
  getBalanceAccountRequest: GetBalanceAccountRequest,
): string {
  return JSON.stringify(
    GetBalanceAccountRequest$outboundSchema.parse(getBalanceAccountRequest),
  );
}
