/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export const GetDepositInfoAccountServerList = [
  "https://trade.predexon.com",
] as const;

export type GetDepositInfoAccountRequest = {
  accountId: string;
};

/** @internal */
export type GetDepositInfoAccountRequest$Outbound = {
  accountId: string;
};

/** @internal */
export const GetDepositInfoAccountRequest$outboundSchema: z.ZodMiniType<
  GetDepositInfoAccountRequest$Outbound,
  GetDepositInfoAccountRequest
> = z.object({
  accountId: z.string(),
});

export function getDepositInfoAccountRequestToJSON(
  getDepositInfoAccountRequest: GetDepositInfoAccountRequest,
): string {
  return JSON.stringify(
    GetDepositInfoAccountRequest$outboundSchema.parse(
      getDepositInfoAccountRequest,
    ),
  );
}
