/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export const GetRouterOrderServerList = [
  "https://trade.predexon.com",
] as const;

export type GetRouterOrderRequest = {
  accountId: string;
  routerOrderId: string;
  /**
   * Set to `true` to receive a `_routing.considered[]` audit array derived from the persisted `decisionSnapshot`. `avgPrice` and `feeBpsAtTop` are `null` on this path — neither is recoverable from a book snapshot alone. For richer audit, read `decisionSnapshot.venues[]` directly (always present on limit orders).
   */
  explain?: boolean | undefined;
};

/** @internal */
export type GetRouterOrderRequest$Outbound = {
  accountId: string;
  routerOrderId: string;
  explain?: boolean | undefined;
};

/** @internal */
export const GetRouterOrderRequest$outboundSchema: z.ZodMiniType<
  GetRouterOrderRequest$Outbound,
  GetRouterOrderRequest
> = z.object({
  accountId: z.string(),
  routerOrderId: z.string(),
  explain: z.optional(z.boolean()),
});

export function getRouterOrderRequestToJSON(
  getRouterOrderRequest: GetRouterOrderRequest,
): string {
  return JSON.stringify(
    GetRouterOrderRequest$outboundSchema.parse(getRouterOrderRequest),
  );
}
