/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const KalshiListMarketsServerList = [
  "https://api.predexon.com",
] as const;

export type KalshiListMarketsRequest = {
  /**
   * Filter by status: open or closed
   */
  status?: data.StatusOption | null | undefined;
  /**
   * Minimum last price (0-100)
   */
  minPrice?: number | null | undefined;
  /**
   * Maximum last price (0-100)
   */
  maxPrice?: number | null | undefined;
  /**
   * Minimum dollar open interest
   */
  minOpenInterest?: number | null | undefined;
  /**
   * Minimum dollar volume
   */
  minVolume?: number | null | undefined;
  /**
   * Search in title (minimum 3 characters)
   */
  search?: string | null | undefined;
  /**
   * Filter by ticker(s)
   */
  ticker?: Array<string> | null | undefined;
  /**
   * Filter by event ticker(s)
   */
  eventTicker?: Array<string> | null | undefined;
  /**
   * Filter by series ticker(s)
   */
  seriesTicker?: Array<string> | null | undefined;
  /**
   * Filter by predexon ID(s)
   */
  predexonId?: Array<string> | null | undefined;
  /**
   * Sort by
   */
  sort?: data.KalshiMarketsSortOption | undefined;
  /**
   * Number of markets to return
   */
  limit?: number | undefined;
  /**
   * Cursor for next page (from previous response)
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type KalshiListMarketsRequest$Outbound = {
  status?: string | null | undefined;
  min_price?: number | null | undefined;
  max_price?: number | null | undefined;
  min_open_interest?: number | null | undefined;
  min_volume?: number | null | undefined;
  search?: string | null | undefined;
  ticker?: Array<string> | null | undefined;
  event_ticker?: Array<string> | null | undefined;
  series_ticker?: Array<string> | null | undefined;
  predexon_id?: Array<string> | null | undefined;
  sort?: string | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const KalshiListMarketsRequest$outboundSchema: z.ZodMiniType<
  KalshiListMarketsRequest$Outbound,
  KalshiListMarketsRequest
> = z.pipe(
  z.object({
    status: z.optional(z.nullable(data.StatusOption$outboundSchema)),
    minPrice: z.optional(z.nullable(z.int())),
    maxPrice: z.optional(z.nullable(z.int())),
    minOpenInterest: z.optional(z.nullable(z.int())),
    minVolume: z.optional(z.nullable(z.int())),
    search: z.optional(z.nullable(z.string())),
    ticker: z.optional(z.nullable(z.array(z.string()))),
    eventTicker: z.optional(z.nullable(z.array(z.string()))),
    seriesTicker: z.optional(z.nullable(z.array(z.string()))),
    predexonId: z.optional(z.nullable(z.array(z.string()))),
    sort: z.optional(data.KalshiMarketsSortOption$outboundSchema),
    limit: z._default(z.int(), 20),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      minPrice: "min_price",
      maxPrice: "max_price",
      minOpenInterest: "min_open_interest",
      minVolume: "min_volume",
      eventTicker: "event_ticker",
      seriesTicker: "series_ticker",
      predexonId: "predexon_id",
      paginationKey: "pagination_key",
    });
  }),
);

export function kalshiListMarketsRequestToJSON(
  kalshiListMarketsRequest: KalshiListMarketsRequest,
): string {
  return JSON.stringify(
    KalshiListMarketsRequest$outboundSchema.parse(kalshiListMarketsRequest),
  );
}
