/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const KalshiGetTradesServerList = [
  "https://api.predexon.com",
] as const;

export type KalshiGetTradesRequest = {
  /**
   * Filter by market ticker
   */
  ticker?: string | null | undefined;
  /**
   * Filter by event ticker (prefix match)
   */
  eventTicker?: string | null | undefined;
  /**
   * Filter by taker side: yes or no
   */
  takerSide?: data.KalshiTakerSide | null | undefined;
  /**
   * Unix timestamp (seconds) for start
   */
  startTime?: number | null | undefined;
  /**
   * Unix timestamp (seconds) for end
   */
  endTime?: number | null | undefined;
  /**
   * Minimum contract count
   */
  minCount?: number | null | undefined;
  /**
   * Number of trades to return
   */
  limit?: number | undefined;
  /**
   * Sort order: asc or desc
   */
  order?: data.OrderDirection | undefined;
  /**
   * Cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type KalshiGetTradesRequest$Outbound = {
  ticker?: string | null | undefined;
  event_ticker?: string | null | undefined;
  taker_side?: string | null | undefined;
  start_time?: number | null | undefined;
  end_time?: number | null | undefined;
  min_count?: number | null | undefined;
  limit: number;
  order?: string | undefined;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const KalshiGetTradesRequest$outboundSchema: z.ZodMiniType<
  KalshiGetTradesRequest$Outbound,
  KalshiGetTradesRequest
> = z.pipe(
  z.object({
    ticker: z.optional(z.nullable(z.string())),
    eventTicker: z.optional(z.nullable(z.string())),
    takerSide: z.optional(z.nullable(data.KalshiTakerSide$outboundSchema)),
    startTime: z.optional(z.nullable(z.int())),
    endTime: z.optional(z.nullable(z.int())),
    minCount: z.optional(z.nullable(z.int())),
    limit: z._default(z.int(), 100),
    order: z.optional(data.OrderDirection$outboundSchema),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      eventTicker: "event_ticker",
      takerSide: "taker_side",
      startTime: "start_time",
      endTime: "end_time",
      minCount: "min_count",
      paginationKey: "pagination_key",
    });
  }),
);

export function kalshiGetTradesRequestToJSON(
  kalshiGetTradesRequest: KalshiGetTradesRequest,
): string {
  return JSON.stringify(
    KalshiGetTradesRequest$outboundSchema.parse(kalshiGetTradesRequest),
  );
}
