/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const OpinionListMarketsServerList = [
  "https://api.predexon.com",
] as const;

export type OpinionListMarketsRequest = {
  /**
   * Filter by status: open or closed
   */
  status?: data.StatusOption | null | undefined;
  /**
   * Filter by market type: binary or categorical
   */
  marketType?: data.MarketTypeOption | null | undefined;
  /**
   * Search in title (minimum 3 characters)
   */
  search?: string | null | undefined;
  /**
   * Filter by label(s)
   */
  labels?: Array<string> | null | undefined;
  /**
   * Minimum total volume (USD)
   */
  minVolume?: number | null | undefined;
  /**
   * Filter by condition ID(s)
   */
  conditionId?: Array<string> | null | undefined;
  /**
   * Filter by market slug(s)
   */
  marketSlug?: Array<string> | null | undefined;
  /**
   * Filter by market ID(s)
   */
  marketId?: Array<number> | null | undefined;
  /**
   * Filter by predexon ID(s)
   */
  predexonId?: Array<string> | null | undefined;
  /**
   * Filter by token ID(s)
   */
  tokenId?: Array<string> | null | undefined;
  /**
   * Filter by event/parent market ID(s)
   */
  eventId?: Array<number> | null | undefined;
  /**
   * Filter by event slug(s)
   */
  eventSlug?: Array<string> | null | undefined;
  /**
   * Sort by
   */
  sort?: data.OpinionMarketsSortOption | undefined;
  /**
   * Number of markets to return
   */
  limit?: number | undefined;
  /**
   * Cursor for next page (from previous response)
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type OpinionListMarketsRequest$Outbound = {
  status?: string | null | undefined;
  market_type?: string | null | undefined;
  search?: string | null | undefined;
  labels?: Array<string> | null | undefined;
  min_volume?: number | null | undefined;
  condition_id?: Array<string> | null | undefined;
  market_slug?: Array<string> | null | undefined;
  market_id?: Array<number> | null | undefined;
  predexon_id?: Array<string> | null | undefined;
  token_id?: Array<string> | null | undefined;
  event_id?: Array<number> | null | undefined;
  event_slug?: Array<string> | null | undefined;
  sort?: string | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const OpinionListMarketsRequest$outboundSchema: z.ZodMiniType<
  OpinionListMarketsRequest$Outbound,
  OpinionListMarketsRequest
> = z.pipe(
  z.object({
    status: z.optional(z.nullable(data.StatusOption$outboundSchema)),
    marketType: z.optional(z.nullable(data.MarketTypeOption$outboundSchema)),
    search: z.optional(z.nullable(z.string())),
    labels: z.optional(z.nullable(z.array(z.string()))),
    minVolume: z.optional(z.nullable(z.number())),
    conditionId: z.optional(z.nullable(z.array(z.string()))),
    marketSlug: z.optional(z.nullable(z.array(z.string()))),
    marketId: z.optional(z.nullable(z.array(z.int()))),
    predexonId: z.optional(z.nullable(z.array(z.string()))),
    tokenId: z.optional(z.nullable(z.array(z.string()))),
    eventId: z.optional(z.nullable(z.array(z.int()))),
    eventSlug: z.optional(z.nullable(z.array(z.string()))),
    sort: z.optional(data.OpinionMarketsSortOption$outboundSchema),
    limit: z._default(z.int(), 20),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      marketType: "market_type",
      minVolume: "min_volume",
      conditionId: "condition_id",
      marketSlug: "market_slug",
      marketId: "market_id",
      predexonId: "predexon_id",
      tokenId: "token_id",
      eventId: "event_id",
      eventSlug: "event_slug",
      paginationKey: "pagination_key",
    });
  }),
);

export function opinionListMarketsRequestToJSON(
  opinionListMarketsRequest: OpinionListMarketsRequest,
): string {
  return JSON.stringify(
    OpinionListMarketsRequest$outboundSchema.parse(opinionListMarketsRequest),
  );
}
