/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetSmartMoneyPositioningServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetSmartMoneyPositioningRequest = {
  /**
   * Market condition ID
   */
  conditionId: string;
  /**
   * Time window for metrics
   */
  window?: data.TimeWindow | undefined;
  /**
   * Minimum global realized PnL to be 'smart' (USD)
   */
  minRealizedPnl?: number | null | undefined;
  /**
   * Minimum global total PnL to be 'smart' (USD, net of fees)
   */
  minTotalPnl?: number | null | undefined;
  /**
   * Minimum global ROI to be 'smart' (decimal)
   */
  minRoi?: number | null | undefined;
  /**
   * Minimum global win rate (decimal)
   */
  minWinRate?: number | null | undefined;
  /**
   * Minimum global profit factor
   */
  minProfitFactor?: number | null | undefined;
  /**
   * Minimum global trade count
   */
  minTrades?: number | null | undefined;
  /**
   * Minimum global volume (USD)
   */
  minVolume?: number | null | undefined;
};

/** @internal */
export type PolymarketGetSmartMoneyPositioningRequest$Outbound = {
  condition_id: string;
  window?: string | undefined;
  min_realized_pnl?: number | null | undefined;
  min_total_pnl?: number | null | undefined;
  min_roi?: number | null | undefined;
  min_win_rate?: number | null | undefined;
  min_profit_factor?: number | null | undefined;
  min_trades?: number | null | undefined;
  min_volume?: number | null | undefined;
};

/** @internal */
export const PolymarketGetSmartMoneyPositioningRequest$outboundSchema:
  z.ZodMiniType<
    PolymarketGetSmartMoneyPositioningRequest$Outbound,
    PolymarketGetSmartMoneyPositioningRequest
  > = z.pipe(
    z.object({
      conditionId: z.string(),
      window: z.optional(data.TimeWindow$outboundSchema),
      minRealizedPnl: z.optional(z.nullable(z.number())),
      minTotalPnl: z.optional(z.nullable(z.number())),
      minRoi: z.optional(z.nullable(z.number())),
      minWinRate: z.optional(z.nullable(z.number())),
      minProfitFactor: z.optional(z.nullable(z.number())),
      minTrades: z.optional(z.nullable(z.int())),
      minVolume: z.optional(z.nullable(z.number())),
    }),
    z.transform((v) => {
      return remap$(v, {
        conditionId: "condition_id",
        minRealizedPnl: "min_realized_pnl",
        minTotalPnl: "min_total_pnl",
        minRoi: "min_roi",
        minWinRate: "min_win_rate",
        minProfitFactor: "min_profit_factor",
        minTrades: "min_trades",
        minVolume: "min_volume",
      });
    }),
  );

export function polymarketGetSmartMoneyPositioningRequestToJSON(
  polymarketGetSmartMoneyPositioningRequest:
    PolymarketGetSmartMoneyPositioningRequest,
): string {
  return JSON.stringify(
    PolymarketGetSmartMoneyPositioningRequest$outboundSchema.parse(
      polymarketGetSmartMoneyPositioningRequest,
    ),
  );
}
