/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetWalletPositionsServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetWalletPositionsRequest = {
  /**
   * Wallet address to fetch positions for
   */
  wallet: string;
  /**
   * Include zero-balance (closed) positions
   */
  includeClosed?: boolean | undefined;
  /**
   * Minimum number of shares to include
   */
  minShares?: number | undefined;
  /**
   * Filter by market slug
   */
  marketSlug?: string | null | undefined;
  /**
   * Filter to a specific market by condition ID
   */
  conditionId?: string | null | undefined;
  /**
   * Field to sort by
   */
  sortBy?: data.PositionSortBy | undefined;
  /**
   * Sort order: asc or desc
   */
  order?: data.OrderDirection | undefined;
  /**
   * Maximum number of positions to return (1-200)
   */
  limit?: number | undefined;
  /**
   * Cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PolymarketGetWalletPositionsRequest$Outbound = {
  wallet: string;
  include_closed: boolean;
  min_shares: number;
  market_slug?: string | null | undefined;
  condition_id?: string | null | undefined;
  sort_by?: string | undefined;
  order?: string | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PolymarketGetWalletPositionsRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetWalletPositionsRequest$Outbound,
  PolymarketGetWalletPositionsRequest
> = z.pipe(
  z.object({
    wallet: z.string(),
    includeClosed: z._default(z.boolean(), true),
    minShares: z._default(z.number(), 0),
    marketSlug: z.optional(z.nullable(z.string())),
    conditionId: z.optional(z.nullable(z.string())),
    sortBy: z.optional(data.PositionSortBy$outboundSchema),
    order: z.optional(data.OrderDirection$outboundSchema),
    limit: z._default(z.int(), 100),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      includeClosed: "include_closed",
      minShares: "min_shares",
      marketSlug: "market_slug",
      conditionId: "condition_id",
      sortBy: "sort_by",
      paginationKey: "pagination_key",
    });
  }),
);

export function polymarketGetWalletPositionsRequestToJSON(
  polymarketGetWalletPositionsRequest: PolymarketGetWalletPositionsRequest,
): string {
  return JSON.stringify(
    PolymarketGetWalletPositionsRequest$outboundSchema.parse(
      polymarketGetWalletPositionsRequest,
    ),
  );
}
