/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export const PolymarketGetBuilderTimeSeriesServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetBuilderTimeSeriesRequest = {
  /**
   * Builder code (bytes32 hex)
   */
  builderCode: string;
  /**
   * Rolling window: 24h, 7d, 30d, or all
   */
  window?: string | undefined;
  /**
   * Bucket size: 'day' or 'hour'
   */
  bucket?: string | undefined;
};

/** @internal */
export type PolymarketGetBuilderTimeSeriesRequest$Outbound = {
  builder_code: string;
  window: string;
  bucket: string;
};

/** @internal */
export const PolymarketGetBuilderTimeSeriesRequest$outboundSchema:
  z.ZodMiniType<
    PolymarketGetBuilderTimeSeriesRequest$Outbound,
    PolymarketGetBuilderTimeSeriesRequest
  > = z.pipe(
    z.object({
      builderCode: z.string(),
      window: z._default(z.string(), "30d"),
      bucket: z._default(z.string(), "day"),
    }),
    z.transform((v) => {
      return remap$(v, {
        builderCode: "builder_code",
      });
    }),
  );

export function polymarketGetBuilderTimeSeriesRequestToJSON(
  polymarketGetBuilderTimeSeriesRequest: PolymarketGetBuilderTimeSeriesRequest,
): string {
  return JSON.stringify(
    PolymarketGetBuilderTimeSeriesRequest$outboundSchema.parse(
      polymarketGetBuilderTimeSeriesRequest,
    ),
  );
}
