/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetLeaderboardServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetLeaderboardRequest = {
  /**
   * Time window for metrics
   */
  window?: data.TimeWindow | undefined;
  /**
   * Sort field
   */
  sortBy?: data.LeaderboardSortBy | undefined;
  /**
   * Sort order
   */
  order?: data.OrderDirection | undefined;
  /**
   * Comma-separated styles to include (OR logic)
   */
  style?: string | null | undefined;
  /**
   * Comma-separated styles to exclude
   */
  excludeStyle?: string | null | undefined;
  /**
   * Minimum realized PnL in USD
   */
  minRealizedPnl?: number | null | undefined;
  /**
   * Maximum realized PnL in USD
   */
  maxRealizedPnl?: number | null | undefined;
  /**
   * Minimum total PnL in USD (realized + unrealized - net fees)
   */
  minTotalPnl?: number | null | undefined;
  /**
   * Maximum total PnL in USD (realized + unrealized - net fees)
   */
  maxTotalPnl?: number | null | undefined;
  /**
   * Minimum volume in USD
   */
  minVolume?: number | null | undefined;
  /**
   * Maximum volume in USD
   */
  maxVolume?: number | null | undefined;
  /**
   * Minimum trade count
   */
  minTrades?: number | null | undefined;
  /**
   * Maximum trade count
   */
  maxTrades?: number | null | undefined;
  /**
   * Minimum ROI (decimal)
   */
  minRoi?: number | null | undefined;
  /**
   * Maximum ROI (decimal)
   */
  maxRoi?: number | null | undefined;
  /**
   * Minimum profit factor
   */
  minProfitFactor?: number | null | undefined;
  /**
   * Maximum profit factor
   */
  maxProfitFactor?: number | null | undefined;
  /**
   * Minimum win rate (decimal)
   */
  minWinRate?: number | null | undefined;
  /**
   * Maximum win rate (decimal)
   */
  maxWinRate?: number | null | undefined;
  /**
   * Minimum avg trade size in USD
   */
  minAvgTradeUsd?: number | null | undefined;
  /**
   * Maximum avg trade size in USD
   */
  maxAvgTradeUsd?: number | null | undefined;
  /**
   * Minimum wallet age in days
   */
  minWalletAgeDays?: number | null | undefined;
  /**
   * Maximum wallet age in days
   */
  maxWalletAgeDays?: number | null | undefined;
  /**
   * Minimum avg buy price (0-1)
   */
  minAvgBuyPrice?: number | null | undefined;
  /**
   * Maximum avg buy price (0-1)
   */
  maxAvgBuyPrice?: number | null | undefined;
  /**
   * Minimum avg sell price (0-1)
   */
  minAvgSellPrice?: number | null | undefined;
  /**
   * Maximum avg sell price (0-1)
   */
  maxAvgSellPrice?: number | null | undefined;
  /**
   * Minimum entry edge (avg_sell - avg_buy)
   */
  minEntryEdge?: number | null | undefined;
  /**
   * Maximum entry edge (avg_sell - avg_buy)
   */
  maxEntryEdge?: number | null | undefined;
  /**
   * Results per page
   */
  limit?: number | undefined;
  /**
   * Cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PolymarketGetLeaderboardRequest$Outbound = {
  window?: string | undefined;
  sort_by?: string | undefined;
  order?: string | undefined;
  style?: string | null | undefined;
  exclude_style?: string | null | undefined;
  min_realized_pnl?: number | null | undefined;
  max_realized_pnl?: number | null | undefined;
  min_total_pnl?: number | null | undefined;
  max_total_pnl?: number | null | undefined;
  min_volume?: number | null | undefined;
  max_volume?: number | null | undefined;
  min_trades?: number | null | undefined;
  max_trades?: number | null | undefined;
  min_roi?: number | null | undefined;
  max_roi?: number | null | undefined;
  min_profit_factor?: number | null | undefined;
  max_profit_factor?: number | null | undefined;
  min_win_rate?: number | null | undefined;
  max_win_rate?: number | null | undefined;
  min_avg_trade_usd?: number | null | undefined;
  max_avg_trade_usd?: number | null | undefined;
  min_wallet_age_days?: number | null | undefined;
  max_wallet_age_days?: number | null | undefined;
  min_avg_buy_price?: number | null | undefined;
  max_avg_buy_price?: number | null | undefined;
  min_avg_sell_price?: number | null | undefined;
  max_avg_sell_price?: number | null | undefined;
  min_entry_edge?: number | null | undefined;
  max_entry_edge?: number | null | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PolymarketGetLeaderboardRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetLeaderboardRequest$Outbound,
  PolymarketGetLeaderboardRequest
> = z.pipe(
  z.object({
    window: z.optional(data.TimeWindow$outboundSchema),
    sortBy: z.optional(data.LeaderboardSortBy$outboundSchema),
    order: z.optional(data.OrderDirection$outboundSchema),
    style: z.optional(z.nullable(z.string())),
    excludeStyle: z.optional(z.nullable(z.string())),
    minRealizedPnl: z.optional(z.nullable(z.number())),
    maxRealizedPnl: z.optional(z.nullable(z.number())),
    minTotalPnl: z.optional(z.nullable(z.number())),
    maxTotalPnl: z.optional(z.nullable(z.number())),
    minVolume: z.optional(z.nullable(z.number())),
    maxVolume: z.optional(z.nullable(z.number())),
    minTrades: z.optional(z.nullable(z.int())),
    maxTrades: z.optional(z.nullable(z.int())),
    minRoi: z.optional(z.nullable(z.number())),
    maxRoi: z.optional(z.nullable(z.number())),
    minProfitFactor: z.optional(z.nullable(z.number())),
    maxProfitFactor: z.optional(z.nullable(z.number())),
    minWinRate: z.optional(z.nullable(z.number())),
    maxWinRate: z.optional(z.nullable(z.number())),
    minAvgTradeUsd: z.optional(z.nullable(z.number())),
    maxAvgTradeUsd: z.optional(z.nullable(z.number())),
    minWalletAgeDays: z.optional(z.nullable(z.int())),
    maxWalletAgeDays: z.optional(z.nullable(z.int())),
    minAvgBuyPrice: z.optional(z.nullable(z.number())),
    maxAvgBuyPrice: z.optional(z.nullable(z.number())),
    minAvgSellPrice: z.optional(z.nullable(z.number())),
    maxAvgSellPrice: z.optional(z.nullable(z.number())),
    minEntryEdge: z.optional(z.nullable(z.number())),
    maxEntryEdge: z.optional(z.nullable(z.number())),
    limit: z._default(z.int(), 100),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      sortBy: "sort_by",
      excludeStyle: "exclude_style",
      minRealizedPnl: "min_realized_pnl",
      maxRealizedPnl: "max_realized_pnl",
      minTotalPnl: "min_total_pnl",
      maxTotalPnl: "max_total_pnl",
      minVolume: "min_volume",
      maxVolume: "max_volume",
      minTrades: "min_trades",
      maxTrades: "max_trades",
      minRoi: "min_roi",
      maxRoi: "max_roi",
      minProfitFactor: "min_profit_factor",
      maxProfitFactor: "max_profit_factor",
      minWinRate: "min_win_rate",
      maxWinRate: "max_win_rate",
      minAvgTradeUsd: "min_avg_trade_usd",
      maxAvgTradeUsd: "max_avg_trade_usd",
      minWalletAgeDays: "min_wallet_age_days",
      maxWalletAgeDays: "max_wallet_age_days",
      minAvgBuyPrice: "min_avg_buy_price",
      maxAvgBuyPrice: "max_avg_buy_price",
      minAvgSellPrice: "min_avg_sell_price",
      maxAvgSellPrice: "max_avg_sell_price",
      minEntryEdge: "min_entry_edge",
      maxEntryEdge: "max_entry_edge",
      paginationKey: "pagination_key",
    });
  }),
);

export function polymarketGetLeaderboardRequestToJSON(
  polymarketGetLeaderboardRequest: PolymarketGetLeaderboardRequest,
): string {
  return JSON.stringify(
    PolymarketGetLeaderboardRequest$outboundSchema.parse(
      polymarketGetLeaderboardRequest,
    ),
  );
}
