/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetWalletPnLServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetWalletPnLRequest = {
  /**
   * Wallet address to fetch PnL for
   */
  wallet: string;
  /**
   * Time granularity for PnL data
   */
  granularity: data.PnLGranularity;
  /**
   * Unix timestamp (seconds) for start of range
   */
  startTime?: number | null | undefined;
  /**
   * Unix timestamp (seconds) for end of range
   */
  endTime?: number | null | undefined;
  /**
   * Filter to a specific market by condition ID
   */
  conditionId?: string | null | undefined;
};

/** @internal */
export type PolymarketGetWalletPnLRequest$Outbound = {
  wallet: string;
  granularity: string;
  start_time?: number | null | undefined;
  end_time?: number | null | undefined;
  condition_id?: string | null | undefined;
};

/** @internal */
export const PolymarketGetWalletPnLRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetWalletPnLRequest$Outbound,
  PolymarketGetWalletPnLRequest
> = z.pipe(
  z.object({
    wallet: z.string(),
    granularity: data.PnLGranularity$outboundSchema,
    startTime: z.optional(z.nullable(z.int())),
    endTime: z.optional(z.nullable(z.int())),
    conditionId: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      startTime: "start_time",
      endTime: "end_time",
      conditionId: "condition_id",
    });
  }),
);

export function polymarketGetWalletPnLRequestToJSON(
  polymarketGetWalletPnLRequest: PolymarketGetWalletPnLRequest,
): string {
  return JSON.stringify(
    PolymarketGetWalletPnLRequest$outboundSchema.parse(
      polymarketGetWalletPnLRequest,
    ),
  );
}
