/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketListMarketsKeysetServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketListMarketsKeysetRequest = {
  /**
   * Filter by status: open or closed
   */
  status?: data.StatusOption | null | undefined;
  /**
   * Minimum price
   */
  minPrice?: number | null | undefined;
  /**
   * Maximum price
   */
  maxPrice?: number | null | undefined;
  /**
   * Minimum open interest (USD)
   */
  minOpenInterest?: number | null | undefined;
  /**
   * Minimum volume (USD)
   */
  minVolume?: number | null | undefined;
  /**
   * Filter by tag(s)
   */
  tags?: Array<string> | null | undefined;
  /**
   * Filter by event slug(s)
   */
  eventSlug?: Array<string> | null | undefined;
  /**
   * Search in title (minimum 3 characters)
   */
  search?: string | null | undefined;
  /**
   * Filter by condition ID(s)
   */
  conditionId?: Array<string> | null | undefined;
  /**
   * Filter by question ID(s)
   */
  questionId?: Array<string> | null | undefined;
  /**
   * Filter by market ID(s)
   */
  marketId?: Array<string> | null | undefined;
  /**
   * Filter by market slug(s)
   */
  marketSlug?: Array<string> | null | undefined;
  /**
   * Filter by token ID(s) - matches either side_a or side_b
   */
  tokenId?: Array<string> | null | undefined;
  /**
   * Filter by predexon ID(s) - matches either side_a or side_b
   */
  predexonId?: Array<string> | null | undefined;
  /**
   * Sort by
   */
  sort?: data.PolymarketMarketsSortOption | undefined;
  /**
   * Only markets with end_time after this Unix timestamp (seconds)
   */
  endAfter?: number | null | undefined;
  /**
   * Only markets with end_time before or at this Unix timestamp (seconds)
   */
  endBefore?: number | null | undefined;
  /**
   * Number of markets to return
   */
  limit?: number | undefined;
  /**
   * Cursor for the next page
   */
  paginationKey?: string | null | undefined;
  /**
   * Minimum rolling 1-day volume (USD)
   */
  minVolume1d?: number | null | undefined;
  /**
   * Minimum rolling 7-day volume (USD)
   */
  minVolume7d?: number | null | undefined;
  /**
   * Minimum rolling 30-day volume (USD)
   */
  minVolume30d?: number | null | undefined;
  /**
   * Minimum rolling 1-day trade count
   */
  minTrades1d?: number | null | undefined;
  /**
   * Minimum rolling 7-day trade count
   */
  minTrades7d?: number | null | undefined;
  /**
   * Minimum rolling 30-day trade count
   */
  minTrades30d?: number | null | undefined;
};

/** @internal */
export type PolymarketListMarketsKeysetRequest$Outbound = {
  status?: string | null | undefined;
  min_price?: number | null | undefined;
  max_price?: number | null | undefined;
  min_open_interest?: number | null | undefined;
  min_volume?: number | null | undefined;
  tags?: Array<string> | null | undefined;
  event_slug?: Array<string> | null | undefined;
  search?: string | null | undefined;
  condition_id?: Array<string> | null | undefined;
  question_id?: Array<string> | null | undefined;
  market_id?: Array<string> | null | undefined;
  market_slug?: Array<string> | null | undefined;
  token_id?: Array<string> | null | undefined;
  predexon_id?: Array<string> | null | undefined;
  sort?: string | undefined;
  end_after?: number | null | undefined;
  end_before?: number | null | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
  min_volume_1d?: number | null | undefined;
  min_volume_7d?: number | null | undefined;
  min_volume_30d?: number | null | undefined;
  min_trades_1d?: number | null | undefined;
  min_trades_7d?: number | null | undefined;
  min_trades_30d?: number | null | undefined;
};

/** @internal */
export const PolymarketListMarketsKeysetRequest$outboundSchema: z.ZodMiniType<
  PolymarketListMarketsKeysetRequest$Outbound,
  PolymarketListMarketsKeysetRequest
> = z.pipe(
  z.object({
    status: z.optional(z.nullable(data.StatusOption$outboundSchema)),
    minPrice: z.optional(z.nullable(z.number())),
    maxPrice: z.optional(z.nullable(z.number())),
    minOpenInterest: z.optional(z.nullable(z.number())),
    minVolume: z.optional(z.nullable(z.number())),
    tags: z.optional(z.nullable(z.array(z.string()))),
    eventSlug: z.optional(z.nullable(z.array(z.string()))),
    search: z.optional(z.nullable(z.string())),
    conditionId: z.optional(z.nullable(z.array(z.string()))),
    questionId: z.optional(z.nullable(z.array(z.string()))),
    marketId: z.optional(z.nullable(z.array(z.string()))),
    marketSlug: z.optional(z.nullable(z.array(z.string()))),
    tokenId: z.optional(z.nullable(z.array(z.string()))),
    predexonId: z.optional(z.nullable(z.array(z.string()))),
    sort: z.optional(data.PolymarketMarketsSortOption$outboundSchema),
    endAfter: z.optional(z.nullable(z.int())),
    endBefore: z.optional(z.nullable(z.int())),
    limit: z._default(z.int(), 20),
    paginationKey: z.optional(z.nullable(z.string())),
    minVolume1d: z.optional(z.nullable(z.number())),
    minVolume7d: z.optional(z.nullable(z.number())),
    minVolume30d: z.optional(z.nullable(z.number())),
    minTrades1d: z.optional(z.nullable(z.int())),
    minTrades7d: z.optional(z.nullable(z.int())),
    minTrades30d: z.optional(z.nullable(z.int())),
  }),
  z.transform((v) => {
    return remap$(v, {
      minPrice: "min_price",
      maxPrice: "max_price",
      minOpenInterest: "min_open_interest",
      minVolume: "min_volume",
      eventSlug: "event_slug",
      conditionId: "condition_id",
      questionId: "question_id",
      marketId: "market_id",
      marketSlug: "market_slug",
      tokenId: "token_id",
      predexonId: "predexon_id",
      endAfter: "end_after",
      endBefore: "end_before",
      paginationKey: "pagination_key",
      minVolume1d: "min_volume_1d",
      minVolume7d: "min_volume_7d",
      minVolume30d: "min_volume_30d",
      minTrades1d: "min_trades_1d",
      minTrades7d: "min_trades_7d",
      minTrades30d: "min_trades_30d",
    });
  }),
);

export function polymarketListMarketsKeysetRequestToJSON(
  polymarketListMarketsKeysetRequest: PolymarketListMarketsKeysetRequest,
): string {
  return JSON.stringify(
    PolymarketListMarketsKeysetRequest$outboundSchema.parse(
      polymarketListMarketsKeysetRequest,
    ),
  );
}
