/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetVolumeTimeSeriesServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetVolumeTimeSeriesRequest = {
  /**
   * Token ID for the market
   */
  tokenId: string;
  /**
   * Time granularity
   */
  granularity?: data.PnLGranularity | undefined;
  /**
   * Unix timestamp (seconds) for start
   */
  startTime?: number | null | undefined;
  /**
   * Unix timestamp (seconds) for end
   */
  endTime?: number | null | undefined;
};

/** @internal */
export type PolymarketGetVolumeTimeSeriesRequest$Outbound = {
  token_id: string;
  granularity?: string | undefined;
  start_time?: number | null | undefined;
  end_time?: number | null | undefined;
};

/** @internal */
export const PolymarketGetVolumeTimeSeriesRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetVolumeTimeSeriesRequest$Outbound,
  PolymarketGetVolumeTimeSeriesRequest
> = z.pipe(
  z.object({
    tokenId: z.string(),
    granularity: z.optional(data.PnLGranularity$outboundSchema),
    startTime: z.optional(z.nullable(z.int())),
    endTime: z.optional(z.nullable(z.int())),
  }),
  z.transform((v) => {
    return remap$(v, {
      tokenId: "token_id",
      startTime: "start_time",
      endTime: "end_time",
    });
  }),
);

export function polymarketGetVolumeTimeSeriesRequestToJSON(
  polymarketGetVolumeTimeSeriesRequest: PolymarketGetVolumeTimeSeriesRequest,
): string {
  return JSON.stringify(
    PolymarketGetVolumeTimeSeriesRequest$outboundSchema.parse(
      polymarketGetVolumeTimeSeriesRequest,
    ),
  );
}
