/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export const PolymarketGetMarketTopHoldersServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetMarketTopHoldersRequest = {
  /**
   * Market condition ID
   */
  conditionId: string;
  /**
   * Filter by position side: 'yes' or 'no'
   */
  side?: string | null | undefined;
  /**
   * Minimum shares held (normalized)
   */
  minShares?: number | null | undefined;
  /**
   * Minimum number of trades
   */
  minTrades?: number | null | undefined;
  /**
   * Include total holder count (slower query)
   */
  includeCount?: boolean | undefined;
  /**
   * Results per page
   */
  limit?: number | undefined;
  /**
   * Cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PolymarketGetMarketTopHoldersRequest$Outbound = {
  condition_id: string;
  side?: string | null | undefined;
  min_shares?: number | null | undefined;
  min_trades?: number | null | undefined;
  include_count: boolean;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PolymarketGetMarketTopHoldersRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetMarketTopHoldersRequest$Outbound,
  PolymarketGetMarketTopHoldersRequest
> = z.pipe(
  z.object({
    conditionId: z.string(),
    side: z.optional(z.nullable(z.string())),
    minShares: z.optional(z.nullable(z.number())),
    minTrades: z.optional(z.nullable(z.int())),
    includeCount: z._default(z.boolean(), false),
    limit: z._default(z.int(), 100),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      conditionId: "condition_id",
      minShares: "min_shares",
      minTrades: "min_trades",
      includeCount: "include_count",
      paginationKey: "pagination_key",
    });
  }),
);

export function polymarketGetMarketTopHoldersRequestToJSON(
  polymarketGetMarketTopHoldersRequest: PolymarketGetMarketTopHoldersRequest,
): string {
  return JSON.stringify(
    PolymarketGetMarketTopHoldersRequest$outboundSchema.parse(
      polymarketGetMarketTopHoldersRequest,
    ),
  );
}
