/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetWalletVolumeChartServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetWalletVolumeChartRequest = {
  /**
   * Wallet address to fetch volume chart for
   */
  wallet: string;
  /**
   * Time granularity: hour, day, or week
   */
  granularity?: data.VolumeChartGranularity | undefined;
  /**
   * Unix timestamp (seconds) for start of time range
   */
  startTime: number;
  /**
   * Unix timestamp (seconds) for end of time range
   */
  endTime: number;
};

/** @internal */
export type PolymarketGetWalletVolumeChartRequest$Outbound = {
  wallet: string;
  granularity?: string | undefined;
  start_time: number;
  end_time: number;
};

/** @internal */
export const PolymarketGetWalletVolumeChartRequest$outboundSchema:
  z.ZodMiniType<
    PolymarketGetWalletVolumeChartRequest$Outbound,
    PolymarketGetWalletVolumeChartRequest
  > = z.pipe(
    z.object({
      wallet: z.string(),
      granularity: z.optional(data.VolumeChartGranularity$outboundSchema),
      startTime: z.int(),
      endTime: z.int(),
    }),
    z.transform((v) => {
      return remap$(v, {
        startTime: "start_time",
        endTime: "end_time",
      });
    }),
  );

export function polymarketGetWalletVolumeChartRequestToJSON(
  polymarketGetWalletVolumeChartRequest: PolymarketGetWalletVolumeChartRequest,
): string {
  return JSON.stringify(
    PolymarketGetWalletVolumeChartRequest$outboundSchema.parse(
      polymarketGetWalletVolumeChartRequest,
    ),
  );
}
