/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export const PolymarketGetWalletProfileServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetWalletProfileRequest = {
  /**
   * Wallet address (hex)
   */
  wallet: string;
};

/** @internal */
export type PolymarketGetWalletProfileRequest$Outbound = {
  wallet: string;
};

/** @internal */
export const PolymarketGetWalletProfileRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetWalletProfileRequest$Outbound,
  PolymarketGetWalletProfileRequest
> = z.object({
  wallet: z.string(),
});

export function polymarketGetWalletProfileRequestToJSON(
  polymarketGetWalletProfileRequest: PolymarketGetWalletProfileRequest,
): string {
  return JSON.stringify(
    PolymarketGetWalletProfileRequest$outboundSchema.parse(
      polymarketGetWalletProfileRequest,
    ),
  );
}
