/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetCohortStatsServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetCohortStatsRequest = {
  /**
   * Time window for metrics
   */
  window?: data.TimeWindow | undefined;
  /**
   * Minimum trades to be included in cohort (filters noise)
   */
  minTrades?: number | null | undefined;
};

/** @internal */
export type PolymarketGetCohortStatsRequest$Outbound = {
  window?: string | undefined;
  min_trades?: number | null | undefined;
};

/** @internal */
export const PolymarketGetCohortStatsRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetCohortStatsRequest$Outbound,
  PolymarketGetCohortStatsRequest
> = z.pipe(
  z.object({
    window: z.optional(data.TimeWindow$outboundSchema),
    minTrades: z.optional(z.nullable(z.int())),
  }),
  z.transform((v) => {
    return remap$(v, {
      minTrades: "min_trades",
    });
  }),
);

export function polymarketGetCohortStatsRequestToJSON(
  polymarketGetCohortStatsRequest: PolymarketGetCohortStatsRequest,
): string {
  return JSON.stringify(
    PolymarketGetCohortStatsRequest$outboundSchema.parse(
      polymarketGetCohortStatsRequest,
    ),
  );
}
