/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketListAllPositionsServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketListAllPositionsRequest = {
  /**
   * Order by block number or timestamp
   */
  orderBy?: data.AllPositionsOrderBy | undefined;
  /**
   * Sort order (desc for latest first, asc for streaming from oldest)
   */
  order?: data.OrderDirection | undefined;
  /**
   * Minimum block number (inclusive)
   */
  minBlock?: number | null | undefined;
  /**
   * Maximum block number (inclusive)
   */
  maxBlock?: number | null | undefined;
  /**
   * Minimum timestamp in Unix seconds (inclusive)
   */
  minTimestamp?: number | null | undefined;
  /**
   * Maximum timestamp in Unix seconds (inclusive)
   */
  maxTimestamp?: number | null | undefined;
  /**
   * Filter by wallet address
   */
  wallet?: string | null | undefined;
  /**
   * Filter by token ID
   */
  tokenId?: string | null | undefined;
  /**
   * Filter by market condition ID
   */
  conditionId?: string | null | undefined;
  /**
   * Maximum positions per page (1-500)
   */
  limit?: number | undefined;
  /**
   * Cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PolymarketListAllPositionsRequest$Outbound = {
  order_by?: string | undefined;
  order?: string | undefined;
  min_block?: number | null | undefined;
  max_block?: number | null | undefined;
  min_timestamp?: number | null | undefined;
  max_timestamp?: number | null | undefined;
  wallet?: string | null | undefined;
  token_id?: string | null | undefined;
  condition_id?: string | null | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PolymarketListAllPositionsRequest$outboundSchema: z.ZodMiniType<
  PolymarketListAllPositionsRequest$Outbound,
  PolymarketListAllPositionsRequest
> = z.pipe(
  z.object({
    orderBy: z.optional(data.AllPositionsOrderBy$outboundSchema),
    order: z.optional(data.OrderDirection$outboundSchema),
    minBlock: z.optional(z.nullable(z.int())),
    maxBlock: z.optional(z.nullable(z.int())),
    minTimestamp: z.optional(z.nullable(z.int())),
    maxTimestamp: z.optional(z.nullable(z.int())),
    wallet: z.optional(z.nullable(z.string())),
    tokenId: z.optional(z.nullable(z.string())),
    conditionId: z.optional(z.nullable(z.string())),
    limit: z._default(z.int(), 100),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      orderBy: "order_by",
      minBlock: "min_block",
      maxBlock: "max_block",
      minTimestamp: "min_timestamp",
      maxTimestamp: "max_timestamp",
      tokenId: "token_id",
      conditionId: "condition_id",
      paginationKey: "pagination_key",
    });
  }),
);

export function polymarketListAllPositionsRequestToJSON(
  polymarketListAllPositionsRequest: PolymarketListAllPositionsRequest,
): string {
  return JSON.stringify(
    PolymarketListAllPositionsRequest$outboundSchema.parse(
      polymarketListAllPositionsRequest,
    ),
  );
}
