/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export const PolymarketGetBuilderLeaderboardServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetBuilderLeaderboardRequest = {
  /**
   * Rolling window: 24h, 7d, 30d, or all
   */
  window?: string | undefined;
  /**
   * Sort field: 'volume' or 'fee'
   */
  sortBy?: string | undefined;
  /**
   * Max entries to return
   */
  limit?: number | undefined;
};

/** @internal */
export type PolymarketGetBuilderLeaderboardRequest$Outbound = {
  window: string;
  sort_by: string;
  limit: number;
};

/** @internal */
export const PolymarketGetBuilderLeaderboardRequest$outboundSchema:
  z.ZodMiniType<
    PolymarketGetBuilderLeaderboardRequest$Outbound,
    PolymarketGetBuilderLeaderboardRequest
  > = z.pipe(
    z.object({
      window: z._default(z.string(), "7d"),
      sortBy: z._default(z.string(), "volume"),
      limit: z._default(z.int(), 50),
    }),
    z.transform((v) => {
      return remap$(v, {
        sortBy: "sort_by",
      });
    }),
  );

export function polymarketGetBuilderLeaderboardRequestToJSON(
  polymarketGetBuilderLeaderboardRequest:
    PolymarketGetBuilderLeaderboardRequest,
): string {
  return JSON.stringify(
    PolymarketGetBuilderLeaderboardRequest$outboundSchema.parse(
      polymarketGetBuilderLeaderboardRequest,
    ),
  );
}
