/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketListSmartActivityMarketsServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketListSmartActivityMarketsRequest = {
  /**
   * Time window for metrics
   */
  window?: data.TimeWindow | undefined;
  /**
   * Sort markets by this metric
   */
  sortBy?: data.SmartActivitySortBy | undefined;
  /**
   * Sort order
   */
  order?: data.OrderDirection | undefined;
  /**
   * Minimum global realized PnL to be 'smart' (USD)
   */
  minRealizedPnl?: number | null | undefined;
  /**
   * Minimum global total PnL to be 'smart' (USD, net of fees)
   */
  minTotalPnl?: number | null | undefined;
  /**
   * Minimum global ROI to be 'smart' (decimal)
   */
  minRoi?: number | null | undefined;
  /**
   * Minimum global win rate (decimal)
   */
  minWinRate?: number | null | undefined;
  /**
   * Minimum global profit factor
   */
  minProfitFactor?: number | null | undefined;
  /**
   * Minimum global trade count
   */
  minTrades?: number | null | undefined;
  /**
   * Minimum global volume (USD)
   */
  minVolume?: number | null | undefined;
  /**
   * Filter by market status: open or closed
   */
  status?: string | null | undefined;
  /**
   * Results per page
   */
  limit?: number | undefined;
  /**
   * Cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PolymarketListSmartActivityMarketsRequest$Outbound = {
  window?: string | undefined;
  sort_by?: string | undefined;
  order?: string | undefined;
  min_realized_pnl?: number | null | undefined;
  min_total_pnl?: number | null | undefined;
  min_roi?: number | null | undefined;
  min_win_rate?: number | null | undefined;
  min_profit_factor?: number | null | undefined;
  min_trades?: number | null | undefined;
  min_volume?: number | null | undefined;
  status?: string | null | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PolymarketListSmartActivityMarketsRequest$outboundSchema:
  z.ZodMiniType<
    PolymarketListSmartActivityMarketsRequest$Outbound,
    PolymarketListSmartActivityMarketsRequest
  > = z.pipe(
    z.object({
      window: z.optional(data.TimeWindow$outboundSchema),
      sortBy: z.optional(data.SmartActivitySortBy$outboundSchema),
      order: z.optional(data.OrderDirection$outboundSchema),
      minRealizedPnl: z.optional(z.nullable(z.number())),
      minTotalPnl: z.optional(z.nullable(z.number())),
      minRoi: z.optional(z.nullable(z.number())),
      minWinRate: z.optional(z.nullable(z.number())),
      minProfitFactor: z.optional(z.nullable(z.number())),
      minTrades: z.optional(z.nullable(z.int())),
      minVolume: z.optional(z.nullable(z.number())),
      status: z.optional(z.nullable(z.string())),
      limit: z._default(z.int(), 100),
      paginationKey: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        sortBy: "sort_by",
        minRealizedPnl: "min_realized_pnl",
        minTotalPnl: "min_total_pnl",
        minRoi: "min_roi",
        minWinRate: "min_win_rate",
        minProfitFactor: "min_profit_factor",
        minTrades: "min_trades",
        minVolume: "min_volume",
        paginationKey: "pagination_key",
      });
    }),
  );

export function polymarketListSmartActivityMarketsRequestToJSON(
  polymarketListSmartActivityMarketsRequest:
    PolymarketListSmartActivityMarketsRequest,
): string {
  return JSON.stringify(
    PolymarketListSmartActivityMarketsRequest$outboundSchema.parse(
      polymarketListSmartActivityMarketsRequest,
    ),
  );
}
