/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export const PolymarketGetBuilderStatsServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetBuilderStatsRequest = {
  /**
   * Builder code (bytes32 hex)
   */
  builderCode: string;
  /**
   * Rolling window: 24h, 7d, 30d, or all
   */
  window?: string | undefined;
};

/** @internal */
export type PolymarketGetBuilderStatsRequest$Outbound = {
  builder_code: string;
  window: string;
};

/** @internal */
export const PolymarketGetBuilderStatsRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetBuilderStatsRequest$Outbound,
  PolymarketGetBuilderStatsRequest
> = z.pipe(
  z.object({
    builderCode: z.string(),
    window: z._default(z.string(), "7d"),
  }),
  z.transform((v) => {
    return remap$(v, {
      builderCode: "builder_code",
    });
  }),
);

export function polymarketGetBuilderStatsRequestToJSON(
  polymarketGetBuilderStatsRequest: PolymarketGetBuilderStatsRequest,
): string {
  return JSON.stringify(
    PolymarketGetBuilderStatsRequest$outboundSchema.parse(
      polymarketGetBuilderStatsRequest,
    ),
  );
}
