/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export const PolymarketListUmaMarketsServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketListUmaMarketsRequest = {
  /**
   * UMA state: pending|proposed|disputed|reset|resolved.
   */
  state: string;
  limit?: number | undefined;
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PolymarketListUmaMarketsRequest$Outbound = {
  state: string;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PolymarketListUmaMarketsRequest$outboundSchema: z.ZodMiniType<
  PolymarketListUmaMarketsRequest$Outbound,
  PolymarketListUmaMarketsRequest
> = z.pipe(
  z.object({
    state: z.string(),
    limit: z._default(z.int(), 50),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      paginationKey: "pagination_key",
    });
  }),
);

export function polymarketListUmaMarketsRequestToJSON(
  polymarketListUmaMarketsRequest: PolymarketListUmaMarketsRequest,
): string {
  return JSON.stringify(
    PolymarketListUmaMarketsRequest$outboundSchema.parse(
      polymarketListUmaMarketsRequest,
    ),
  );
}
