/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetWalletMarketsServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetWalletMarketsRequest = {
  /**
   * Wallet address
   */
  wallet: string;
  /**
   * Time window
   */
  window?: data.TimeWindow | undefined;
  /**
   * Sort field
   */
  sortBy?: data.LeaderboardSortBy | undefined;
  /**
   * Sort order
   */
  order?: data.OrderDirection | undefined;
  /**
   * Minimum trades per market
   */
  minTrades?: number | null | undefined;
  /**
   * Results per page
   */
  limit?: number | undefined;
  /**
   * Cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PolymarketGetWalletMarketsRequest$Outbound = {
  wallet: string;
  window?: string | undefined;
  sort_by?: string | undefined;
  order?: string | undefined;
  min_trades?: number | null | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PolymarketGetWalletMarketsRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetWalletMarketsRequest$Outbound,
  PolymarketGetWalletMarketsRequest
> = z.pipe(
  z.object({
    wallet: z.string(),
    window: z.optional(data.TimeWindow$outboundSchema),
    sortBy: z.optional(data.LeaderboardSortBy$outboundSchema),
    order: z.optional(data.OrderDirection$outboundSchema),
    minTrades: z.optional(z.nullable(z.int())),
    limit: z._default(z.int(), 100),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      sortBy: "sort_by",
      minTrades: "min_trades",
      paginationKey: "pagination_key",
    });
  }),
);

export function polymarketGetWalletMarketsRequestToJSON(
  polymarketGetWalletMarketsRequest: PolymarketGetWalletMarketsRequest,
): string {
  return JSON.stringify(
    PolymarketGetWalletMarketsRequest$outboundSchema.parse(
      polymarketGetWalletMarketsRequest,
    ),
  );
}
