/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetMarketLeaderboardServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetMarketLeaderboardRequest = {
  /**
   * Market condition ID
   */
  conditionId: string;
  /**
   * Time window
   */
  window?: data.TimeWindow | undefined;
  /**
   * Sort field
   */
  sortBy?: data.LeaderboardSortBy | undefined;
  /**
   * Sort order
   */
  order?: data.OrderDirection | undefined;
  /**
   * Minimum total PnL in this market (USD, net of fees)
   */
  minTotalPnl?: number | null | undefined;
  /**
   * Maximum total PnL in this market (USD, net of fees)
   */
  maxTotalPnl?: number | null | undefined;
  /**
   * Minimum trades in this market
   */
  minTrades?: number | null | undefined;
  /**
   * Maximum trades in this market
   */
  maxTrades?: number | null | undefined;
  /**
   * Minimum volume in this market
   */
  minVolume?: number | null | undefined;
  /**
   * Maximum volume in this market
   */
  maxVolume?: number | null | undefined;
  /**
   * Minimum avg buy price (0-1)
   */
  minAvgBuyPrice?: number | null | undefined;
  /**
   * Maximum avg buy price (0-1)
   */
  maxAvgBuyPrice?: number | null | undefined;
  /**
   * Minimum avg sell price (0-1)
   */
  minAvgSellPrice?: number | null | undefined;
  /**
   * Maximum avg sell price (0-1)
   */
  maxAvgSellPrice?: number | null | undefined;
  /**
   * Minimum entry edge (avg_sell - avg_buy)
   */
  minEntryEdge?: number | null | undefined;
  /**
   * Maximum entry edge (avg_sell - avg_buy)
   */
  maxEntryEdge?: number | null | undefined;
  /**
   * Results per page
   */
  limit?: number | undefined;
  /**
   * Cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PolymarketGetMarketLeaderboardRequest$Outbound = {
  condition_id: string;
  window?: string | undefined;
  sort_by?: string | undefined;
  order?: string | undefined;
  min_total_pnl?: number | null | undefined;
  max_total_pnl?: number | null | undefined;
  min_trades?: number | null | undefined;
  max_trades?: number | null | undefined;
  min_volume?: number | null | undefined;
  max_volume?: number | null | undefined;
  min_avg_buy_price?: number | null | undefined;
  max_avg_buy_price?: number | null | undefined;
  min_avg_sell_price?: number | null | undefined;
  max_avg_sell_price?: number | null | undefined;
  min_entry_edge?: number | null | undefined;
  max_entry_edge?: number | null | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PolymarketGetMarketLeaderboardRequest$outboundSchema:
  z.ZodMiniType<
    PolymarketGetMarketLeaderboardRequest$Outbound,
    PolymarketGetMarketLeaderboardRequest
  > = z.pipe(
    z.object({
      conditionId: z.string(),
      window: z.optional(data.TimeWindow$outboundSchema),
      sortBy: z.optional(data.LeaderboardSortBy$outboundSchema),
      order: z.optional(data.OrderDirection$outboundSchema),
      minTotalPnl: z.optional(z.nullable(z.number())),
      maxTotalPnl: z.optional(z.nullable(z.number())),
      minTrades: z.optional(z.nullable(z.int())),
      maxTrades: z.optional(z.nullable(z.int())),
      minVolume: z.optional(z.nullable(z.number())),
      maxVolume: z.optional(z.nullable(z.number())),
      minAvgBuyPrice: z.optional(z.nullable(z.number())),
      maxAvgBuyPrice: z.optional(z.nullable(z.number())),
      minAvgSellPrice: z.optional(z.nullable(z.number())),
      maxAvgSellPrice: z.optional(z.nullable(z.number())),
      minEntryEdge: z.optional(z.nullable(z.number())),
      maxEntryEdge: z.optional(z.nullable(z.number())),
      limit: z._default(z.int(), 100),
      paginationKey: z.optional(z.nullable(z.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        conditionId: "condition_id",
        sortBy: "sort_by",
        minTotalPnl: "min_total_pnl",
        maxTotalPnl: "max_total_pnl",
        minTrades: "min_trades",
        maxTrades: "max_trades",
        minVolume: "min_volume",
        maxVolume: "max_volume",
        minAvgBuyPrice: "min_avg_buy_price",
        maxAvgBuyPrice: "max_avg_buy_price",
        minAvgSellPrice: "min_avg_sell_price",
        maxAvgSellPrice: "max_avg_sell_price",
        minEntryEdge: "min_entry_edge",
        maxEntryEdge: "max_entry_edge",
        paginationKey: "pagination_key",
      });
    }),
  );

export function polymarketGetMarketLeaderboardRequestToJSON(
  polymarketGetMarketLeaderboardRequest: PolymarketGetMarketLeaderboardRequest,
): string {
  return JSON.stringify(
    PolymarketGetMarketLeaderboardRequest$outboundSchema.parse(
      polymarketGetMarketLeaderboardRequest,
    ),
  );
}
