/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetTradesServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetTradesRequest = {
  /**
   * Filter by market slug
   */
  marketSlug?: string | null | undefined;
  /**
   * Filter by condition ID
   */
  conditionId?: string | null | undefined;
  /**
   * Filter by token ID
   */
  tokenId?: string | null | undefined;
  /**
   * Unix timestamp (seconds) for start
   */
  startTime?: number | null | undefined;
  /**
   * Unix timestamp (seconds) for end
   */
  endTime?: number | null | undefined;
  /**
   * Minimum trade amount in USD
   */
  minTotal?: number | null | undefined;
  /**
   * Number of trades to return
   */
  limit?: number | undefined;
  /**
   * Filter by wallet address
   */
  wallet?: string | null | undefined;
  /**
   * Filter by V2 builder attribution tag (bytes32 hex, 0x + 64 hex chars)
   */
  builder?: string | null | undefined;
  /**
   * Sort order: asc or desc
   */
  order?: data.OrderDirection | undefined;
  /**
   * Cursor for pagination
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PolymarketGetTradesRequest$Outbound = {
  market_slug?: string | null | undefined;
  condition_id?: string | null | undefined;
  token_id?: string | null | undefined;
  start_time?: number | null | undefined;
  end_time?: number | null | undefined;
  min_total?: number | null | undefined;
  limit: number;
  wallet?: string | null | undefined;
  builder?: string | null | undefined;
  order?: string | undefined;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PolymarketGetTradesRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetTradesRequest$Outbound,
  PolymarketGetTradesRequest
> = z.pipe(
  z.object({
    marketSlug: z.optional(z.nullable(z.string())),
    conditionId: z.optional(z.nullable(z.string())),
    tokenId: z.optional(z.nullable(z.string())),
    startTime: z.optional(z.nullable(z.int())),
    endTime: z.optional(z.nullable(z.int())),
    minTotal: z.optional(z.nullable(z.number())),
    limit: z._default(z.int(), 100),
    wallet: z.optional(z.nullable(z.string())),
    builder: z.optional(z.nullable(z.string())),
    order: z.optional(data.OrderDirection$outboundSchema),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      marketSlug: "market_slug",
      conditionId: "condition_id",
      tokenId: "token_id",
      startTime: "start_time",
      endTime: "end_time",
      minTotal: "min_total",
      paginationKey: "pagination_key",
    });
  }),
);

export function polymarketGetTradesRequestToJSON(
  polymarketGetTradesRequest: PolymarketGetTradesRequest,
): string {
  return JSON.stringify(
    PolymarketGetTradesRequest$outboundSchema.parse(polymarketGetTradesRequest),
  );
}
