/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export const PolymarketGetCandlesticksByTokenServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetCandlesticksByTokenRequest = {
  /**
   * Outcome token ID
   */
  tokenId: string;
  /**
   * Unix timestamp (seconds) for start of time range
   */
  startTime?: number | null | undefined;
  /**
   * Unix timestamp (seconds) for end of time range
   */
  endTime?: number | null | undefined;
  /**
   * Interval: 0=auto, 1=1m, 5=5m, 15=15m, 60=1h, 1440=1d
   */
  interval?: number | undefined;
};

/** @internal */
export type PolymarketGetCandlesticksByTokenRequest$Outbound = {
  token_id: string;
  start_time?: number | null | undefined;
  end_time?: number | null | undefined;
  interval: number;
};

/** @internal */
export const PolymarketGetCandlesticksByTokenRequest$outboundSchema:
  z.ZodMiniType<
    PolymarketGetCandlesticksByTokenRequest$Outbound,
    PolymarketGetCandlesticksByTokenRequest
  > = z.pipe(
    z.object({
      tokenId: z.string(),
      startTime: z.optional(z.nullable(z.int())),
      endTime: z.optional(z.nullable(z.int())),
      interval: z._default(z.int(), 0),
    }),
    z.transform((v) => {
      return remap$(v, {
        tokenId: "token_id",
        startTime: "start_time",
        endTime: "end_time",
      });
    }),
  );

export function polymarketGetCandlesticksByTokenRequestToJSON(
  polymarketGetCandlesticksByTokenRequest:
    PolymarketGetCandlesticksByTokenRequest,
): string {
  return JSON.stringify(
    PolymarketGetCandlesticksByTokenRequest$outboundSchema.parse(
      polymarketGetCandlesticksByTokenRequest,
    ),
  );
}
