/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketListCryptoMarketsServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketListCryptoMarketsRequest = {
  /**
   * Filter by crypto asset: btc, eth, sol, xrp, hype, doge, bnb
   */
  asset?: data.CryptoAsset | null | undefined;
  /**
   * Filter by timeframe: 5m, 15m, 1h, 4h, daily
   */
  timeframe?: data.CryptoTimeframe | null | undefined;
  /**
   * Filter by market status: open, closed
   */
  status?: data.StatusFilter | null | undefined;
  /**
   * Only markets with end_time after this Unix timestamp
   */
  endAfter?: number | null | undefined;
  /**
   * Only markets with end_time before or at this Unix timestamp
   */
  endBefore?: number | null | undefined;
  /**
   * Sort by end_time: desc (most recent first) or asc (chronological)
   */
  sort?: data.SortOrder | undefined;
  /**
   * Number of markets to return
   */
  limit?: number | undefined;
  /**
   * Offset for pagination
   */
  offset?: number | undefined;
};

/** @internal */
export type PolymarketListCryptoMarketsRequest$Outbound = {
  asset?: string | null | undefined;
  timeframe?: string | null | undefined;
  status?: string | null | undefined;
  end_after?: number | null | undefined;
  end_before?: number | null | undefined;
  sort?: string | undefined;
  limit: number;
  offset: number;
};

/** @internal */
export const PolymarketListCryptoMarketsRequest$outboundSchema: z.ZodMiniType<
  PolymarketListCryptoMarketsRequest$Outbound,
  PolymarketListCryptoMarketsRequest
> = z.pipe(
  z.object({
    asset: z.optional(z.nullable(data.CryptoAsset$outboundSchema)),
    timeframe: z.optional(z.nullable(data.CryptoTimeframe$outboundSchema)),
    status: z.optional(z.nullable(data.StatusFilter$outboundSchema)),
    endAfter: z.optional(z.nullable(z.int())),
    endBefore: z.optional(z.nullable(z.int())),
    sort: z.optional(data.SortOrder$outboundSchema),
    limit: z._default(z.int(), 50),
    offset: z._default(z.int(), 0),
  }),
  z.transform((v) => {
    return remap$(v, {
      endAfter: "end_after",
      endBefore: "end_before",
    });
  }),
);

export function polymarketListCryptoMarketsRequestToJSON(
  polymarketListCryptoMarketsRequest: PolymarketListCryptoMarketsRequest,
): string {
  return JSON.stringify(
    PolymarketListCryptoMarketsRequest$outboundSchema.parse(
      polymarketListCryptoMarketsRequest,
    ),
  );
}
