/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export const PolymarketGetCandlesticksServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetCandlesticksRequest = {
  /**
   * Condition ID for the market
   */
  conditionId: string;
  /**
   * Unix timestamp (seconds) for start of time range
   */
  startTime?: number | null | undefined;
  /**
   * Unix timestamp (seconds) for end of time range
   */
  endTime?: number | null | undefined;
  /**
   * Interval: 0=auto, 1=1m, 5=5m, 15=15m, 60=1h, 1440=1d
   */
  interval?: number | undefined;
};

/** @internal */
export type PolymarketGetCandlesticksRequest$Outbound = {
  condition_id: string;
  start_time?: number | null | undefined;
  end_time?: number | null | undefined;
  interval: number;
};

/** @internal */
export const PolymarketGetCandlesticksRequest$outboundSchema: z.ZodMiniType<
  PolymarketGetCandlesticksRequest$Outbound,
  PolymarketGetCandlesticksRequest
> = z.pipe(
  z.object({
    conditionId: z.string(),
    startTime: z.optional(z.nullable(z.int())),
    endTime: z.optional(z.nullable(z.int())),
    interval: z._default(z.int(), 0),
  }),
  z.transform((v) => {
    return remap$(v, {
      conditionId: "condition_id",
      startTime: "start_time",
      endTime: "end_time",
    });
  }),
);

export function polymarketGetCandlesticksRequestToJSON(
  polymarketGetCandlesticksRequest: PolymarketGetCandlesticksRequest,
): string {
  return JSON.stringify(
    PolymarketGetCandlesticksRequest$outboundSchema.parse(
      polymarketGetCandlesticksRequest,
    ),
  );
}
