/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PolymarketGetOpenInterestTimeSeriesServerList = [
  "https://api.predexon.com",
] as const;

export type PolymarketGetOpenInterestTimeSeriesRequest = {
  /**
   * Condition ID for the market
   */
  conditionId: string;
  /**
   * Time granularity
   */
  granularity?: data.PnLGranularity | undefined;
  /**
   * Unix timestamp (seconds) for start
   */
  startTime?: number | null | undefined;
  /**
   * Unix timestamp (seconds) for end
   */
  endTime?: number | null | undefined;
};

/** @internal */
export type PolymarketGetOpenInterestTimeSeriesRequest$Outbound = {
  condition_id: string;
  granularity?: string | undefined;
  start_time?: number | null | undefined;
  end_time?: number | null | undefined;
};

/** @internal */
export const PolymarketGetOpenInterestTimeSeriesRequest$outboundSchema:
  z.ZodMiniType<
    PolymarketGetOpenInterestTimeSeriesRequest$Outbound,
    PolymarketGetOpenInterestTimeSeriesRequest
  > = z.pipe(
    z.object({
      conditionId: z.string(),
      granularity: z.optional(data.PnLGranularity$outboundSchema),
      startTime: z.optional(z.nullable(z.int())),
      endTime: z.optional(z.nullable(z.int())),
    }),
    z.transform((v) => {
      return remap$(v, {
        conditionId: "condition_id",
        startTime: "start_time",
        endTime: "end_time",
      });
    }),
  );

export function polymarketGetOpenInterestTimeSeriesRequestToJSON(
  polymarketGetOpenInterestTimeSeriesRequest:
    PolymarketGetOpenInterestTimeSeriesRequest,
): string {
  return JSON.stringify(
    PolymarketGetOpenInterestTimeSeriesRequest$outboundSchema.parse(
      polymarketGetOpenInterestTimeSeriesRequest,
    ),
  );
}
