/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as data from "../data/index.js";

export const PredictfunListMarketsServerList = [
  "https://api.predexon.com",
] as const;

export type PredictfunListMarketsRequest = {
  /**
   * Filter by status: open or closed
   */
  status?: data.StatusOption | null | undefined;
  /**
   * Filter by market variant: DEFAULT, CRYPTO_UP_DOWN, SPORTS_TEAM_MATCH, SPORTS_MATCH, TWEET_COUNT
   */
  marketVariant?: data.MarketVariantOption | null | undefined;
  /**
   * Search in title (minimum 3 characters)
   */
  search?: string | null | undefined;
  /**
   * Minimum bid depth
   */
  minBidDepth?: number | null | undefined;
  /**
   * Filter by condition ID(s)
   */
  conditionId?: Array<string> | null | undefined;
  /**
   * Filter by market slug(s)
   */
  marketSlug?: Array<string> | null | undefined;
  /**
   * Filter by market ID(s)
   */
  marketId?: Array<number> | null | undefined;
  /**
   * Filter by token ID(s)
   */
  tokenId?: Array<string> | null | undefined;
  /**
   * Filter by predexon ID(s)
   */
  predexonId?: Array<string> | null | undefined;
  /**
   * Filter by event slug(s) — returns all outcomes under that event
   */
  eventSlug?: Array<string> | null | undefined;
  /**
   * Sort by
   */
  sort?: data.PredictfunMarketsSortOption | undefined;
  /**
   * Number of markets to return
   */
  limit?: number | undefined;
  /**
   * Cursor for next page (from previous response)
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PredictfunListMarketsRequest$Outbound = {
  status?: string | null | undefined;
  market_variant?: string | null | undefined;
  search?: string | null | undefined;
  min_bid_depth?: number | null | undefined;
  condition_id?: Array<string> | null | undefined;
  market_slug?: Array<string> | null | undefined;
  market_id?: Array<number> | null | undefined;
  token_id?: Array<string> | null | undefined;
  predexon_id?: Array<string> | null | undefined;
  event_slug?: Array<string> | null | undefined;
  sort?: string | undefined;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PredictfunListMarketsRequest$outboundSchema: z.ZodMiniType<
  PredictfunListMarketsRequest$Outbound,
  PredictfunListMarketsRequest
> = z.pipe(
  z.object({
    status: z.optional(z.nullable(data.StatusOption$outboundSchema)),
    marketVariant: z.optional(
      z.nullable(data.MarketVariantOption$outboundSchema),
    ),
    search: z.optional(z.nullable(z.string())),
    minBidDepth: z.optional(z.nullable(z.number())),
    conditionId: z.optional(z.nullable(z.array(z.string()))),
    marketSlug: z.optional(z.nullable(z.array(z.string()))),
    marketId: z.optional(z.nullable(z.array(z.int()))),
    tokenId: z.optional(z.nullable(z.array(z.string()))),
    predexonId: z.optional(z.nullable(z.array(z.string()))),
    eventSlug: z.optional(z.nullable(z.array(z.string()))),
    sort: z.optional(data.PredictfunMarketsSortOption$outboundSchema),
    limit: z._default(z.int(), 20),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      marketVariant: "market_variant",
      minBidDepth: "min_bid_depth",
      conditionId: "condition_id",
      marketSlug: "market_slug",
      marketId: "market_id",
      tokenId: "token_id",
      predexonId: "predexon_id",
      eventSlug: "event_slug",
      paginationKey: "pagination_key",
    });
  }),
);

export function predictfunListMarketsRequestToJSON(
  predictfunListMarketsRequest: PredictfunListMarketsRequest,
): string {
  return JSON.stringify(
    PredictfunListMarketsRequest$outboundSchema.parse(
      predictfunListMarketsRequest,
    ),
  );
}
