/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export const PredictfunGetOrderbookHistoryServerList = [
  "https://api.predexon.com",
] as const;

export type PredictfunGetOrderbookHistoryRequest = {
  /**
   * The PredictFun market ID
   */
  marketId: number;
  /**
   * Start time in Unix timestamp (milliseconds)
   */
  startTime: number;
  /**
   * End time in Unix timestamp (milliseconds)
   */
  endTime: number;
  /**
   * Maximum number of snapshots to return
   */
  limit?: number | undefined;
  /**
   * Pagination key to get the next chunk of data
   */
  paginationKey?: string | null | undefined;
};

/** @internal */
export type PredictfunGetOrderbookHistoryRequest$Outbound = {
  market_id: number;
  start_time: number;
  end_time: number;
  limit: number;
  pagination_key?: string | null | undefined;
};

/** @internal */
export const PredictfunGetOrderbookHistoryRequest$outboundSchema: z.ZodMiniType<
  PredictfunGetOrderbookHistoryRequest$Outbound,
  PredictfunGetOrderbookHistoryRequest
> = z.pipe(
  z.object({
    marketId: z.int(),
    startTime: z.int(),
    endTime: z.int(),
    limit: z._default(z.int(), 100),
    paginationKey: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      marketId: "market_id",
      startTime: "start_time",
      endTime: "end_time",
      paginationKey: "pagination_key",
    });
  }),
);

export function predictfunGetOrderbookHistoryRequestToJSON(
  predictfunGetOrderbookHistoryRequest: PredictfunGetOrderbookHistoryRequest,
): string {
  return JSON.stringify(
    PredictfunGetOrderbookHistoryRequest$outboundSchema.parse(
      predictfunGetOrderbookHistoryRequest,
    ),
  );
}
