/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as trading from "../trading/index.js";

export const RedeemPositionAccountServerList = [
  "https://trade.predexon.com",
] as const;

export type RedeemPositionAccountRequest = {
  accountId: string;
  body: trading.AccountRedeemRequest;
};

/** @internal */
export type RedeemPositionAccountRequest$Outbound = {
  accountId: string;
  body: trading.AccountRedeemRequest$Outbound;
};

/** @internal */
export const RedeemPositionAccountRequest$outboundSchema: z.ZodMiniType<
  RedeemPositionAccountRequest$Outbound,
  RedeemPositionAccountRequest
> = z.object({
  accountId: z.string(),
  body: trading.AccountRedeemRequest$outboundSchema,
});

export function redeemPositionAccountRequestToJSON(
  redeemPositionAccountRequest: RedeemPositionAccountRequest,
): string {
  return JSON.stringify(
    RedeemPositionAccountRequest$outboundSchema.parse(
      redeemPositionAccountRequest,
    ),
  );
}
