/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as trading from "../trading/index.js";

export const RouterPlaceOrderServerList = [
  "https://trade.predexon.com",
] as const;

export type RouterPlaceOrderRequest = {
  accountId: string;
  /**
   * Set to `true` to receive a `_routing.considered[]` audit array on the response — per-venue projection (top-of-book, fee at top, dropped reason) for every venue the router looked at. Defaults to `false` for a slim response.
   */
  explain?: boolean | undefined;
  body: trading.RouterPlaceOrderRequest;
};

/** @internal */
export type RouterPlaceOrderRequest$Outbound = {
  accountId: string;
  explain?: boolean | undefined;
  body: trading.RouterPlaceOrderRequest$Outbound;
};

/** @internal */
export const RouterPlaceOrderRequest$outboundSchema: z.ZodMiniType<
  RouterPlaceOrderRequest$Outbound,
  RouterPlaceOrderRequest
> = z.object({
  accountId: z.string(),
  explain: z.optional(z.boolean()),
  body: trading.RouterPlaceOrderRequest$outboundSchema,
});

export function routerPlaceOrderRequestToJSON(
  routerPlaceOrderRequest: RouterPlaceOrderRequest,
): string {
  return JSON.stringify(
    RouterPlaceOrderRequest$outboundSchema.parse(routerPlaceOrderRequest),
  );
}
