/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { Activity, Activity$inboundSchema } from "./activity.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";

/**
 * Activity endpoint response.
 */
export type ActivityResponse = {
  activities: Array<Activity>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const ActivityResponse$inboundSchema: z.ZodMiniType<
  ActivityResponse,
  unknown
> = z.object({
  activities: z.array(Activity$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function activityResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActivityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityResponse' from JSON`,
  );
}
