/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Sort options for activity.
 */
export const ActivitySortBy = {
  Timestamp: "timestamp",
  Type: "type",
} as const;
/**
 * Sort options for activity.
 */
export type ActivitySortBy = ClosedEnum<typeof ActivitySortBy>;

/** @internal */
export const ActivitySortBy$outboundSchema: z.ZodMiniEnum<
  typeof ActivitySortBy
> = z.enum(ActivitySortBy);
