/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { ActivitySide, ActivitySide$inboundSchema } from "./activity-side.js";

/**
 * Activity model.
 */
export type Activity = {
  /**
   * Activity side enum.
   */
  side: ActivitySide;
  marketSlug: string;
  /**
   * Gamma market row id (numeric string). Populated for SPLIT/MERGE/REDEEM. Null for CONVERT — see `neg_risk_market_id` instead.
   */
  marketId?: string | null | undefined;
  /**
   * NegRisk parent market identifier (32-byte hex). Matches Gamma's `Event.negRiskMarketID`. Populated only for CONVERT rows.
   */
  negRiskMarketId?: string | null | undefined;
  /**
   * CTF condition ID for SPLIT/MERGE/REDEEM (per-outcome). Empty string for CONVERT — conversions are market-level, so use `neg_risk_market_id`.
   */
  conditionId: string;
  /**
   * NegRisk indexSet bitmask (decimal string) — which outcomes were involved. Populated only for CONVERT rows; null for other sides.
   */
  indexSet?: string | null | undefined;
  /**
   * Raw number of shares from blockchain
   */
  shares: number;
  /**
   * Shares normalized (raw / 1000000)
   */
  sharesNormalized: number;
  /**
   * USD value of the activity
   */
  amountUsd: number;
  price: number;
  txHash: string;
  title: string;
  /**
   * Unix timestamp in seconds
   */
  timestamp: number;
  /**
   * User wallet address
   */
  user: string;
};

/** @internal */
export const Activity$inboundSchema: z.ZodMiniType<Activity, unknown> = z.pipe(
  z.object({
    side: ActivitySide$inboundSchema,
    market_slug: types.string(),
    market_id: z.optional(z.nullable(types.string())),
    neg_risk_market_id: z.optional(z.nullable(types.string())),
    condition_id: types.string(),
    index_set: z.optional(z.nullable(types.string())),
    shares: types.number(),
    shares_normalized: types.number(),
    amount_usd: types.number(),
    price: types.number(),
    tx_hash: types.string(),
    title: types.string(),
    timestamp: types.number(),
    user: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "market_slug": "marketSlug",
      "market_id": "marketId",
      "neg_risk_market_id": "negRiskMarketId",
      "condition_id": "conditionId",
      "index_set": "indexSet",
      "shares_normalized": "sharesNormalized",
      "amount_usd": "amountUsd",
      "tx_hash": "txHash",
    });
  }),
);

export function activityFromJSON(
  jsonString: string,
): SafeParseResult<Activity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Activity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Activity' from JSON`,
  );
}
