/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  AllUsersPosition,
  AllUsersPosition$inboundSchema,
} from "./all-users-position.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";

/**
 * Response for all-user positions endpoint.
 */
export type AllPositionsResponse = {
  /**
   * Position records
   */
  positions: Array<AllUsersPosition>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const AllPositionsResponse$inboundSchema: z.ZodMiniType<
  AllPositionsResponse,
  unknown
> = z.object({
  positions: z.array(AllUsersPosition$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function allPositionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AllPositionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AllPositionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AllPositionsResponse' from JSON`,
  );
}
