/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Single OHLCV candlestick derived from book ticker mid-prices.
 *
 * @remarks
 *
 * Open/high/low/close reflect the mid-price (not trade price).
 * tick_count indicates market activity density within the candle.
 */
export type BinanceCandleData = {
  /**
   * Unix timestamp (seconds) at period start
   */
  timestamp: number;
  /**
   * Opening mid-price in USDT
   */
  open: number;
  /**
   * Highest mid-price in USDT
   */
  high: number;
  /**
   * Lowest mid-price in USDT
   */
  low: number;
  /**
   * Closing mid-price in USDT
   */
  close: number;
  /**
   * Number of book ticker updates in this candle
   */
  tickCount: number;
  /**
   * Average bid-ask spread over this candle
   */
  avgSpread: number;
};

/** @internal */
export const BinanceCandleData$inboundSchema: z.ZodMiniType<
  BinanceCandleData,
  unknown
> = z.pipe(
  z.object({
    timestamp: types.number(),
    open: types.number(),
    high: types.number(),
    low: types.number(),
    close: types.number(),
    tick_count: types.number(),
    avg_spread: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tick_count": "tickCount",
      "avg_spread": "avgSpread",
    });
  }),
);

export function binanceCandleDataFromJSON(
  jsonString: string,
): SafeParseResult<BinanceCandleData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BinanceCandleData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BinanceCandleData' from JSON`,
  );
}
