/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  BinanceTickData,
  BinanceTickData$inboundSchema,
} from "./binance-tick-data.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";

/**
 * Paginated response of raw book ticker data.
 *
 * @remarks
 *
 * Use cursor-based pagination to iterate through large time windows.
 * A 15-minute window typically contains ~63K ticks per symbol.
 */
export type BinanceTicksResponse = {
  /**
   * Trading pair (e.g. BTCUSDT)
   */
  symbol: string;
  /**
   * Array of tick data points, ordered by timestamp ASC
   */
  ticks: Array<BinanceTickData>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const BinanceTicksResponse$inboundSchema: z.ZodMiniType<
  BinanceTicksResponse,
  unknown
> = z.object({
  symbol: types.string(),
  ticks: z.array(BinanceTickData$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function binanceTicksResponseFromJSON(
  jsonString: string,
): SafeParseResult<BinanceTicksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BinanceTicksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BinanceTicksResponse' from JSON`,
  );
}
