/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  BuilderMarketEntry,
  BuilderMarketEntry$inboundSchema,
} from "./builder-market-entry.js";

/**
 * Response for builder top-markets endpoint.
 */
export type BuilderMarketsResponse = {
  builderCode: string;
  window: string;
  entries: Array<BuilderMarketEntry>;
};

/** @internal */
export const BuilderMarketsResponse$inboundSchema: z.ZodMiniType<
  BuilderMarketsResponse,
  unknown
> = z.pipe(
  z.object({
    builder_code: types.string(),
    window: types.string(),
    entries: z.array(BuilderMarketEntry$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "builder_code": "builderCode",
    });
  }),
);

export function builderMarketsResponseFromJSON(
  jsonString: string,
): SafeParseResult<BuilderMarketsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BuilderMarketsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BuilderMarketsResponse' from JSON`,
  );
}
