/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * One row in the builder leaderboard.
 */
export type BuilderLeaderboardEntry = {
  /**
   * Position in leaderboard (1-indexed)
   */
  rank: number;
  /**
   * Builder code (bytes32 hex)
   */
  builderCode: string;
  /**
   * Attributed trade notional in USD over the window
   */
  volumeUsd: number;
  /**
   * Builder fee revenue in USD over the window
   */
  builderFeeUsd: number;
  /**
   * Platform fee on attributed trades (informational)
   */
  platformFeeUsd: number;
  /**
   * Number of V2 OrderFilled rows attributed to this builder
   */
  tradeCount: number;
  /**
   * Unique non-internal addresses that traded via this builder
   */
  uniqueTraders: number;
  /**
   * Unique condition_ids touched
   */
  uniqueMarkets: number;
  /**
   * Current taker bps (null if rate not yet fetched)
   */
  currentTakerBps?: number | null | undefined;
  /**
   * Current maker bps (null if rate not yet fetched)
   */
  currentMakerBps?: number | null | undefined;
};

/** @internal */
export const BuilderLeaderboardEntry$inboundSchema: z.ZodMiniType<
  BuilderLeaderboardEntry,
  unknown
> = z.pipe(
  z.object({
    rank: types.number(),
    builder_code: types.string(),
    volume_usd: types.number(),
    builder_fee_usd: types.number(),
    platform_fee_usd: types.number(),
    trade_count: types.number(),
    unique_traders: types.number(),
    unique_markets: types.number(),
    current_taker_bps: z.optional(z.nullable(types.number())),
    current_maker_bps: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "builder_code": "builderCode",
      "volume_usd": "volumeUsd",
      "builder_fee_usd": "builderFeeUsd",
      "platform_fee_usd": "platformFeeUsd",
      "trade_count": "tradeCount",
      "unique_traders": "uniqueTraders",
      "unique_markets": "uniqueMarkets",
      "current_taker_bps": "currentTakerBps",
      "current_maker_bps": "currentMakerBps",
    });
  }),
);

export function builderLeaderboardEntryFromJSON(
  jsonString: string,
): SafeParseResult<BuilderLeaderboardEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BuilderLeaderboardEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BuilderLeaderboardEntry' from JSON`,
  );
}
