/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  BuilderTimeseriesPoint,
  BuilderTimeseriesPoint$inboundSchema,
} from "./builder-timeseries-point.js";

/**
 * Response for builder timeseries endpoint.
 */
export type BuilderTimeseriesResponse = {
  builderCode: string;
  window: string;
  /**
   * Bucket size: 'day' or 'hour'
   */
  bucket: string;
  points: Array<BuilderTimeseriesPoint>;
};

/** @internal */
export const BuilderTimeseriesResponse$inboundSchema: z.ZodMiniType<
  BuilderTimeseriesResponse,
  unknown
> = z.pipe(
  z.object({
    builder_code: types.string(),
    window: types.string(),
    bucket: types.string(),
    points: z.array(BuilderTimeseriesPoint$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "builder_code": "builderCode",
    });
  }),
);

export function builderTimeseriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<BuilderTimeseriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BuilderTimeseriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BuilderTimeseriesResponse' from JSON`,
  );
}
