/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * A single (taker_bps, maker_bps) validity window for one builder.
 */
export type BuilderFeeRateHistoryEntry = {
  /**
   * Taker-leg fee in basis points (0-100)
   */
  takerBps: number;
  /**
   * Maker-leg fee in basis points (0-50)
   */
  makerBps: number;
  /**
   * Unix timestamp the rate took effect
   */
  validFrom: number;
  /**
   * Unix timestamp the rate stopped applying (far-future for current)
   */
  validTo: number;
};

/** @internal */
export const BuilderFeeRateHistoryEntry$inboundSchema: z.ZodMiniType<
  BuilderFeeRateHistoryEntry,
  unknown
> = z.pipe(
  z.object({
    taker_bps: types.number(),
    maker_bps: types.number(),
    valid_from: types.number(),
    valid_to: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "taker_bps": "takerBps",
      "maker_bps": "makerBps",
      "valid_from": "validFrom",
      "valid_to": "validTo",
    });
  }),
);

export function builderFeeRateHistoryEntryFromJSON(
  jsonString: string,
): SafeParseResult<BuilderFeeRateHistoryEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BuilderFeeRateHistoryEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BuilderFeeRateHistoryEntry' from JSON`,
  );
}
