/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { PriceData, PriceData$inboundSchema } from "./price-data.js";

/**
 * Individual candlestick data.
 */
export type CandlestickData = {
  endPeriodTs: number;
  /**
   * Price data within candlestick.
   */
  price: PriceData;
  volume: number;
  tradesCount: number;
};

/** @internal */
export const CandlestickData$inboundSchema: z.ZodMiniType<
  CandlestickData,
  unknown
> = z.pipe(
  z.object({
    end_period_ts: types.number(),
    price: PriceData$inboundSchema,
    volume: types.number(),
    trades_count: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "end_period_ts": "endPeriodTs",
      "trades_count": "tradesCount",
    });
  }),
);

export function candlestickDataFromJSON(
  jsonString: string,
): SafeParseResult<CandlestickData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CandlestickData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CandlestickData' from JSON`,
  );
}
