/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Evidence object — free-form, but typically includes: hops (in/out depths), bidirectional flag, class (wallet classification), is_verified_trader flag, direct_flow array (per-asset amount and tx count), shared_peers (low-degree wallets both seed and sibling transacted with), same_signer / same_x_username identity proofs, shared_first_funder.
 */
export type Evidence = {};

/**
 * One sibling wallet related to the seed via on-chain transfer graph signals.
 */
export type ClusterSiblingEntry = {
  /**
   * Sibling wallet address
   */
  address: string;
  /**
   * Confidence score 0-100; ≥70 is strong evidence
   */
  confidence: number;
  /**
   * Shortest path from seed to sibling in the transfer graph (1 = direct neighbor).
   */
  minHops: number;
  /**
   * Evidence object — free-form, but typically includes: hops (in/out depths), bidirectional flag, class (wallet classification), is_verified_trader flag, direct_flow array (per-asset amount and tx count), shared_peers (low-degree wallets both seed and sibling transacted with), same_signer / same_x_username identity proofs, shared_first_funder.
   */
  evidence: Evidence;
};

/** @internal */
export const Evidence$inboundSchema: z.ZodMiniType<Evidence, unknown> = z
  .object({});

export function evidenceFromJSON(
  jsonString: string,
): SafeParseResult<Evidence, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Evidence$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Evidence' from JSON`,
  );
}

/** @internal */
export const ClusterSiblingEntry$inboundSchema: z.ZodMiniType<
  ClusterSiblingEntry,
  unknown
> = z.pipe(
  z.object({
    address: types.string(),
    confidence: types.number(),
    min_hops: types.number(),
    evidence: z.lazy(() => Evidence$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "min_hops": "minHops",
    });
  }),
);

export function clusterSiblingEntryFromJSON(
  jsonString: string,
): SafeParseResult<ClusterSiblingEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClusterSiblingEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClusterSiblingEntry' from JSON`,
  );
}
