/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Performance statistics for a cohort of wallets.
 */
export type CohortStats = {
  /**
   * Name of the cohort (e.g., trading style)
   */
  cohortName: string;
  /**
   * Number of wallets in this cohort
   */
  walletCount: number;
  /**
   * Total volume from this cohort (USD)
   */
  totalVolume: number;
  /**
   * Total realized PnL from this cohort (USD)
   */
  totalRealizedPnl: number;
  /**
   * Average realized PnL per wallet (USD)
   */
  avgRealizedPnl: number;
  /**
   * Median realized PnL (USD) - approximated
   */
  medianRealizedPnl: number;
  /**
   * Average ROI
   */
  avgRoi: number;
  /**
   * Average win rate
   */
  avgWinRate: number;
  /**
   * Average profit factor
   */
  avgProfitFactor: number;
  /**
   * Average number of trades
   */
  avgTrades: number;
  /**
   * Percentage of wallets with positive PnL (0-1)
   */
  profitableWalletPct: number;
  /**
   * Total taker fees paid by this cohort (USD)
   */
  totalFeesPaid: number;
  /**
   * DEPRECATED: always 0. Refunds are already netted into fees_paid.
   */
  totalFeesRefunded: number;
  /**
   * Average taker fees paid per wallet (USD)
   */
  avgFeesPaid: number;
  /**
   * DEPRECATED: always 0. Refunds are already netted into fees_paid.
   */
  avgFeesRefunded: number;
};

/** @internal */
export const CohortStats$inboundSchema: z.ZodMiniType<CohortStats, unknown> = z
  .pipe(
    z.object({
      cohort_name: types.string(),
      wallet_count: types.number(),
      total_volume: types.number(),
      total_realized_pnl: types.number(),
      avg_realized_pnl: types.number(),
      median_realized_pnl: types.number(),
      avg_roi: types.number(),
      avg_win_rate: types.number(),
      avg_profit_factor: types.number(),
      avg_trades: types.number(),
      profitable_wallet_pct: types.number(),
      total_fees_paid: z._default(types.number(), 0),
      total_fees_refunded: z._default(types.number(), 0),
      avg_fees_paid: z._default(types.number(), 0),
      avg_fees_refunded: z._default(types.number(), 0),
    }),
    z.transform((v) => {
      return remap$(v, {
        "cohort_name": "cohortName",
        "wallet_count": "walletCount",
        "total_volume": "totalVolume",
        "total_realized_pnl": "totalRealizedPnl",
        "avg_realized_pnl": "avgRealizedPnl",
        "median_realized_pnl": "medianRealizedPnl",
        "avg_roi": "avgRoi",
        "avg_win_rate": "avgWinRate",
        "avg_profit_factor": "avgProfitFactor",
        "avg_trades": "avgTrades",
        "profitable_wallet_pct": "profitableWalletPct",
        "total_fees_paid": "totalFeesPaid",
        "total_fees_refunded": "totalFeesRefunded",
        "avg_fees_paid": "avgFeesPaid",
        "avg_fees_refunded": "avgFeesRefunded",
      });
    }),
  );

export function cohortStatsFromJSON(
  jsonString: string,
): SafeParseResult<CohortStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CohortStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CohortStats' from JSON`,
  );
}
