/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CryptoUpDownMarket,
  CryptoUpDownMarket$inboundSchema,
} from "./crypto-up-down-market.js";
import {
  OffsetPagination,
  OffsetPagination$inboundSchema,
} from "./offset-pagination.js";

/**
 * Response for crypto up/down markets list endpoint.
 */
export type CryptoUpDownResponse = {
  markets: Array<CryptoUpDownMarket>;
  /**
   * Offset-based pagination for markets list endpoints.
   */
  pagination: OffsetPagination;
};

/** @internal */
export const CryptoUpDownResponse$inboundSchema: z.ZodMiniType<
  CryptoUpDownResponse,
  unknown
> = z.object({
  markets: z.array(CryptoUpDownMarket$inboundSchema),
  pagination: OffsetPagination$inboundSchema,
});

export function cryptoUpDownResponseFromJSON(
  jsonString: string,
): SafeParseResult<CryptoUpDownResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CryptoUpDownResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CryptoUpDownResponse' from JSON`,
  );
}
