/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const CryptoTimeframe = {
  Fivem: "5m",
  Fifteenm: "15m",
  Oneh: "1h",
  Fourh: "4h",
  Daily: "daily",
} as const;
export type CryptoTimeframe = ClosedEnum<typeof CryptoTimeframe>;

/** @internal */
export const CryptoTimeframe$outboundSchema: z.ZodMiniEnum<
  typeof CryptoTimeframe
> = z.enum(CryptoTimeframe);
