/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const CryptoAsset = {
  Btc: "btc",
  Eth: "eth",
  Sol: "sol",
  Xrp: "xrp",
  Hype: "hype",
  Doge: "doge",
  Bnb: "bnb",
} as const;
export type CryptoAsset = ClosedEnum<typeof CryptoAsset>;

/** @internal */
export const CryptoAsset$outboundSchema: z.ZodMiniEnum<typeof CryptoAsset> = z
  .enum(CryptoAsset);
