/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Cursor-based pagination for endpoints that don't support offset.
 */
export type CursorPagination = {
  /**
   * Requested limit
   */
  limit: number;
  /**
   * Number of items in current response
   */
  count: number;
  /**
   * Base64-encoded cursor for next page
   */
  paginationKey?: string | null | undefined;
  /**
   * Whether there are more items available
   */
  hasMore: boolean;
};

/** @internal */
export const CursorPagination$inboundSchema: z.ZodMiniType<
  CursorPagination,
  unknown
> = z.pipe(
  z.object({
    limit: types.number(),
    count: types.number(),
    pagination_key: z.optional(z.nullable(types.string())),
    has_more: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "pagination_key": "paginationKey",
      "has_more": "hasMore",
    });
  }),
);

export function cursorPaginationFromJSON(
  jsonString: string,
): SafeParseResult<CursorPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CursorPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CursorPagination' from JSON`,
  );
}
