/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Dflow trade type enum.
 */
export const DflowTradeType = {
  BuyFill: "BUY_FILL",
  SellFill: "SELL_FILL",
  Redeem: "REDEEM",
} as const;
/**
 * Dflow trade type enum.
 */
export type DflowTradeType = OpenEnum<typeof DflowTradeType>;

/** @internal */
export const DflowTradeType$inboundSchema: z.ZodMiniType<
  DflowTradeType,
  unknown
> = openEnums.inboundSchema(DflowTradeType);
/** @internal */
export const DflowTradeType$outboundSchema: z.ZodMiniType<
  string,
  DflowTradeType
> = openEnums.outboundSchema(DflowTradeType);
