/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  DflowPositionStatus,
  DflowPositionStatus$inboundSchema,
} from "./dflow-position-status.js";

/**
 * Individual dflow position.
 */
export type DflowPosition = {
  /**
   * Outcome token mint address
   */
  outcomeMint: string;
  /**
   * Market ticker identifier
   */
  marketTicker?: string | null | undefined;
  /**
   * Human-readable market title
   */
  marketTitle?: string | null | undefined;
  /**
   * Yes outcome subtitle
   */
  yesSubtitle?: string | null | undefined;
  /**
   * No outcome subtitle
   */
  noSubtitle?: string | null | undefined;
  /**
   * Outcome side: yes or no
   */
  outcome?: string | null | undefined;
  /**
   * Dflow position status enum.
   */
  status: DflowPositionStatus;
  /**
   * Total cost basis in USD
   */
  totalCostBasis: number;
  /**
   * Average entry price per token
   */
  avgEntryPrice: number;
  /**
   * Realized PnL in USD
   */
  realizedPnl: number;
  /**
   * Total fees paid in USD
   */
  feesPaid: number;
  /**
   * Total quantity bought
   */
  totalQtyBought: number;
  /**
   * Total quantity sold
   */
  totalQtySold: number;
  /**
   * Unix timestamp of first trade
   */
  firstTradeAt?: number | null | undefined;
  /**
   * Unix timestamp of last trade
   */
  lastTradeAt?: number | null | undefined;
};

/** @internal */
export const DflowPosition$inboundSchema: z.ZodMiniType<
  DflowPosition,
  unknown
> = z.pipe(
  z.object({
    outcome_mint: types.string(),
    market_ticker: z.optional(z.nullable(types.string())),
    market_title: z.optional(z.nullable(types.string())),
    yes_subtitle: z.optional(z.nullable(types.string())),
    no_subtitle: z.optional(z.nullable(types.string())),
    outcome: z.optional(z.nullable(types.string())),
    status: DflowPositionStatus$inboundSchema,
    total_cost_basis: types.number(),
    avg_entry_price: types.number(),
    realized_pnl: types.number(),
    fees_paid: types.number(),
    total_qty_bought: types.number(),
    total_qty_sold: types.number(),
    first_trade_at: z.optional(z.nullable(types.number())),
    last_trade_at: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "outcome_mint": "outcomeMint",
      "market_ticker": "marketTicker",
      "market_title": "marketTitle",
      "yes_subtitle": "yesSubtitle",
      "no_subtitle": "noSubtitle",
      "total_cost_basis": "totalCostBasis",
      "avg_entry_price": "avgEntryPrice",
      "realized_pnl": "realizedPnl",
      "fees_paid": "feesPaid",
      "total_qty_bought": "totalQtyBought",
      "total_qty_sold": "totalQtySold",
      "first_trade_at": "firstTradeAt",
      "last_trade_at": "lastTradeAt",
    });
  }),
);

export function dflowPositionFromJSON(
  jsonString: string,
): SafeParseResult<DflowPosition, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DflowPosition$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DflowPosition' from JSON`,
  );
}
