/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Summary of all dflow positions.
 */
export type DflowPositionsSummary = {
  /**
   * Total number of positions
   */
  totalPositions: number;
  /**
   * Number of open positions
   */
  openPositions: number;
  /**
   * Number of closed positions
   */
  closedPositions: number;
  /**
   * Total cost basis across all positions
   */
  totalCostBasis: number;
  /**
   * Total realized PnL
   */
  totalRealizedPnl: number;
  /**
   * Total fees paid
   */
  totalFeesPaid: number;
};

/** @internal */
export const DflowPositionsSummary$inboundSchema: z.ZodMiniType<
  DflowPositionsSummary,
  unknown
> = z.pipe(
  z.object({
    total_positions: types.number(),
    open_positions: types.number(),
    closed_positions: types.number(),
    total_cost_basis: types.number(),
    total_realized_pnl: types.number(),
    total_fees_paid: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_positions": "totalPositions",
      "open_positions": "openPositions",
      "closed_positions": "closedPositions",
      "total_cost_basis": "totalCostBasis",
      "total_realized_pnl": "totalRealizedPnl",
      "total_fees_paid": "totalFeesPaid",
    });
  }),
);

export function dflowPositionsSummaryFromJSON(
  jsonString: string,
): SafeParseResult<DflowPositionsSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DflowPositionsSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DflowPositionsSummary' from JSON`,
  );
}
