/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  DflowPnLDataPoint,
  DflowPnLDataPoint$inboundSchema,
} from "./dflow-pn-l-data-point.js";
import {
  PnLGranularity,
  PnLGranularity$inboundSchema,
} from "./pn-l-granularity.js";

/**
 * Dflow wallet PnL endpoint response.
 */
export type DflowWalletPnLResponse = {
  /**
   * PnL granularity enum.
   */
  granularity: PnLGranularity;
  startTime: number;
  endTime: number;
  walletAddress: string;
  pnlOverTime: Array<DflowPnLDataPoint>;
};

/** @internal */
export const DflowWalletPnLResponse$inboundSchema: z.ZodMiniType<
  DflowWalletPnLResponse,
  unknown
> = z.pipe(
  z.object({
    granularity: PnLGranularity$inboundSchema,
    start_time: types.number(),
    end_time: types.number(),
    wallet_address: types.string(),
    pnl_over_time: z.array(DflowPnLDataPoint$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "start_time": "startTime",
      "end_time": "endTime",
      "wallet_address": "walletAddress",
      "pnl_over_time": "pnlOverTime",
    });
  }),
);

export function dflowWalletPnLResponseFromJSON(
  jsonString: string,
): SafeParseResult<DflowWalletPnLResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DflowWalletPnLResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DflowWalletPnLResponse' from JSON`,
  );
}
