/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Dflow position status enum.
 */
export const DflowPositionStatus = {
  Open: "open",
  Closed: "closed",
} as const;
/**
 * Dflow position status enum.
 */
export type DflowPositionStatus = OpenEnum<typeof DflowPositionStatus>;

/** @internal */
export const DflowPositionStatus$inboundSchema: z.ZodMiniType<
  DflowPositionStatus,
  unknown
> = openEnums.inboundSchema(DflowPositionStatus);
/** @internal */
export const DflowPositionStatus$outboundSchema: z.ZodMiniType<
  string,
  DflowPositionStatus
> = openEnums.outboundSchema(DflowPositionStatus);
