/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Sort options for dflow positions.
 */
export const DflowPositionSortBy = {
  TotalQtyBought: "total_qty_bought",
  TotalCostBasis: "total_cost_basis",
  RealizedPnl: "realized_pnl",
} as const;
/**
 * Sort options for dflow positions.
 */
export type DflowPositionSortBy = ClosedEnum<typeof DflowPositionSortBy>;

/** @internal */
export const DflowPositionSortBy$outboundSchema: z.ZodMiniEnum<
  typeof DflowPositionSortBy
> = z.enum(DflowPositionSortBy);
