/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  DflowPosition,
  DflowPosition$inboundSchema,
} from "./dflow-position.js";
import {
  DflowPositionsSummary,
  DflowPositionsSummary$inboundSchema,
} from "./dflow-positions-summary.js";

/**
 * Dflow wallet positions endpoint response.
 */
export type DflowWalletPositionsResponse = {
  /**
   * Wallet address
   */
  wallet: string;
  positions: Array<DflowPosition>;
  /**
   * Summary of all dflow positions.
   */
  summary: DflowPositionsSummary;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const DflowWalletPositionsResponse$inboundSchema: z.ZodMiniType<
  DflowWalletPositionsResponse,
  unknown
> = z.object({
  wallet: types.string(),
  positions: z.array(DflowPosition$inboundSchema),
  summary: DflowPositionsSummary$inboundSchema,
  pagination: CursorPagination$inboundSchema,
});

export function dflowWalletPositionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DflowWalletPositionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DflowWalletPositionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DflowWalletPositionsResponse' from JSON`,
  );
}
