/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  DflowTradeType,
  DflowTradeType$inboundSchema,
} from "./dflow-trade-type.js";

/**
 * Individual dflow trade.
 */
export type DflowTrade = {
  /**
   * Solana transaction signature
   */
  signature: string;
  /**
   * Solana slot number
   */
  slot: number;
  /**
   * Unix timestamp in seconds
   */
  timestamp: number;
  /**
   * Dflow trade type enum.
   */
  tradeType: DflowTradeType;
  /**
   * Wallet address of the trade owner
   */
  ownerWallet: string;
  /**
   * Market ticker identifier
   */
  marketTicker?: string | null | undefined;
  /**
   * Outcome token mint address
   */
  outcomeMint: string;
  /**
   * Input amount
   */
  inputAmount: number;
  /**
   * Output amount
   */
  outputAmount: number;
  /**
   * Trade execution price
   */
  tradePrice: number;
  /**
   * Realized PnL from this trade
   */
  realizedPnl: number;
  /**
   * Fee amount paid
   */
  feeAmount: number;
  /**
   * Human-readable market title
   */
  title?: string | null | undefined;
  /**
   * Trade side: YES or NO
   */
  side?: string | null | undefined;
};

/** @internal */
export const DflowTrade$inboundSchema: z.ZodMiniType<DflowTrade, unknown> = z
  .pipe(
    z.object({
      signature: types.string(),
      slot: types.number(),
      timestamp: types.number(),
      trade_type: DflowTradeType$inboundSchema,
      owner_wallet: types.string(),
      market_ticker: z.optional(z.nullable(types.string())),
      outcome_mint: types.string(),
      input_amount: types.number(),
      output_amount: types.number(),
      trade_price: types.number(),
      realized_pnl: types.number(),
      fee_amount: types.number(),
      title: z.optional(z.nullable(types.string())),
      side: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "trade_type": "tradeType",
        "owner_wallet": "ownerWallet",
        "market_ticker": "marketTicker",
        "outcome_mint": "outcomeMint",
        "input_amount": "inputAmount",
        "output_amount": "outputAmount",
        "trade_price": "tradePrice",
        "realized_pnl": "realizedPnl",
        "fee_amount": "feeAmount",
      });
    }),
  );

export function dflowTradeFromJSON(
  jsonString: string,
): SafeParseResult<DflowTrade, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DflowTrade$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DflowTrade' from JSON`,
  );
}
