/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const EventStatusOption = {
  Open: "open",
  Closed: "closed",
} as const;
export type EventStatusOption = ClosedEnum<typeof EventStatusOption>;

/** @internal */
export const EventStatusOption$outboundSchema: z.ZodMiniEnum<
  typeof EventStatusOption
> = z.enum(EventStatusOption);
