/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { KalshiEvent, KalshiEvent$inboundSchema } from "./kalshi-event.js";
import {
  KalshiOutcome,
  KalshiOutcome$inboundSchema,
} from "./kalshi-outcome.js";

/**
 * Kalshi market in list response.
 */
export type KalshiMarket = {
  ticker: string;
  eventTicker: string;
  marketId?: string | null | undefined;
  title: string;
  yesSubtitle: string;
  noSubtitle: string;
  status: string;
  result?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  openTime?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  closeTime?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  expectedExpirationTime?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  settlementTime?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  determinationTime?: string | null | undefined;
  canCloseEarly: boolean;
  strikeType?: string | null | undefined;
  customStrike?: string | null | undefined;
  outcomes: Array<KalshiOutcome>;
  lastPrice?: number | null | undefined;
  volume: number;
  openInterest: number;
  dollarVolume: number;
  dollarOpenInterest: number;
  /**
   * Event info nested in Kalshi market.
   */
  event: KalshiEvent;
  /**
   * ISO 8601 timestamp
   */
  createdAt?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  updatedAt?: string | null | undefined;
};

/** @internal */
export const KalshiMarket$inboundSchema: z.ZodMiniType<KalshiMarket, unknown> =
  z.pipe(
    z.object({
      ticker: types.string(),
      event_ticker: types.string(),
      market_id: z.optional(z.nullable(types.string())),
      title: types.string(),
      yes_subtitle: z._default(types.string(), ""),
      no_subtitle: z._default(types.string(), ""),
      status: types.string(),
      result: z.optional(z.nullable(types.string())),
      open_time: z.optional(z.nullable(types.string())),
      close_time: z.optional(z.nullable(types.string())),
      expected_expiration_time: z.optional(z.nullable(types.string())),
      settlement_time: z.optional(z.nullable(types.string())),
      determination_time: z.optional(z.nullable(types.string())),
      can_close_early: z._default(types.boolean(), false),
      strike_type: z.optional(z.nullable(types.string())),
      custom_strike: z.optional(z.nullable(types.string())),
      outcomes: z.array(KalshiOutcome$inboundSchema),
      last_price: z.optional(z.nullable(types.number())),
      volume: z._default(types.number(), 0),
      open_interest: z._default(types.number(), 0),
      dollar_volume: z._default(types.number(), 0),
      dollar_open_interest: z._default(types.number(), 0),
      event: KalshiEvent$inboundSchema,
      created_at: z.optional(z.nullable(types.string())),
      updated_at: z.optional(z.nullable(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "event_ticker": "eventTicker",
        "market_id": "marketId",
        "yes_subtitle": "yesSubtitle",
        "no_subtitle": "noSubtitle",
        "open_time": "openTime",
        "close_time": "closeTime",
        "expected_expiration_time": "expectedExpirationTime",
        "settlement_time": "settlementTime",
        "determination_time": "determinationTime",
        "can_close_early": "canCloseEarly",
        "strike_type": "strikeType",
        "custom_strike": "customStrike",
        "last_price": "lastPrice",
        "open_interest": "openInterest",
        "dollar_volume": "dollarVolume",
        "dollar_open_interest": "dollarOpenInterest",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
      });
    }),
  );

export function kalshiMarketFromJSON(
  jsonString: string,
): SafeParseResult<KalshiMarket, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KalshiMarket$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KalshiMarket' from JSON`,
  );
}
