/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import { KalshiMarket, KalshiMarket$inboundSchema } from "./kalshi-market.js";

/**
 * Response for Kalshi markets list endpoint.
 */
export type KalshiMarketsResponse = {
  markets: Array<KalshiMarket>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const KalshiMarketsResponse$inboundSchema: z.ZodMiniType<
  KalshiMarketsResponse,
  unknown
> = z.object({
  markets: z.array(KalshiMarket$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function kalshiMarketsResponseFromJSON(
  jsonString: string,
): SafeParseResult<KalshiMarketsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KalshiMarketsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KalshiMarketsResponse' from JSON`,
  );
}
