/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import { KalshiTrade, KalshiTrade$inboundSchema } from "./kalshi-trade.js";

/**
 * Kalshi trades endpoint response.
 */
export type KalshiTradesResponse = {
  trades: Array<KalshiTrade>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const KalshiTradesResponse$inboundSchema: z.ZodMiniType<
  KalshiTradesResponse,
  unknown
> = z.object({
  trades: z.array(KalshiTrade$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function kalshiTradesResponseFromJSON(
  jsonString: string,
): SafeParseResult<KalshiTradesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KalshiTradesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KalshiTradesResponse' from JSON`,
  );
}
