/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  KalshiTakerSide,
  KalshiTakerSide$inboundSchema,
} from "./kalshi-taker-side.js";

/**
 * Kalshi trade model.
 */
export type KalshiTrade = {
  /**
   * Unique trade identifier
   */
  tradeId: string;
  /**
   * Market ticker
   */
  ticker: string;
  /**
   * Number of contracts traded
   */
  count: number;
  /**
   * Yes price (0-1)
   */
  yesPrice: number;
  /**
   * No price (0-1)
   */
  noPrice: number;
  /**
   * Kalshi taker side enum.
   */
  takerSide: KalshiTakerSide;
  /**
   * Unix timestamp in seconds
   */
  createdTime: number;
};

/** @internal */
export const KalshiTrade$inboundSchema: z.ZodMiniType<KalshiTrade, unknown> = z
  .pipe(
    z.object({
      trade_id: types.string(),
      ticker: types.string(),
      count: types.number(),
      yes_price: types.number(),
      no_price: types.number(),
      taker_side: KalshiTakerSide$inboundSchema,
      created_time: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "trade_id": "tradeId",
        "yes_price": "yesPrice",
        "no_price": "noPrice",
        "taker_side": "takerSide",
        "created_time": "createdTime",
      });
    }),
  );

export function kalshiTradeFromJSON(
  jsonString: string,
): SafeParseResult<KalshiTrade, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KalshiTrade$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KalshiTrade' from JSON`,
  );
}
