/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const KalshiMarketsSortOption = {
  Volume: "volume",
  OpenInterest: "open_interest",
  PriceDesc: "price_desc",
  PriceAsc: "price_asc",
  CloseTime: "close_time",
} as const;
export type KalshiMarketsSortOption = ClosedEnum<
  typeof KalshiMarketsSortOption
>;

/** @internal */
export const KalshiMarketsSortOption$outboundSchema: z.ZodMiniEnum<
  typeof KalshiMarketsSortOption
> = z.enum(KalshiMarketsSortOption);
