/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  KalshiOrderbookSnapshot,
  KalshiOrderbookSnapshot$inboundSchema,
} from "./kalshi-orderbook-snapshot.js";

/**
 * Kalshi orderbooks endpoint response.
 */
export type KalshiOrderbooksResponse = {
  snapshots: Array<KalshiOrderbookSnapshot>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const KalshiOrderbooksResponse$inboundSchema: z.ZodMiniType<
  KalshiOrderbooksResponse,
  unknown
> = z.object({
  snapshots: z.array(KalshiOrderbookSnapshot$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function kalshiOrderbooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<KalshiOrderbooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KalshiOrderbooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KalshiOrderbooksResponse' from JSON`,
  );
}
