/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  TradingStyleFlags,
  TradingStyleFlags$inboundSchema,
} from "./trading-style-flags.js";
import {
  WindowMetrics,
  WindowMetrics$inboundSchema,
} from "./window-metrics.js";

/**
 * Single entry in the leaderboard.
 */
export type LeaderboardEntry = {
  /**
   * Position in leaderboard (1-indexed)
   */
  rank: number;
  /**
   * Wallet address
   */
  user: string;
  /**
   * Metrics for a specific time window.
   */
  metrics: WindowMetrics;
  /**
   * Multi-label trading style classification.
   */
  tradingStyles: TradingStyleFlags;
  /**
   * Price edge (avg_sell - avg_buy), only for all_time
   */
  entryEdge?: number | null | undefined;
  /**
   * Unix timestamp of first trade
   */
  firstTradeAt?: number | null | undefined;
};

/** @internal */
export const LeaderboardEntry$inboundSchema: z.ZodMiniType<
  LeaderboardEntry,
  unknown
> = z.pipe(
  z.object({
    rank: types.number(),
    user: types.string(),
    metrics: WindowMetrics$inboundSchema,
    trading_styles: TradingStyleFlags$inboundSchema,
    entry_edge: z.optional(z.nullable(types.number())),
    first_trade_at: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "trading_styles": "tradingStyles",
      "entry_edge": "entryEdge",
      "first_trade_at": "firstTradeAt",
    });
  }),
);

export function leaderboardEntryFromJSON(
  jsonString: string,
): SafeParseResult<LeaderboardEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LeaderboardEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LeaderboardEntry' from JSON`,
  );
}
