/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Sort options for leaderboard.
 */
export const LeaderboardSortBy = {
  RealizedPnl: "realized_pnl",
  TotalPnl: "total_pnl",
  Volume: "volume",
  Roi: "roi",
  ProfitFactor: "profit_factor",
  WinRate: "win_rate",
  Trades: "trades",
} as const;
/**
 * Sort options for leaderboard.
 */
export type LeaderboardSortBy = OpenEnum<typeof LeaderboardSortBy>;

/** @internal */
export const LeaderboardSortBy$inboundSchema: z.ZodMiniType<
  LeaderboardSortBy,
  unknown
> = openEnums.inboundSchema(LeaderboardSortBy);
/** @internal */
export const LeaderboardSortBy$outboundSchema: z.ZodMiniType<
  string,
  LeaderboardSortBy
> = openEnums.outboundSchema(LeaderboardSortBy);
