/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  LimitlessOrderbookLevel,
  LimitlessOrderbookLevel$inboundSchema,
} from "./limitless-orderbook-level.js";

/**
 * Single Limitless orderbook snapshot (YES side only; invert for NO).
 */
export type LimitlessOrderbookSnapshot = {
  /**
   * Market slug identifier
   */
  marketSlug: string;
  /**
   * YES token ID (metadata)
   */
  tokenId: string;
  /**
   * Snapshot timestamp (Unix epoch MILLISECONDS)
   */
  timestamp: number;
  /**
   * Bid levels (buying YES)
   */
  bids: Array<LimitlessOrderbookLevel>;
  /**
   * Ask levels (selling YES)
   */
  asks: Array<LimitlessOrderbookLevel>;
  /**
   * Midpoint price
   */
  midpoint: number;
  /**
   * Adjusted midpoint price
   */
  adjustedMidpoint: number;
};

/** @internal */
export const LimitlessOrderbookSnapshot$inboundSchema: z.ZodMiniType<
  LimitlessOrderbookSnapshot,
  unknown
> = z.pipe(
  z.object({
    market_slug: types.string(),
    token_id: types.string(),
    timestamp: types.number(),
    bids: z.array(LimitlessOrderbookLevel$inboundSchema),
    asks: z.array(LimitlessOrderbookLevel$inboundSchema),
    midpoint: types.number(),
    adjusted_midpoint: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "market_slug": "marketSlug",
      "token_id": "tokenId",
      "adjusted_midpoint": "adjustedMidpoint",
    });
  }),
);

export function limitlessOrderbookSnapshotFromJSON(
  jsonString: string,
): SafeParseResult<LimitlessOrderbookSnapshot, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LimitlessOrderbookSnapshot$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LimitlessOrderbookSnapshot' from JSON`,
  );
}
