/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  LimitlessMarket,
  LimitlessMarket$inboundSchema,
} from "./limitless-market.js";

/**
 * Response for Limitless markets list endpoint.
 */
export type LimitlessMarketsResponse = {
  markets: Array<LimitlessMarket>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const LimitlessMarketsResponse$inboundSchema: z.ZodMiniType<
  LimitlessMarketsResponse,
  unknown
> = z.object({
  markets: z.array(LimitlessMarket$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function limitlessMarketsResponseFromJSON(
  jsonString: string,
): SafeParseResult<LimitlessMarketsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LimitlessMarketsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LimitlessMarketsResponse' from JSON`,
  );
}
