/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Collateral token info for a Limitless market.
 */
export type LimitlessCollateral = {
  address: string;
  symbol: string;
  decimals: number;
};

/** @internal */
export const LimitlessCollateral$inboundSchema: z.ZodMiniType<
  LimitlessCollateral,
  unknown
> = z.object({
  address: z._default(types.string(), ""),
  symbol: z._default(types.string(), ""),
  decimals: z._default(types.number(), 6),
});

export function limitlessCollateralFromJSON(
  jsonString: string,
): SafeParseResult<LimitlessCollateral, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LimitlessCollateral$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LimitlessCollateral' from JSON`,
  );
}
