/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  LimitlessCollateral,
  LimitlessCollateral$inboundSchema,
} from "./limitless-collateral.js";
import {
  LimitlessOutcome,
  LimitlessOutcome$inboundSchema,
} from "./limitless-outcome.js";

/**
 * Limitless market response model.
 */
export type LimitlessMarket = {
  conditionId: string;
  marketId?: number | null | undefined;
  marketSlug: string;
  title: string;
  description: string;
  status: string;
  tradeType: string;
  outcomes: Array<LimitlessOutcome>;
  totalVolumeUsd: number;
  /**
   * Open interest in USD. Null for Limitless CLOB markets because Limitless currently exposes OI only for AMM markets.
   */
  openInterestUsd?: number | null | undefined;
  liquidityUsd: number;
  imageUrl: string;
  categories?: Array<string> | undefined;
  tags?: Array<string> | undefined;
  /**
   * Collateral token info for a Limitless market.
   */
  collateral: LimitlessCollateral;
  marketAddress?: string | null | undefined;
  exchangeAddress?: string | null | undefined;
  expired: boolean;
  winningOutcome?: number | null | undefined;
  payoutNumerators?: Array<number> | undefined;
  resolutionBlock?: number | null | undefined;
  resolutionTx?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  expirationTime?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  createdTime?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  updatedTime?: string | null | undefined;
};

/** @internal */
export const LimitlessMarket$inboundSchema: z.ZodMiniType<
  LimitlessMarket,
  unknown
> = z.pipe(
  z.object({
    condition_id: types.string(),
    market_id: z.optional(z.nullable(types.number())),
    market_slug: types.string(),
    title: types.string(),
    description: z._default(types.string(), ""),
    status: types.string(),
    trade_type: types.string(),
    outcomes: z.array(LimitlessOutcome$inboundSchema),
    total_volume_usd: z._default(types.number(), 0),
    open_interest_usd: z.optional(z.nullable(types.number())),
    liquidity_usd: z._default(types.number(), 0),
    image_url: z._default(types.string(), ""),
    categories: types.optional(z.array(types.string())),
    tags: types.optional(z.array(types.string())),
    collateral: LimitlessCollateral$inboundSchema,
    market_address: z.optional(z.nullable(types.string())),
    exchange_address: z.optional(z.nullable(types.string())),
    expired: z._default(types.boolean(), false),
    winning_outcome: z.optional(z.nullable(types.number())),
    payout_numerators: types.optional(z.array(types.number())),
    resolution_block: z.optional(z.nullable(types.number())),
    resolution_tx: z.optional(z.nullable(types.string())),
    expiration_time: z.optional(z.nullable(types.string())),
    created_time: z.optional(z.nullable(types.string())),
    updated_time: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "market_id": "marketId",
      "market_slug": "marketSlug",
      "trade_type": "tradeType",
      "total_volume_usd": "totalVolumeUsd",
      "open_interest_usd": "openInterestUsd",
      "liquidity_usd": "liquidityUsd",
      "image_url": "imageUrl",
      "market_address": "marketAddress",
      "exchange_address": "exchangeAddress",
      "winning_outcome": "winningOutcome",
      "payout_numerators": "payoutNumerators",
      "resolution_block": "resolutionBlock",
      "resolution_tx": "resolutionTx",
      "expiration_time": "expirationTime",
      "created_time": "createdTime",
      "updated_time": "updatedTime",
    });
  }),
);

export function limitlessMarketFromJSON(
  jsonString: string,
): SafeParseResult<LimitlessMarket, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LimitlessMarket$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LimitlessMarket' from JSON`,
  );
}
