/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * A single tradeable outcome for a Limitless market.
 */
export type LimitlessOutcome = {
  label: string;
  tokenId: string;
  predexonId: string;
  price?: number | null | undefined;
};

/** @internal */
export const LimitlessOutcome$inboundSchema: z.ZodMiniType<
  LimitlessOutcome,
  unknown
> = z.pipe(
  z.object({
    label: types.string(),
    token_id: z._default(types.string(), ""),
    predexon_id: z._default(types.string(), ""),
    price: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "token_id": "tokenId",
      "predexon_id": "predexonId",
    });
  }),
);

export function limitlessOutcomeFromJSON(
  jsonString: string,
): SafeParseResult<LimitlessOutcome, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LimitlessOutcome$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LimitlessOutcome' from JSON`,
  );
}
