/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Market price endpoint response.
 */
export type MarketPriceResponse = {
  price: number;
  /**
   * Unix timestamp in seconds
   */
  atTime: number;
};

/** @internal */
export const MarketPriceResponse$inboundSchema: z.ZodMiniType<
  MarketPriceResponse,
  unknown
> = z.pipe(
  z.object({
    price: types.number(),
    at_time: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "at_time": "atTime",
    });
  }),
);

export function marketPriceResponseFromJSON(
  jsonString: string,
): SafeParseResult<MarketPriceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketPriceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketPriceResponse' from JSON`,
  );
}
