/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Logic for combining market filters.
 */
export const MarketFilterLogic = {
  And: "and",
  Or: "or",
} as const;
/**
 * Logic for combining market filters.
 */
export type MarketFilterLogic = OpenEnum<typeof MarketFilterLogic>;

/** @internal */
export const MarketFilterLogic$inboundSchema: z.ZodMiniType<
  MarketFilterLogic,
  unknown
> = openEnums.inboundSchema(MarketFilterLogic);
/** @internal */
export const MarketFilterLogic$outboundSchema: z.ZodMiniType<
  string,
  MarketFilterLogic
> = openEnums.outboundSchema(MarketFilterLogic);
