/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  OpenInterestDataPoint,
  OpenInterestDataPoint$inboundSchema,
} from "./open-interest-data-point.js";
import {
  PnLGranularity,
  PnLGranularity$inboundSchema,
} from "./pn-l-granularity.js";

/**
 * Market open interest time series endpoint response.
 */
export type MarketOpenInterestTimeSeriesResponse = {
  conditionId: string;
  /**
   * Market ID
   */
  marketId?: string | null | undefined;
  /**
   * PnL granularity enum.
   */
  granularity: PnLGranularity;
  startTime: number;
  endTime: number;
  openInterestOverTime: Array<OpenInterestDataPoint>;
};

/** @internal */
export const MarketOpenInterestTimeSeriesResponse$inboundSchema: z.ZodMiniType<
  MarketOpenInterestTimeSeriesResponse,
  unknown
> = z.pipe(
  z.object({
    condition_id: types.string(),
    market_id: z.optional(z.nullable(types.string())),
    granularity: PnLGranularity$inboundSchema,
    start_time: types.number(),
    end_time: types.number(),
    open_interest_over_time: z.array(OpenInterestDataPoint$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "market_id": "marketId",
      "start_time": "startTime",
      "end_time": "endTime",
      "open_interest_over_time": "openInterestOverTime",
    });
  }),
);

export function marketOpenInterestTimeSeriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<MarketOpenInterestTimeSeriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MarketOpenInterestTimeSeriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketOpenInterestTimeSeriesResponse' from JSON`,
  );
}
