/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Rolling window metrics from market_metrics_summary (hourly cron refresh).
 */
export type MarketRollingMetrics = {
  /**
   * Volume in USD over last 24 hours
   */
  volume1d: number;
  /**
   * Volume in USD over last 7 days
   */
  volume7d: number;
  /**
   * Volume in USD over last 30 days
   */
  volume30d: number;
  /**
   * Buy volume (USD) last 24h
   */
  buyVolume1d: number;
  /**
   * Buy volume (USD) last 7d
   */
  buyVolume7d: number;
  /**
   * Buy volume (USD) last 30d
   */
  buyVolume30d: number;
  /**
   * Sell volume (USD) last 24h
   */
  sellVolume1d: number;
  /**
   * Sell volume (USD) last 7d
   */
  sellVolume7d: number;
  /**
   * Sell volume (USD) last 30d
   */
  sellVolume30d: number;
  /**
   * Trade count last 24h
   */
  trades1d: number;
  /**
   * Trade count last 7d
   */
  trades7d: number;
  /**
   * Trade count last 30d
   */
  trades30d: number;
  /**
   * Buy trades last 24h
   */
  buys1d: number;
  /**
   * Buy trades last 7d
   */
  buys7d: number;
  /**
   * Buy trades last 30d
   */
  buys30d: number;
  /**
   * Sell trades last 24h
   */
  sells1d: number;
  /**
   * Sell trades last 7d
   */
  sells7d: number;
  /**
   * Sell trades last 30d
   */
  sells30d: number;
  /**
   * OI change over last 24h (USD)
   */
  oiChange1d: number;
  /**
   * OI change over last 7d (USD)
   */
  oiChange7d: number;
  /**
   * OI change over last 30d (USD)
   */
  oiChange30d: number;
  /**
   * ISO 8601 timestamp when metrics were last computed
   */
  computedAt?: string | null | undefined;
};

/** @internal */
export const MarketRollingMetrics$inboundSchema: z.ZodMiniType<
  MarketRollingMetrics,
  unknown
> = z.pipe(
  z.object({
    volume_1d: z._default(types.number(), 0),
    volume_7d: z._default(types.number(), 0),
    volume_30d: z._default(types.number(), 0),
    buy_volume_1d: z._default(types.number(), 0),
    buy_volume_7d: z._default(types.number(), 0),
    buy_volume_30d: z._default(types.number(), 0),
    sell_volume_1d: z._default(types.number(), 0),
    sell_volume_7d: z._default(types.number(), 0),
    sell_volume_30d: z._default(types.number(), 0),
    trades_1d: z._default(types.number(), 0),
    trades_7d: z._default(types.number(), 0),
    trades_30d: z._default(types.number(), 0),
    buys_1d: z._default(types.number(), 0),
    buys_7d: z._default(types.number(), 0),
    buys_30d: z._default(types.number(), 0),
    sells_1d: z._default(types.number(), 0),
    sells_7d: z._default(types.number(), 0),
    sells_30d: z._default(types.number(), 0),
    oi_change_1d: z._default(types.number(), 0),
    oi_change_7d: z._default(types.number(), 0),
    oi_change_30d: z._default(types.number(), 0),
    computed_at: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "volume_1d": "volume1d",
      "volume_7d": "volume7d",
      "volume_30d": "volume30d",
      "buy_volume_1d": "buyVolume1d",
      "buy_volume_7d": "buyVolume7d",
      "buy_volume_30d": "buyVolume30d",
      "sell_volume_1d": "sellVolume1d",
      "sell_volume_7d": "sellVolume7d",
      "sell_volume_30d": "sellVolume30d",
      "trades_1d": "trades1d",
      "trades_7d": "trades7d",
      "trades_30d": "trades30d",
      "buys_1d": "buys1d",
      "buys_7d": "buys7d",
      "buys_30d": "buys30d",
      "sells_1d": "sells1d",
      "sells_7d": "sells7d",
      "sells_30d": "sells30d",
      "oi_change_1d": "oiChange1d",
      "oi_change_7d": "oiChange7d",
      "oi_change_30d": "oiChange30d",
      "computed_at": "computedAt",
    });
  }),
);

export function marketRollingMetricsFromJSON(
  jsonString: string,
): SafeParseResult<MarketRollingMetrics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketRollingMetrics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketRollingMetrics' from JSON`,
  );
}
