/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const MarketTypeOption = {
  Binary: "binary",
  Categorical: "categorical",
} as const;
export type MarketTypeOption = ClosedEnum<typeof MarketTypeOption>;

/** @internal */
export const MarketTypeOption$outboundSchema: z.ZodMiniEnum<
  typeof MarketTypeOption
> = z.enum(MarketTypeOption);
