/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const MarketVariantOption = {
  Default: "DEFAULT",
  CryptoUpDown: "CRYPTO_UP_DOWN",
  SportsTeamMatch: "SPORTS_TEAM_MATCH",
  SportsMatch: "SPORTS_MATCH",
  TweetCount: "TWEET_COUNT",
} as const;
export type MarketVariantOption = ClosedEnum<typeof MarketVariantOption>;

/** @internal */
export const MarketVariantOption$outboundSchema: z.ZodMiniEnum<
  typeof MarketVariantOption
> = z.enum(MarketVariantOption);
