/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  LeaderboardEntry,
  LeaderboardEntry$inboundSchema,
} from "./leaderboard-entry.js";
import {
  LeaderboardSortBy,
  LeaderboardSortBy$inboundSchema,
} from "./leaderboard-sort-by.js";
import { TimeWindow, TimeWindow$inboundSchema } from "./time-window.js";

/**
 * Response for per-market leaderboard endpoint.
 */
export type MarketLeaderboardResponse = {
  /**
   * Market condition ID
   */
  conditionId: string;
  /**
   * Time window for rolling metrics.
   */
  window: TimeWindow;
  /**
   * Sort options for leaderboard.
   */
  sortBy: LeaderboardSortBy;
  /**
   * Leaderboard entries
   */
  entries: Array<LeaderboardEntry>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const MarketLeaderboardResponse$inboundSchema: z.ZodMiniType<
  MarketLeaderboardResponse,
  unknown
> = z.pipe(
  z.object({
    condition_id: types.string(),
    window: TimeWindow$inboundSchema,
    sort_by: LeaderboardSortBy$inboundSchema,
    entries: z.array(LeaderboardEntry$inboundSchema),
    pagination: CursorPagination$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "sort_by": "sortBy",
    });
  }),
);

export function marketLeaderboardResponseFromJSON(
  jsonString: string,
): SafeParseResult<MarketLeaderboardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketLeaderboardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketLeaderboardResponse' from JSON`,
  );
}
