/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  PnLGranularity,
  PnLGranularity$inboundSchema,
} from "./pn-l-granularity.js";
import {
  VolumeDataPoint,
  VolumeDataPoint$inboundSchema,
} from "./volume-data-point.js";

/**
 * Market volume time series endpoint response.
 */
export type MarketVolumeTimeSeriesResponse = {
  tokenId: string;
  /**
   * PnL granularity enum.
   */
  granularity: PnLGranularity;
  startTime: number;
  endTime: number;
  volumeOverTime: Array<VolumeDataPoint>;
};

/** @internal */
export const MarketVolumeTimeSeriesResponse$inboundSchema: z.ZodMiniType<
  MarketVolumeTimeSeriesResponse,
  unknown
> = z.pipe(
  z.object({
    token_id: types.string(),
    granularity: PnLGranularity$inboundSchema,
    start_time: types.number(),
    end_time: types.number(),
    volume_over_time: z.array(VolumeDataPoint$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "token_id": "tokenId",
      "start_time": "startTime",
      "end_time": "endTime",
      "volume_over_time": "volumeOverTime",
    });
  }),
);

export function marketVolumeTimeSeriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<MarketVolumeTimeSeriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MarketVolumeTimeSeriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MarketVolumeTimeSeriesResponse' from JSON`,
  );
}
