/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Offset-based pagination for markets list endpoints.
 */
export type OffsetPagination = {
  /**
   * Requested limit
   */
  limit: number;
  /**
   * Current offset
   */
  offset: number;
  /**
   * Total number of matching items
   */
  total: number;
  /**
   * Whether there are more items available
   */
  hasMore: boolean;
};

/** @internal */
export const OffsetPagination$inboundSchema: z.ZodMiniType<
  OffsetPagination,
  unknown
> = z.pipe(
  z.object({
    limit: types.number(),
    offset: types.number(),
    total: types.number(),
    has_more: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
    });
  }),
);

export function offsetPaginationFromJSON(
  jsonString: string,
): SafeParseResult<OffsetPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OffsetPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OffsetPagination' from JSON`,
  );
}
