/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Individual open interest data point.
 */
export type OpenInterestDataPoint = {
  /**
   * Unix timestamp in seconds
   */
  timestamp: number;
  /**
   * Total value of tokens circulating from split, merge, redeem, and conversion events (USD)
   */
  openInterestUsd?: number | null | undefined;
};

/** @internal */
export const OpenInterestDataPoint$inboundSchema: z.ZodMiniType<
  OpenInterestDataPoint,
  unknown
> = z.pipe(
  z.object({
    timestamp: types.number(),
    open_interest_usd: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "open_interest_usd": "openInterestUsd",
    });
  }),
);

export function openInterestDataPointFromJSON(
  jsonString: string,
): SafeParseResult<OpenInterestDataPoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpenInterestDataPoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpenInterestDataPoint' from JSON`,
  );
}
