/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Single price level in Opinion orderbook.
 */
export type OpinionOrderbookLevel = {
  /**
   * Price level (0-1 range)
   */
  price: number;
  /**
   * Size at this price level
   */
  size: number;
};

/** @internal */
export const OpinionOrderbookLevel$inboundSchema: z.ZodMiniType<
  OpinionOrderbookLevel,
  unknown
> = z.object({
  price: types.number(),
  size: types.number(),
});

export function opinionOrderbookLevelFromJSON(
  jsonString: string,
): SafeParseResult<OpinionOrderbookLevel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpinionOrderbookLevel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpinionOrderbookLevel' from JSON`,
  );
}
