/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  OpinionCollection,
  OpinionCollection$inboundSchema,
} from "./opinion-collection.js";
import {
  OpinionOutcome,
  OpinionOutcome$inboundSchema,
} from "./opinion-outcome.js";

/**
 * Opinion market response model.
 */
export type OpinionMarket = {
  marketId: number;
  title: string;
  slug: string;
  description: string;
  status: string;
  outcomes: Array<OpinionOutcome>;
  totalVolumeUsd: number;
  volume24hUsd: number;
  volume7dUsd: number;
  conditionId: string;
  questionId: string;
  resultTokenId?: string | null | undefined;
  eventId?: number | null | undefined;
  eventSlug?: string | null | undefined;
  eventTitle?: string | null | undefined;
  labels?: Array<string> | undefined;
  thumbnailUrl: string;
  chainId: string;
  quoteToken: string;
  collection?: OpinionCollection | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  createdTime?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  cutoffTime?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  resolvedTime?: string | null | undefined;
};

/** @internal */
export const OpinionMarket$inboundSchema: z.ZodMiniType<
  OpinionMarket,
  unknown
> = z.pipe(
  z.object({
    market_id: types.number(),
    title: types.string(),
    slug: types.string(),
    description: z._default(types.string(), ""),
    status: types.string(),
    outcomes: z.array(OpinionOutcome$inboundSchema),
    total_volume_usd: z._default(types.number(), 0),
    volume_24h_usd: z._default(types.number(), 0),
    volume_7d_usd: z._default(types.number(), 0),
    condition_id: z._default(types.string(), ""),
    question_id: z._default(types.string(), ""),
    result_token_id: z.optional(z.nullable(types.string())),
    event_id: z.optional(z.nullable(types.number())),
    event_slug: z.optional(z.nullable(types.string())),
    event_title: z.optional(z.nullable(types.string())),
    labels: types.optional(z.array(types.string())),
    thumbnail_url: z._default(types.string(), ""),
    chain_id: z._default(types.string(), ""),
    quote_token: z._default(types.string(), ""),
    collection: z.optional(z.nullable(OpinionCollection$inboundSchema)),
    created_time: z.optional(z.nullable(types.string())),
    cutoff_time: z.optional(z.nullable(types.string())),
    resolved_time: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "market_id": "marketId",
      "total_volume_usd": "totalVolumeUsd",
      "volume_24h_usd": "volume24hUsd",
      "volume_7d_usd": "volume7dUsd",
      "condition_id": "conditionId",
      "question_id": "questionId",
      "result_token_id": "resultTokenId",
      "event_id": "eventId",
      "event_slug": "eventSlug",
      "event_title": "eventTitle",
      "thumbnail_url": "thumbnailUrl",
      "chain_id": "chainId",
      "quote_token": "quoteToken",
      "created_time": "createdTime",
      "cutoff_time": "cutoffTime",
      "resolved_time": "resolvedTime",
    });
  }),
);

export function opinionMarketFromJSON(
  jsonString: string,
): SafeParseResult<OpinionMarket, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpinionMarket$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpinionMarket' from JSON`,
  );
}
