/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  OpinionOrderbookLevel,
  OpinionOrderbookLevel$inboundSchema,
} from "./opinion-orderbook-level.js";

/**
 * Single Opinion orderbook snapshot (YES side only; invert for NO).
 */
export type OpinionOrderbookSnapshot = {
  /**
   * Market ID
   */
  marketId: number;
  /**
   * YES token ID (metadata)
   */
  tokenId: string;
  /**
   * Snapshot timestamp (Unix epoch MILLISECONDS)
   */
  timestamp: number;
  /**
   * Bid levels
   */
  bids: Array<OpinionOrderbookLevel>;
  /**
   * Ask levels
   */
  asks: Array<OpinionOrderbookLevel>;
  /**
   * Best bid price
   */
  bestBid: number;
  /**
   * Best ask price
   */
  bestAsk: number;
  /**
   * Total bid depth
   */
  bidDepth: number;
  /**
   * Total ask depth
   */
  askDepth: number;
};

/** @internal */
export const OpinionOrderbookSnapshot$inboundSchema: z.ZodMiniType<
  OpinionOrderbookSnapshot,
  unknown
> = z.pipe(
  z.object({
    market_id: types.number(),
    token_id: types.string(),
    timestamp: types.number(),
    bids: z.array(OpinionOrderbookLevel$inboundSchema),
    asks: z.array(OpinionOrderbookLevel$inboundSchema),
    best_bid: types.number(),
    best_ask: types.number(),
    bid_depth: types.number(),
    ask_depth: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "market_id": "marketId",
      "token_id": "tokenId",
      "best_bid": "bestBid",
      "best_ask": "bestAsk",
      "bid_depth": "bidDepth",
      "ask_depth": "askDepth",
    });
  }),
);

export function opinionOrderbookSnapshotFromJSON(
  jsonString: string,
): SafeParseResult<OpinionOrderbookSnapshot, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OpinionOrderbookSnapshot$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OpinionOrderbookSnapshot' from JSON`,
  );
}
