/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const OpinionMarketsSortOption = {
  Volume: "volume",
  Volume24h: "volume_24h",
  Volume7d: "volume_7d",
  Created: "created",
  CreatedAsc: "created_asc",
  Expiration: "expiration",
} as const;
export type OpinionMarketsSortOption = ClosedEnum<
  typeof OpinionMarketsSortOption
>;

/** @internal */
export const OpinionMarketsSortOption$outboundSchema: z.ZodMiniEnum<
  typeof OpinionMarketsSortOption
> = z.enum(OpinionMarketsSortOption);
