/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Order side enum.
 */
export const OrderSide = {
  Buy: "BUY",
  Sell: "SELL",
} as const;
/**
 * Order side enum.
 */
export type OrderSide = OpenEnum<typeof OrderSide>;

/** @internal */
export const OrderSide$inboundSchema: z.ZodMiniType<OrderSide, unknown> =
  openEnums.inboundSchema(OrderSide);
