/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Sort order direction enum.
 */
export const OrderDirection = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort order direction enum.
 */
export type OrderDirection = ClosedEnum<typeof OrderDirection>;

/** @internal */
export const OrderDirection$outboundSchema: z.ZodMiniEnum<
  typeof OrderDirection
> = z.enum(OrderDirection);
