/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * PnL granularity enum.
 */
export const PnLGranularity = {
  Day: "day",
  Week: "week",
  Month: "month",
  Year: "year",
  All: "all",
} as const;
/**
 * PnL granularity enum.
 */
export type PnLGranularity = OpenEnum<typeof PnLGranularity>;

/** @internal */
export const PnLGranularity$inboundSchema: z.ZodMiniType<
  PnLGranularity,
  unknown
> = openEnums.inboundSchema(PnLGranularity);
/** @internal */
export const PnLGranularity$outboundSchema: z.ZodMiniType<
  string,
  PnLGranularity
> = openEnums.outboundSchema(PnLGranularity);
