/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Tag = {};

export type Series = {};

/**
 * Polymarket event in list response.
 */
export type PolymarketEvent = {
  id: string;
  ticker: string;
  slug: string;
  title: string;
  description: string;
  category: string;
  tags?: Array<Tag> | undefined;
  series?: Array<Series> | undefined;
  imageUrl: string;
  iconUrl: string;
  resolutionSource: string;
  /**
   * ISO 8601 timestamp
   */
  startDate?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  endDate?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  creationDate?: string | null | undefined;
  /**
   * ISO 8601 timestamp
   */
  closedTime?: string | null | undefined;
  negRisk: boolean;
  negRiskMarketId?: string | null | undefined;
  enableOrderBook: boolean;
  status: string;
};

/** @internal */
export const Tag$inboundSchema: z.ZodMiniType<Tag, unknown> = z.object({});

export function tagFromJSON(
  jsonString: string,
): SafeParseResult<Tag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tag' from JSON`,
  );
}

/** @internal */
export const Series$inboundSchema: z.ZodMiniType<Series, unknown> = z.object(
  {},
);

export function seriesFromJSON(
  jsonString: string,
): SafeParseResult<Series, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Series$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Series' from JSON`,
  );
}

/** @internal */
export const PolymarketEvent$inboundSchema: z.ZodMiniType<
  PolymarketEvent,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    ticker: z._default(types.string(), ""),
    slug: z._default(types.string(), ""),
    title: z._default(types.string(), ""),
    description: z._default(types.string(), ""),
    category: z._default(types.string(), ""),
    tags: types.optional(z.array(z.lazy(() => Tag$inboundSchema))),
    series: types.optional(z.array(z.lazy(() => Series$inboundSchema))),
    image_url: z._default(types.string(), ""),
    icon_url: z._default(types.string(), ""),
    resolution_source: z._default(types.string(), ""),
    start_date: z.optional(z.nullable(types.string())),
    end_date: z.optional(z.nullable(types.string())),
    creation_date: z.optional(z.nullable(types.string())),
    closed_time: z.optional(z.nullable(types.string())),
    neg_risk: z._default(types.boolean(), false),
    neg_risk_market_id: z.optional(z.nullable(types.string())),
    enable_order_book: z._default(types.boolean(), false),
    status: z._default(types.string(), "open"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
      "icon_url": "iconUrl",
      "resolution_source": "resolutionSource",
      "start_date": "startDate",
      "end_date": "endDate",
      "creation_date": "creationDate",
      "closed_time": "closedTime",
      "neg_risk": "negRisk",
      "neg_risk_market_id": "negRiskMarketId",
      "enable_order_book": "enableOrderBook",
    });
  }),
);

export function polymarketEventFromJSON(
  jsonString: string,
): SafeParseResult<PolymarketEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PolymarketEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PolymarketEvent' from JSON`,
  );
}
