/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  PolymarketEvent,
  PolymarketEvent$inboundSchema,
} from "./polymarket-event.js";

/**
 * Response for Polymarket events list endpoint with cursor pagination.
 */
export type PolymarketEventsKeysetResponse = {
  events: Array<PolymarketEvent>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const PolymarketEventsKeysetResponse$inboundSchema: z.ZodMiniType<
  PolymarketEventsKeysetResponse,
  unknown
> = z.object({
  events: z.array(PolymarketEvent$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function polymarketEventsKeysetResponseFromJSON(
  jsonString: string,
): SafeParseResult<PolymarketEventsKeysetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PolymarketEventsKeysetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PolymarketEventsKeysetResponse' from JSON`,
  );
}
