/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Outcome for a Polymarket market.
 */
export type PolymarketOutcome = {
  label: string;
  tokenId?: string | null | undefined;
  predexonId?: string | null | undefined;
  price?: number | null | undefined;
};

/** @internal */
export const PolymarketOutcome$inboundSchema: z.ZodMiniType<
  PolymarketOutcome,
  unknown
> = z.pipe(
  z.object({
    label: types.string(),
    token_id: z.optional(z.nullable(types.string())),
    predexon_id: z.optional(z.nullable(types.string())),
    price: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "token_id": "tokenId",
      "predexon_id": "predexonId",
    });
  }),
);

export function polymarketOutcomeFromJSON(
  jsonString: string,
): SafeParseResult<PolymarketOutcome, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PolymarketOutcome$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PolymarketOutcome' from JSON`,
  );
}
