/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  PolymarketEvent,
  PolymarketEvent$inboundSchema,
} from "./polymarket-event.js";

/**
 * Response for Polymarket events list endpoint.
 */
export type PolymarketEventsResponse = {
  events: Array<PolymarketEvent>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const PolymarketEventsResponse$inboundSchema: z.ZodMiniType<
  PolymarketEventsResponse,
  unknown
> = z.object({
  events: z.array(PolymarketEvent$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function polymarketEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PolymarketEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PolymarketEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PolymarketEventsResponse' from JSON`,
  );
}
