/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Summary of all positions.
 */
export type PositionsSummary = {
  totalPositions: number;
  totalValueUsd: number;
  totalCostUsd: number;
  totalUnrealizedPnlUsd: number;
  totalRealizedPnlUsd: number;
  winRate?: number | null | undefined;
  winningPositions?: number | null | undefined;
  losingPositions?: number | null | undefined;
  /**
   * Total taker fees paid (USD)
   */
  feesPaid?: number | null | undefined;
  /**
   * DEPRECATED: always 0. Refunds are already netted into fees_paid.
   */
  feesRefunded?: number | null | undefined;
  /**
   * Net fees paid (same as fees_paid, which is already net of refunds)
   */
  netFees?: number | null | undefined;
};

/** @internal */
export const PositionsSummary$inboundSchema: z.ZodMiniType<
  PositionsSummary,
  unknown
> = z.pipe(
  z.object({
    total_positions: types.number(),
    total_value_usd: types.number(),
    total_cost_usd: types.number(),
    total_unrealized_pnl_usd: types.number(),
    total_realized_pnl_usd: types.number(),
    win_rate: z.optional(z.nullable(types.number())),
    winning_positions: z.optional(z.nullable(types.number())),
    losing_positions: z.optional(z.nullable(types.number())),
    fees_paid: z.optional(z.nullable(types.number())),
    fees_refunded: z.optional(z.nullable(types.number())),
    net_fees: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_positions": "totalPositions",
      "total_value_usd": "totalValueUsd",
      "total_cost_usd": "totalCostUsd",
      "total_unrealized_pnl_usd": "totalUnrealizedPnlUsd",
      "total_realized_pnl_usd": "totalRealizedPnlUsd",
      "win_rate": "winRate",
      "winning_positions": "winningPositions",
      "losing_positions": "losingPositions",
      "fees_paid": "feesPaid",
      "fees_refunded": "feesRefunded",
      "net_fees": "netFees",
    });
  }),
);

export function positionsSummaryFromJSON(
  jsonString: string,
): SafeParseResult<PositionsSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PositionsSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PositionsSummary' from JSON`,
  );
}
