/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  PositionCurrentState,
  PositionCurrentState$inboundSchema,
} from "./position-current-state.js";
import {
  PositionDetails,
  PositionDetails$inboundSchema,
} from "./position-details.js";
import {
  PositionMarketInfo,
  PositionMarketInfo$inboundSchema,
} from "./position-market-info.js";
import { PositionPnL, PositionPnL$inboundSchema } from "./position-pn-l.js";

/**
 * Individual position.
 */
export type Position = {
  /**
   * Market info for a position.
   */
  market: PositionMarketInfo;
  /**
   * Position size and cost basis.
   */
  position: PositionDetails;
  /**
   * Current market state for a position.
   */
  current: PositionCurrentState;
  /**
   * Profit and loss for a position.
   */
  pnl: PositionPnL;
};

/** @internal */
export const Position$inboundSchema: z.ZodMiniType<Position, unknown> = z
  .object({
    market: PositionMarketInfo$inboundSchema,
    position: PositionDetails$inboundSchema,
    current: PositionCurrentState$inboundSchema,
    pnl: PositionPnL$inboundSchema,
  });

export function positionFromJSON(
  jsonString: string,
): SafeParseResult<Position, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Position$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Position' from JSON`,
  );
}
