/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Current market state for a position.
 */
export type PositionCurrentState = {
  /**
   * Current market price (0-1)
   */
  price: number;
  /**
   * Current position value in USD
   */
  valueUsd: number;
};

/** @internal */
export const PositionCurrentState$inboundSchema: z.ZodMiniType<
  PositionCurrentState,
  unknown
> = z.pipe(
  z.object({
    price: types.number(),
    value_usd: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "value_usd": "valueUsd",
    });
  }),
);

export function positionCurrentStateFromJSON(
  jsonString: string,
): SafeParseResult<PositionCurrentState, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PositionCurrentState$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PositionCurrentState' from JSON`,
  );
}
