/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Position size and cost basis.
 */
export type PositionDetails = {
  /**
   * Number of shares currently held (0 for closed positions)
   */
  shares: number;
  /**
   * Total shares ever purchased (preserved even after redemption)
   */
  totalSharesBought: number;
  /**
   * Average entry price (0-1)
   */
  avgEntryPrice: number;
  /**
   * Total cost basis in USD
   */
  totalCostUsd: number;
  /**
   * Net taker fees for this position (charged minus refunded, USD)
   */
  netFeesUsd: number;
};

/** @internal */
export const PositionDetails$inboundSchema: z.ZodMiniType<
  PositionDetails,
  unknown
> = z.pipe(
  z.object({
    shares: types.number(),
    total_shares_bought: types.number(),
    avg_entry_price: types.number(),
    total_cost_usd: types.number(),
    net_fees_usd: z._default(types.number(), 0),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_shares_bought": "totalSharesBought",
      "avg_entry_price": "avgEntryPrice",
      "total_cost_usd": "totalCostUsd",
      "net_fees_usd": "netFeesUsd",
    });
  }),
);

export function positionDetailsFromJSON(
  jsonString: string,
): SafeParseResult<PositionDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PositionDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PositionDetails' from JSON`,
  );
}
