/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Market status for a position.
 */
export const PositionMarketStatus = {
  Open: "open",
  ResolvedWin: "resolved_win",
  ResolvedLoss: "resolved_loss",
} as const;
/**
 * Market status for a position.
 */
export type PositionMarketStatus = OpenEnum<typeof PositionMarketStatus>;

/** @internal */
export const PositionMarketStatus$inboundSchema: z.ZodMiniType<
  PositionMarketStatus,
  unknown
> = openEnums.inboundSchema(PositionMarketStatus);
