/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Sort options for positions.
 */
export const PositionSortBy = {
  Value: "value",
  UnrealizedPnl: "unrealized_pnl",
  RealizedPnl: "realized_pnl",
  Cost: "cost",
  AvgPrice: "avg_price",
  CurrentPrice: "current_price",
  EntryDate: "entry_date",
} as const;
/**
 * Sort options for positions.
 */
export type PositionSortBy = ClosedEnum<typeof PositionSortBy>;

/** @internal */
export const PositionSortBy$outboundSchema: z.ZodMiniEnum<
  typeof PositionSortBy
> = z.enum(PositionSortBy);
