/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Position side (YES/NO).
 */
export const PositionSide = {
  Yes: "YES",
  No: "NO",
} as const;
/**
 * Position side (YES/NO).
 */
export type PositionSide = OpenEnum<typeof PositionSide>;

/** @internal */
export const PositionSide$inboundSchema: z.ZodMiniType<PositionSide, unknown> =
  openEnums.inboundSchema(PositionSide);
