/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  PositionMarketStatus,
  PositionMarketStatus$inboundSchema,
} from "./position-market-status.js";
import { PositionSide, PositionSide$inboundSchema } from "./position-side.js";

/**
 * Market info for a position.
 */
export type PositionMarketInfo = {
  conditionId: string;
  marketSlug: string;
  title: string;
  /**
   * Position side (YES/NO).
   */
  side: PositionSide;
  /**
   * Human-readable outcome label (e.g., 'Trump wins' instead of 'Yes')
   */
  sideLabel: string;
  tokenId: string;
  /**
   * Market status for a position.
   */
  status: PositionMarketStatus;
};

/** @internal */
export const PositionMarketInfo$inboundSchema: z.ZodMiniType<
  PositionMarketInfo,
  unknown
> = z.pipe(
  z.object({
    condition_id: types.string(),
    market_slug: types.string(),
    title: types.string(),
    side: PositionSide$inboundSchema,
    side_label: types.string(),
    token_id: types.string(),
    status: PositionMarketStatus$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "market_slug": "marketSlug",
      "side_label": "sideLabel",
      "token_id": "tokenId",
    });
  }),
);

export function positionMarketInfoFromJSON(
  jsonString: string,
): SafeParseResult<PositionMarketInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PositionMarketInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PositionMarketInfo' from JSON`,
  );
}
