/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  PredictFunOrderbookSnapshot,
  PredictFunOrderbookSnapshot$inboundSchema,
} from "./predict-fun-orderbook-snapshot.js";

/**
 * PredictFun orderbooks endpoint response.
 */
export type PredictFunOrderbooksResponse = {
  snapshots: Array<PredictFunOrderbookSnapshot>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const PredictFunOrderbooksResponse$inboundSchema: z.ZodMiniType<
  PredictFunOrderbooksResponse,
  unknown
> = z.object({
  snapshots: z.array(PredictFunOrderbookSnapshot$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function predictFunOrderbooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<PredictFunOrderbooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PredictFunOrderbooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PredictFunOrderbooksResponse' from JSON`,
  );
}
