/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const PredictfunMarketsSortOption = {
  Created: "created",
  CreatedAsc: "created_asc",
  PriceDesc: "price_desc",
  PriceAsc: "price_asc",
  BidDepth: "bid_depth",
} as const;
export type PredictfunMarketsSortOption = ClosedEnum<
  typeof PredictfunMarketsSortOption
>;

/** @internal */
export const PredictfunMarketsSortOption$outboundSchema: z.ZodMiniEnum<
  typeof PredictfunMarketsSortOption
> = z.enum(PredictfunMarketsSortOption);
