/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * A single tradeable outcome for a Predict.fun market.
 */
export type PredictOutcome = {
  label: string;
  tokenId: string;
  predexonId: string;
  bestBid?: number | null | undefined;
  bestAsk?: number | null | undefined;
};

/** @internal */
export const PredictOutcome$inboundSchema: z.ZodMiniType<
  PredictOutcome,
  unknown
> = z.pipe(
  z.object({
    label: types.string(),
    token_id: z._default(types.string(), ""),
    predexon_id: z._default(types.string(), ""),
    best_bid: z.optional(z.nullable(types.number())),
    best_ask: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "token_id": "tokenId",
      "predexon_id": "predexonId",
      "best_bid": "bestBid",
      "best_ask": "bestAsk",
    });
  }),
);

export function predictOutcomeFromJSON(
  jsonString: string,
): SafeParseResult<PredictOutcome, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PredictOutcome$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PredictOutcome' from JSON`,
  );
}
