/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  PredictMarket,
  PredictMarket$inboundSchema,
} from "./predict-market.js";

/**
 * Response for Predict.fun markets list endpoint.
 */
export type PredictMarketsResponse = {
  markets: Array<PredictMarket>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const PredictMarketsResponse$inboundSchema: z.ZodMiniType<
  PredictMarketsResponse,
  unknown
> = z.object({
  markets: z.array(PredictMarket$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function predictMarketsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PredictMarketsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PredictMarketsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PredictMarketsResponse' from JSON`,
  );
}
