/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Price data within candlestick.
 */
export type PriceData = {
  open: number;
  high: number;
  low: number;
  close: number;
  openDollars: string;
  highDollars: string;
  lowDollars: string;
  closeDollars: string;
  mean: number;
  meanDollars: string;
  previous: number;
  previousDollars: string;
};

/** @internal */
export const PriceData$inboundSchema: z.ZodMiniType<PriceData, unknown> = z
  .pipe(
    z.object({
      open: types.number(),
      high: types.number(),
      low: types.number(),
      close: types.number(),
      open_dollars: types.string(),
      high_dollars: types.string(),
      low_dollars: types.string(),
      close_dollars: types.string(),
      mean: types.number(),
      mean_dollars: types.string(),
      previous: types.number(),
      previous_dollars: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "open_dollars": "openDollars",
        "high_dollars": "highDollars",
        "low_dollars": "lowDollars",
        "close_dollars": "closeDollars",
        "mean_dollars": "meanDollars",
        "previous_dollars": "previousDollars",
      });
    }),
  );

export function priceDataFromJSON(
  jsonString: string,
): SafeParseResult<PriceData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PriceData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PriceData' from JSON`,
  );
}
