/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  WindowMetrics,
  WindowMetrics$inboundSchema,
} from "./window-metrics.js";

/**
 * A wallet similar to the target wallet.
 */
export type SimilarWalletEntry = {
  /**
   * Similarity rank (1 = most similar)
   */
  rank: number;
  /**
   * Wallet address
   */
  user: string;
  /**
   * Number of markets traded by both wallets
   */
  marketsOverlap: number;
  /**
   * Percentage of target's markets also traded by this wallet (0-1)
   */
  overlapPct: number;
  /**
   * Total markets this wallet has traded
   */
  totalMarkets: number;
  /**
   * Metrics for a specific time window.
   */
  metrics: WindowMetrics;
};

/** @internal */
export const SimilarWalletEntry$inboundSchema: z.ZodMiniType<
  SimilarWalletEntry,
  unknown
> = z.pipe(
  z.object({
    rank: types.number(),
    user: types.string(),
    markets_overlap: types.number(),
    overlap_pct: types.number(),
    total_markets: types.number(),
    metrics: WindowMetrics$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "markets_overlap": "marketsOverlap",
      "overlap_pct": "overlapPct",
      "total_markets": "totalMarkets",
    });
  }),
);

export function similarWalletEntryFromJSON(
  jsonString: string,
): SafeParseResult<SimilarWalletEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SimilarWalletEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SimilarWalletEntry' from JSON`,
  );
}
