/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Aggregate smart money positioning for a market.
 */
export type SmartMoneyPositioning = {
  /**
   * Market condition ID
   */
  conditionId: string;
  /**
   * Market title
   */
  title?: string | null | undefined;
  /**
   * Market slug for URL construction
   */
  marketSlug?: string | null | undefined;
  /**
   * Number of smart wallets in this market
   */
  smartWalletCount: number;
  /**
   * Smart wallets that are net buyers (buy_volume > sell_volume)
   */
  netBuyers: number;
  /**
   * Smart wallets that are net sellers
   */
  netSellers: number;
  /**
   * Smart wallets with balanced buy/sell
   */
  neutral: number;
  /**
   * Percentage of smart wallets that are net buyers (0-1)
   */
  netBuyersPct: number;
  /**
   * Total volume from smart wallets (USD)
   */
  totalSmartVolume: number;
  /**
   * Total buy volume from smart wallets (USD)
   */
  totalSmartBuyVolume: number;
  /**
   * Total sell volume from smart wallets (USD)
   */
  totalSmartSellVolume: number;
  /**
   * Volume-weighted average buy price of smart wallets (0-1)
   */
  avgSmartBuyPrice: number;
  /**
   * Volume-weighted average sell price of smart wallets (0-1)
   */
  avgSmartSellPrice: number;
  /**
   * Total realized PnL from smart wallets (USD)
   */
  totalSmartRealizedPnl: number;
  /**
   * Total net total PnL from smart wallets (USD)
   */
  totalSmartTotalPnl: number;
  /**
   * Average ROI of smart wallets
   */
  avgSmartRoi: number;
  /**
   * Average win rate of smart wallets
   */
  avgSmartWinRate: number;
};

/** @internal */
export const SmartMoneyPositioning$inboundSchema: z.ZodMiniType<
  SmartMoneyPositioning,
  unknown
> = z.pipe(
  z.object({
    condition_id: types.string(),
    title: z.optional(z.nullable(types.string())),
    market_slug: z.optional(z.nullable(types.string())),
    smart_wallet_count: types.number(),
    net_buyers: types.number(),
    net_sellers: types.number(),
    neutral: types.number(),
    net_buyers_pct: types.number(),
    total_smart_volume: types.number(),
    total_smart_buy_volume: types.number(),
    total_smart_sell_volume: types.number(),
    avg_smart_buy_price: types.number(),
    avg_smart_sell_price: types.number(),
    total_smart_realized_pnl: types.number(),
    total_smart_total_pnl: types.number(),
    avg_smart_roi: types.number(),
    avg_smart_win_rate: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "market_slug": "marketSlug",
      "smart_wallet_count": "smartWalletCount",
      "net_buyers": "netBuyers",
      "net_sellers": "netSellers",
      "net_buyers_pct": "netBuyersPct",
      "total_smart_volume": "totalSmartVolume",
      "total_smart_buy_volume": "totalSmartBuyVolume",
      "total_smart_sell_volume": "totalSmartSellVolume",
      "avg_smart_buy_price": "avgSmartBuyPrice",
      "avg_smart_sell_price": "avgSmartSellPrice",
      "total_smart_realized_pnl": "totalSmartRealizedPnl",
      "total_smart_total_pnl": "totalSmartTotalPnl",
      "avg_smart_roi": "avgSmartRoi",
      "avg_smart_win_rate": "avgSmartWinRate",
    });
  }),
);

export function smartMoneyPositioningFromJSON(
  jsonString: string,
): SafeParseResult<SmartMoneyPositioning, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SmartMoneyPositioning$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmartMoneyPositioning' from JSON`,
  );
}
