/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Sort options for smart activity markets.
 */
export const SmartActivitySortBy = {
  SmartVolume: "smart_volume",
  SmartWalletCount: "smart_wallet_count",
  SmartRealizedPnl: "smart_realized_pnl",
  SmartTotalPnl: "smart_total_pnl",
  AvgSmartRoi: "avg_smart_roi",
} as const;
/**
 * Sort options for smart activity markets.
 */
export type SmartActivitySortBy = ClosedEnum<typeof SmartActivitySortBy>;

/** @internal */
export const SmartActivitySortBy$outboundSchema: z.ZodMiniEnum<
  typeof SmartActivitySortBy
> = z.enum(SmartActivitySortBy);
