/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  SmartMoneyPositioning,
  SmartMoneyPositioning$inboundSchema,
} from "./smart-money-positioning.js";
import { TimeWindow, TimeWindow$inboundSchema } from "./time-window.js";

/**
 * Criteria used to define smart wallets
 */
export type SmartMoneyResponseSmartWalletCriteria = {};

/**
 * Response for smart money positioning endpoint.
 */
export type SmartMoneyResponse = {
  /**
   * Criteria used to define smart wallets
   */
  smartWalletCriteria: SmartMoneyResponseSmartWalletCriteria;
  /**
   * Time window for rolling metrics.
   */
  window: TimeWindow;
  /**
   * Aggregate smart money positioning for a market.
   */
  positioning: SmartMoneyPositioning;
};

/** @internal */
export const SmartMoneyResponseSmartWalletCriteria$inboundSchema: z.ZodMiniType<
  SmartMoneyResponseSmartWalletCriteria,
  unknown
> = z.object({});

export function smartMoneyResponseSmartWalletCriteriaFromJSON(
  jsonString: string,
): SafeParseResult<SmartMoneyResponseSmartWalletCriteria, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SmartMoneyResponseSmartWalletCriteria$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmartMoneyResponseSmartWalletCriteria' from JSON`,
  );
}

/** @internal */
export const SmartMoneyResponse$inboundSchema: z.ZodMiniType<
  SmartMoneyResponse,
  unknown
> = z.pipe(
  z.object({
    smart_wallet_criteria: z.lazy(() =>
      SmartMoneyResponseSmartWalletCriteria$inboundSchema
    ),
    window: TimeWindow$inboundSchema,
    positioning: SmartMoneyPositioning$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "smart_wallet_criteria": "smartWalletCriteria",
    });
  }),
);

export function smartMoneyResponseFromJSON(
  jsonString: string,
): SafeParseResult<SmartMoneyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SmartMoneyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmartMoneyResponse' from JSON`,
  );
}
