/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Market with smart wallet activity stats.
 */
export type SmartActivityMarket = {
  /**
   * Market condition ID
   */
  conditionId: string;
  /**
   * Market title
   */
  title?: string | null | undefined;
  /**
   * Market slug for URL construction
   */
  marketSlug?: string | null | undefined;
  /**
   * Number of smart wallets that traded this market
   */
  smartWalletCount: number;
  /**
   * Total volume from smart wallets (USD)
   */
  smartVolume: number;
  /**
   * Total realized PnL from smart wallets (USD)
   */
  smartRealizedPnl: number;
  /**
   * Total net total PnL from smart wallets (USD)
   */
  smartTotalPnl: number;
  /**
   * Average ROI of smart wallets in this market
   */
  avgSmartRoi: number;
  /**
   * Average win rate of smart wallets in this market
   */
  avgSmartWinRate: number;
  /**
   * Percentage of smart wallets that are net buyers (0-1)
   */
  netBuyersPct: number;
};

/** @internal */
export const SmartActivityMarket$inboundSchema: z.ZodMiniType<
  SmartActivityMarket,
  unknown
> = z.pipe(
  z.object({
    condition_id: types.string(),
    title: z.optional(z.nullable(types.string())),
    market_slug: z.optional(z.nullable(types.string())),
    smart_wallet_count: types.number(),
    smart_volume: types.number(),
    smart_realized_pnl: types.number(),
    smart_total_pnl: types.number(),
    avg_smart_roi: types.number(),
    avg_smart_win_rate: types.number(),
    net_buyers_pct: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "market_slug": "marketSlug",
      "smart_wallet_count": "smartWalletCount",
      "smart_volume": "smartVolume",
      "smart_realized_pnl": "smartRealizedPnl",
      "smart_total_pnl": "smartTotalPnl",
      "avg_smart_roi": "avgSmartRoi",
      "avg_smart_win_rate": "avgSmartWinRate",
      "net_buyers_pct": "netBuyersPct",
    });
  }),
);

export function smartActivityMarketFromJSON(
  jsonString: string,
): SafeParseResult<SmartActivityMarket, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SmartActivityMarket$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmartActivityMarket' from JSON`,
  );
}
