/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const StatusOption = {
  Open: "open",
  Closed: "closed",
} as const;
export type StatusOption = ClosedEnum<typeof StatusOption>;

/** @internal */
export const StatusOption$outboundSchema: z.ZodMiniEnum<typeof StatusOption> = z
  .enum(StatusOption);
