/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const StatusFilter = {
  Open: "open",
  Closed: "closed",
} as const;
export type StatusFilter = ClosedEnum<typeof StatusFilter>;

/** @internal */
export const StatusFilter$outboundSchema: z.ZodMiniEnum<typeof StatusFilter> = z
  .enum(StatusFilter);
