/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Time window for rolling metrics.
 */
export const TimeWindow = {
  Oned: "1d",
  Sevend: "7d",
  Thirtyd: "30d",
  AllTime: "all_time",
} as const;
/**
 * Time window for rolling metrics.
 */
export type TimeWindow = OpenEnum<typeof TimeWindow>;

/** @internal */
export const TimeWindow$inboundSchema: z.ZodMiniType<TimeWindow, unknown> =
  openEnums.inboundSchema(TimeWindow);
/** @internal */
export const TimeWindow$outboundSchema: z.ZodMiniType<string, TimeWindow> =
  openEnums.outboundSchema(TimeWindow);
