/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  TopHolderEntry,
  TopHolderEntry$inboundSchema,
} from "./top-holder-entry.js";

/**
 * Response for market top holders endpoint.
 */
export type TopHoldersResponse = {
  /**
   * Market condition ID
   */
  conditionId: string;
  /**
   * Market title
   */
  title?: string | null | undefined;
  /**
   * Market slug
   */
  marketSlug?: string | null | undefined;
  /**
   * Position side filter applied ('yes', 'no', or null for all)
   */
  side?: string | null | undefined;
  /**
   * Total number of holders matching filters (only if include_count=true)
   */
  totalCount?: number | null | undefined;
  /**
   * Top holder entries
   */
  entries: Array<TopHolderEntry>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const TopHoldersResponse$inboundSchema: z.ZodMiniType<
  TopHoldersResponse,
  unknown
> = z.pipe(
  z.object({
    condition_id: types.string(),
    title: z.optional(z.nullable(types.string())),
    market_slug: z.optional(z.nullable(types.string())),
    side: z.optional(z.nullable(types.string())),
    total_count: z.optional(z.nullable(types.number())),
    entries: z.array(TopHolderEntry$inboundSchema),
    pagination: CursorPagination$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "market_slug": "marketSlug",
      "total_count": "totalCount",
    });
  }),
);

export function topHoldersResponseFromJSON(
  jsonString: string,
): SafeParseResult<TopHoldersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TopHoldersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TopHoldersResponse' from JSON`,
  );
}
