/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Multi-label trading style classification.
 */
export type TradingStyleFlags = {
  /**
   * Large position trader (avg trade > $1000)
   */
  isWhale: boolean;
  /**
   * Balanced buy/sell + frequent trading
   */
  isMarketMaker: boolean;
  /**
   * High trade frequency (>4 trades/position)
   */
  isActiveTrader: boolean;
  /**
   * Long holding periods (<=2 trades/position)
   */
  isBuyAndHold: boolean;
  /**
   * High-risk pattern (win rate < 35%, 50+ closes)
   */
  isDegen: boolean;
  /**
   * Buys at high YES prices (>=0.80)
   */
  isHighConviction: boolean;
  /**
   * Takes unpopular sides (<=0.25)
   */
  isContrarian: boolean;
  /**
   * Enters at uncertain odds (0.35-0.55)
   */
  isValueHunter: boolean;
  /**
   * Primary trading style classification
   */
  primaryStyle: string;
};

/** @internal */
export const TradingStyleFlags$inboundSchema: z.ZodMiniType<
  TradingStyleFlags,
  unknown
> = z.pipe(
  z.object({
    is_whale: types.boolean(),
    is_market_maker: types.boolean(),
    is_active_trader: types.boolean(),
    is_buy_and_hold: types.boolean(),
    is_degen: types.boolean(),
    is_high_conviction: types.boolean(),
    is_contrarian: types.boolean(),
    is_value_hunter: types.boolean(),
    primary_style: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_whale": "isWhale",
      "is_market_maker": "isMarketMaker",
      "is_active_trader": "isActiveTrader",
      "is_buy_and_hold": "isBuyAndHold",
      "is_degen": "isDegen",
      "is_high_conviction": "isHighConviction",
      "is_contrarian": "isContrarian",
      "is_value_hunter": "isValueHunter",
      "primary_style": "primaryStyle",
    });
  }),
);

export function tradingStyleFlagsFromJSON(
  jsonString: string,
): SafeParseResult<TradingStyleFlags, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TradingStyleFlags$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TradingStyleFlags' from JSON`,
  );
}
