/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const TradeTypeOption = {
  Amm: "amm",
  Clob: "clob",
} as const;
export type TradeTypeOption = ClosedEnum<typeof TradeTypeOption>;

/** @internal */
export const TradeTypeOption$outboundSchema: z.ZodMiniEnum<
  typeof TradeTypeOption
> = z.enum(TradeTypeOption);
