/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { OrderSide, OrderSide$inboundSchema } from "./order-side.js";

/**
 * Trade model for Polymarket trades.
 */
export type Trade = {
  tokenId: string;
  /**
   * Order side enum.
   */
  side: OrderSide;
  marketSlug: string;
  conditionId: string;
  /**
   * Shares (raw blockchain units)
   */
  shares: number;
  /**
   * Shares normalized (raw / 1000000)
   */
  sharesNormalized: number;
  /**
   * Trade price (0-1 range)
   */
  price: number;
  /**
   * Trade value in USD
   */
  amountUsd: number;
  txHash: string;
  title: string;
  /**
   * Unix timestamp in seconds
   */
  timestamp: number;
  /**
   * Order hash (same order can have multiple fills)
   */
  orderHash: string;
  /**
   * Maker address
   */
  user: string;
  /**
   * Taker address (counterparty)
   */
  taker: string;
  /**
   * True if trade is for YES token, False for NO token
   */
  isYesSide: boolean;
  /**
   * Human-readable outcome label (e.g., 'Yes', 'No', 'Trump', 'Harris')
   */
  outcomeLabel: string;
  /**
   * Trading fee in USD
   */
  feeUsd: number;
  /**
   * Exchange contract version: 1 = V1 (CTF/NegRiskCTF), 2 = V2
   */
  exchangeVersion: number;
  /**
   * V2 builder attribution tag (bytes32 hex). Empty for V1 fills or V2 fills with no builder.
   */
  builder: string;
  /**
   * V2 opaque metadata tag (bytes32 hex). Empty for V1 fills or V2 fills with no metadata.
   */
  metadata: string;
};

/** @internal */
export const Trade$inboundSchema: z.ZodMiniType<Trade, unknown> = z.pipe(
  z.object({
    token_id: types.string(),
    side: OrderSide$inboundSchema,
    market_slug: types.string(),
    condition_id: types.string(),
    shares: types.number(),
    shares_normalized: types.number(),
    price: types.number(),
    amount_usd: types.number(),
    tx_hash: types.string(),
    title: types.string(),
    timestamp: types.number(),
    order_hash: types.string(),
    user: types.string(),
    taker: types.string(),
    is_yes_side: types.boolean(),
    outcome_label: z._default(types.string(), ""),
    fee_usd: z._default(types.number(), 0),
    exchange_version: z._default(types.number(), 1),
    builder: z._default(types.string(), ""),
    metadata: z._default(types.string(), ""),
  }),
  z.transform((v) => {
    return remap$(v, {
      "token_id": "tokenId",
      "market_slug": "marketSlug",
      "condition_id": "conditionId",
      "shares_normalized": "sharesNormalized",
      "amount_usd": "amountUsd",
      "tx_hash": "txHash",
      "order_hash": "orderHash",
      "is_yes_side": "isYesSide",
      "outcome_label": "outcomeLabel",
      "fee_usd": "feeUsd",
      "exchange_version": "exchangeVersion",
    });
  }),
);

export function tradeFromJSON(
  jsonString: string,
): SafeParseResult<Trade, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Trade$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Trade' from JSON`,
  );
}
