/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const UmaQuestionState = {
  Pending: "pending",
  Proposed: "proposed",
  Disputed: "disputed",
  Reset: "reset",
  Resolved: "resolved",
} as const;
export type UmaQuestionState = OpenEnum<typeof UmaQuestionState>;

/** @internal */
export const UmaQuestionState$inboundSchema: z.ZodMiniType<
  UmaQuestionState,
  unknown
> = openEnums.inboundSchema(UmaQuestionState);
