/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Single UMA event row from uma_event_by_market.
 */
export type UmaEvent = {
  id: string;
  eventType: string;
  sourceContract: string;
  blockNumber: number;
  blockTimestamp: number;
  logIndex: number;
  txHash: string;
  questionId?: string | null | undefined;
  gameId?: string | null | undefined;
  sportsMarketId?: string | null | undefined;
  conditionId?: string | null | undefined;
  requester?: string | null | undefined;
  proposer?: string | null | undefined;
  disputer?: string | null | undefined;
  proposedPrice?: string | null | undefined;
  settledPrice?: string | null | undefined;
  payout?: string | null | undefined;
  expirationTime?: number | null | undefined;
  payouts?: Array<string> | null | undefined;
  homeScore?: number | null | undefined;
  awayScore?: number | null | undefined;
  bondAmount?: string | null | undefined;
  livenessAmount?: number | null | undefined;
  ancillaryData?: string | null | undefined;
};

/** @internal */
export const UmaEvent$inboundSchema: z.ZodMiniType<UmaEvent, unknown> = z.pipe(
  z.object({
    id: types.string(),
    event_type: types.string(),
    source_contract: types.string(),
    block_number: types.number(),
    block_timestamp: types.number(),
    log_index: types.number(),
    tx_hash: types.string(),
    question_id: z.optional(z.nullable(types.string())),
    game_id: z.optional(z.nullable(types.string())),
    sports_market_id: z.optional(z.nullable(types.string())),
    condition_id: z.optional(z.nullable(types.string())),
    requester: z.optional(z.nullable(types.string())),
    proposer: z.optional(z.nullable(types.string())),
    disputer: z.optional(z.nullable(types.string())),
    proposed_price: z.optional(z.nullable(types.string())),
    settled_price: z.optional(z.nullable(types.string())),
    payout: z.optional(z.nullable(types.string())),
    expiration_time: z.optional(z.nullable(types.number())),
    payouts: z.optional(z.nullable(z.array(types.string()))),
    home_score: z.optional(z.nullable(types.number())),
    away_score: z.optional(z.nullable(types.number())),
    bond_amount: z.optional(z.nullable(types.string())),
    liveness_amount: z.optional(z.nullable(types.number())),
    ancillary_data: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_type": "eventType",
      "source_contract": "sourceContract",
      "block_number": "blockNumber",
      "block_timestamp": "blockTimestamp",
      "log_index": "logIndex",
      "tx_hash": "txHash",
      "question_id": "questionId",
      "game_id": "gameId",
      "sports_market_id": "sportsMarketId",
      "condition_id": "conditionId",
      "proposed_price": "proposedPrice",
      "settled_price": "settledPrice",
      "expiration_time": "expirationTime",
      "home_score": "homeScore",
      "away_score": "awayScore",
      "bond_amount": "bondAmount",
      "liveness_amount": "livenessAmount",
      "ancillary_data": "ancillaryData",
    });
  }),
);

export function umaEventFromJSON(
  jsonString: string,
): SafeParseResult<UmaEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UmaEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UmaEvent' from JSON`,
  );
}
