/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  UmaQuestionStatus,
  UmaQuestionStatus$inboundSchema,
} from "./uma-question-status.js";

export type UmaMarketsListItem = {
  /**
   * UMA question status (regular non-sports markets).
   */
  question: UmaQuestionStatus;
};

/** @internal */
export const UmaMarketsListItem$inboundSchema: z.ZodMiniType<
  UmaMarketsListItem,
  unknown
> = z.object({
  question: UmaQuestionStatus$inboundSchema,
});

export function umaMarketsListItemFromJSON(
  jsonString: string,
): SafeParseResult<UmaMarketsListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UmaMarketsListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UmaMarketsListItem' from JSON`,
  );
}
