/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  UmaQuestionState,
  UmaQuestionState$inboundSchema,
} from "./uma-question-state.js";

/**
 * UMA question status (regular non-sports markets).
 */
export type UmaQuestionStatus = {
  /**
   * Question ID (bytes32 hex)
   */
  id: string;
  /**
   * Source adapter contract address
   */
  adapter: string;
  conditionId?: string | null | undefined;
  /**
   * Polymarket market ID (decimal string)
   */
  marketId?: string | null | undefined;
  title?: string | null | undefined;
  state: UmaQuestionState;
  isPaused: boolean;
  isFlagged: boolean;
  /**
   * UMA payout numerator (1e18-scaled, string)
   */
  resolvedPrice?: string | null | undefined;
  resolvedAt?: number | null | undefined;
  pausedAt?: number | null | undefined;
  flaggedAt?: number | null | undefined;
  lastEventAt?: number | null | undefined;
  lastTxHash?: string | null | undefined;
  resetCount: number;
  /**
   * Proposer reward (1e18-scaled, string)
   */
  reward: string;
  /**
   * Proposal bond (1e18-scaled, string)
   */
  proposalBond: string;
  rewardToken: string;
  requestTimestamp: number;
  creator: string;
  createdBlock: number;
  createdTxHash: string;
};

/** @internal */
export const UmaQuestionStatus$inboundSchema: z.ZodMiniType<
  UmaQuestionStatus,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    adapter: types.string(),
    condition_id: z.optional(z.nullable(types.string())),
    market_id: z.optional(z.nullable(types.string())),
    title: z.optional(z.nullable(types.string())),
    state: UmaQuestionState$inboundSchema,
    is_paused: z._default(types.boolean(), false),
    is_flagged: z._default(types.boolean(), false),
    resolved_price: z.optional(z.nullable(types.string())),
    resolved_at: z.optional(z.nullable(types.number())),
    paused_at: z.optional(z.nullable(types.number())),
    flagged_at: z.optional(z.nullable(types.number())),
    last_event_at: z.optional(z.nullable(types.number())),
    last_tx_hash: z.optional(z.nullable(types.string())),
    reset_count: z._default(types.number(), 0),
    reward: types.string(),
    proposal_bond: types.string(),
    reward_token: types.string(),
    request_timestamp: types.number(),
    creator: types.string(),
    created_block: types.number(),
    created_tx_hash: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "market_id": "marketId",
      "is_paused": "isPaused",
      "is_flagged": "isFlagged",
      "resolved_price": "resolvedPrice",
      "resolved_at": "resolvedAt",
      "paused_at": "pausedAt",
      "flagged_at": "flaggedAt",
      "last_event_at": "lastEventAt",
      "last_tx_hash": "lastTxHash",
      "reset_count": "resetCount",
      "proposal_bond": "proposalBond",
      "reward_token": "rewardToken",
      "request_timestamp": "requestTimestamp",
      "created_block": "createdBlock",
      "created_tx_hash": "createdTxHash",
    });
  }),
);

export function umaQuestionStatusFromJSON(
  jsonString: string,
): SafeParseResult<UmaQuestionStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UmaQuestionStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UmaQuestionStatus' from JSON`,
  );
}
