/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Individual volume data point.
 */
export type VolumeDataPoint = {
  /**
   * Unix timestamp in seconds
   */
  timestamp: number;
  /**
   * Cumulative volume up to this point
   */
  volume: number;
  /**
   * Cumulative buy volume up to this point
   */
  buyVolume: number;
  /**
   * Cumulative sell volume up to this point
   */
  sellVolume: number;
};

/** @internal */
export const VolumeDataPoint$inboundSchema: z.ZodMiniType<
  VolumeDataPoint,
  unknown
> = z.pipe(
  z.object({
    timestamp: types.number(),
    volume: types.number(),
    buy_volume: types.number(),
    sell_volume: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "buy_volume": "buyVolume",
      "sell_volume": "sellVolume",
    });
  }),
);

export function volumeDataPointFromJSON(
  jsonString: string,
): SafeParseResult<VolumeDataPoint, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VolumeDataPoint$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VolumeDataPoint' from JSON`,
  );
}
