/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  VolumeChartDataPoint,
  VolumeChartDataPoint$inboundSchema,
} from "./volume-chart-data-point.js";
import {
  VolumeChartGranularity,
  VolumeChartGranularity$inboundSchema,
} from "./volume-chart-granularity.js";

/**
 * Volume chart endpoint response.
 */
export type VolumeChartResponse = {
  /**
   * Market condition ID
   */
  conditionId: string;
  /**
   * Granularity for volume chart endpoint.
   */
  granularity: VolumeChartGranularity;
  /**
   * Unix timestamp of first data point
   */
  startTime: number;
  /**
   * Unix timestamp of last data point
   */
  endTime: number;
  /**
   * Volume data points
   */
  data: Array<VolumeChartDataPoint>;
};

/** @internal */
export const VolumeChartResponse$inboundSchema: z.ZodMiniType<
  VolumeChartResponse,
  unknown
> = z.pipe(
  z.object({
    condition_id: types.string(),
    granularity: VolumeChartGranularity$inboundSchema,
    start_time: types.number(),
    end_time: types.number(),
    data: z.array(VolumeChartDataPoint$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "start_time": "startTime",
      "end_time": "endTime",
    });
  }),
);

export function volumeChartResponseFromJSON(
  jsonString: string,
): SafeParseResult<VolumeChartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VolumeChartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VolumeChartResponse' from JSON`,
  );
}
