/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Granularity for volume chart endpoint.
 */
export const VolumeChartGranularity = {
  Hour: "hour",
  Day: "day",
  Week: "week",
} as const;
/**
 * Granularity for volume chart endpoint.
 */
export type VolumeChartGranularity = OpenEnum<typeof VolumeChartGranularity>;

/** @internal */
export const VolumeChartGranularity$inboundSchema: z.ZodMiniType<
  VolumeChartGranularity,
  unknown
> = openEnums.inboundSchema(VolumeChartGranularity);
/** @internal */
export const VolumeChartGranularity$outboundSchema: z.ZodMiniType<
  string,
  VolumeChartGranularity
> = openEnums.outboundSchema(VolumeChartGranularity);
