/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Bulk identity lookup request.
 */
export type WalletIdentitiesRequest = {
  /**
   * Wallet addresses to look up (max 200)
   */
  addresses: Array<string>;
};

/** @internal */
export type WalletIdentitiesRequest$Outbound = {
  addresses: Array<string>;
};

/** @internal */
export const WalletIdentitiesRequest$outboundSchema: z.ZodMiniType<
  WalletIdentitiesRequest$Outbound,
  WalletIdentitiesRequest
> = z.object({
  addresses: z.array(z.string()),
});

export function walletIdentitiesRequestToJSON(
  walletIdentitiesRequest: WalletIdentitiesRequest,
): string {
  return JSON.stringify(
    WalletIdentitiesRequest$outboundSchema.parse(walletIdentitiesRequest),
  );
}
