/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  TradingStyleFlags,
  TradingStyleFlags$inboundSchema,
} from "./trading-style-flags.js";
import {
  WalletMetrics,
  WalletMetrics$inboundSchema,
} from "./wallet-metrics.js";

/**
 * Full wallet profile response.
 */
export type WalletProfileResponse = {
  /**
   * Wallet address
   */
  user: string;
  /**
   * All metrics for a wallet across all time windows.
   */
  metrics: WalletMetrics;
  /**
   * Multi-label trading style classification.
   */
  tradingStyles: TradingStyleFlags;
  /**
   * Price edge (avg_sell - avg_buy)
   */
  entryEdge?: number | null | undefined;
  /**
   * Total unrealized PnL in USD
   */
  unrealizedPnl?: number | null | undefined;
  /**
   * Total PnL (realized + unrealized - net fees)
   */
  totalPnl?: number | null | undefined;
  /**
   * Unix timestamp of first trade
   */
  firstTradeAt?: number | null | undefined;
  /**
   * Unix timestamp of last trade
   */
  lastTradeAt?: number | null | undefined;
  /**
   * Unix timestamp when metrics were computed
   */
  computedAt?: number | null | undefined;
};

/** @internal */
export const WalletProfileResponse$inboundSchema: z.ZodMiniType<
  WalletProfileResponse,
  unknown
> = z.pipe(
  z.object({
    user: types.string(),
    metrics: WalletMetrics$inboundSchema,
    trading_styles: TradingStyleFlags$inboundSchema,
    entry_edge: z.optional(z.nullable(types.number())),
    unrealized_pnl: z.optional(z.nullable(types.number())),
    total_pnl: z.optional(z.nullable(types.number())),
    first_trade_at: z.optional(z.nullable(types.number())),
    last_trade_at: z.optional(z.nullable(types.number())),
    computed_at: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "trading_styles": "tradingStyles",
      "entry_edge": "entryEdge",
      "unrealized_pnl": "unrealizedPnl",
      "total_pnl": "totalPnl",
      "first_trade_at": "firstTradeAt",
      "last_trade_at": "lastTradeAt",
      "computed_at": "computedAt",
    });
  }),
);

export function walletProfileResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletProfileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletProfileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletProfileResponse' from JSON`,
  );
}
