/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  WalletIdentity,
  WalletIdentity$inboundSchema,
} from "./wallet-identity.js";

/**
 * Bulk identity lookup response.
 */
export type WalletIdentitiesResponse = {
  /**
   * Map of requested address (lowercase) -> profile. Missing addresses are omitted.
   */
  profiles: { [k: string]: WalletIdentity };
};

/** @internal */
export const WalletIdentitiesResponse$inboundSchema: z.ZodMiniType<
  WalletIdentitiesResponse,
  unknown
> = z.object({
  profiles: z.record(z.string(), WalletIdentity$inboundSchema),
});

export function walletIdentitiesResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletIdentitiesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletIdentitiesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletIdentitiesResponse' from JSON`,
  );
}
