/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  WindowMetrics,
  WindowMetrics$inboundSchema,
} from "./window-metrics.js";

/**
 * Per-market metrics for a wallet.
 */
export type WalletMarketEntry = {
  /**
   * Market condition ID
   */
  conditionId: string;
  /**
   * Market title (resolved from market_state)
   */
  title?: string | null | undefined;
  /**
   * Market slug for URL construction
   */
  marketSlug?: string | null | undefined;
  /**
   * Metrics for a specific time window.
   */
  metrics: WindowMetrics;
  /**
   * Price edge for this market
   */
  entryEdge?: number | null | undefined;
  /**
   * First trade timestamp in this market
   */
  firstTradeAt?: number | null | undefined;
  /**
   * Last trade timestamp in this market
   */
  lastTradeAt?: number | null | undefined;
};

/** @internal */
export const WalletMarketEntry$inboundSchema: z.ZodMiniType<
  WalletMarketEntry,
  unknown
> = z.pipe(
  z.object({
    condition_id: types.string(),
    title: z.optional(z.nullable(types.string())),
    market_slug: z.optional(z.nullable(types.string())),
    metrics: WindowMetrics$inboundSchema,
    entry_edge: z.optional(z.nullable(types.number())),
    first_trade_at: z.optional(z.nullable(types.number())),
    last_trade_at: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "condition_id": "conditionId",
      "market_slug": "marketSlug",
      "entry_edge": "entryEdge",
      "first_trade_at": "firstTradeAt",
      "last_trade_at": "lastTradeAt",
    });
  }),
);

export function walletMarketEntryFromJSON(
  jsonString: string,
): SafeParseResult<WalletMarketEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletMarketEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletMarketEntry' from JSON`,
  );
}
