/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Identity + profile metadata for a Polymarket wallet.
 */
export type WalletIdentity = {
  /**
   * Wallet address (proxy / safe address)
   */
  address: string;
  /**
   * Underlying EOA / signer address
   */
  signer?: string | null | undefined;
  /**
   * Wallet type (proxy, safe, eoa, etc.)
   */
  type?: string | null | undefined;
  /**
   * User-set display name from Gamma profile
   */
  displayName?: string | null | undefined;
  /**
   * Auto-generated pseudonym
   */
  pseudonym?: string | null | undefined;
  /**
   * User bio
   */
  bio?: string | null | undefined;
  /**
   * Profile picture URL
   */
  profileImage?: string | null | undefined;
  /**
   * Linked X (Twitter) username
   */
  xUsername?: string | null | undefined;
  /**
   * Verified badge on Polymarket
   */
  verifiedBadge: boolean;
  /**
   * Polymarket market creator
   */
  isCreator: boolean;
  /**
   * Polymarket moderator
   */
  isMod: boolean;
  /**
   * On-chain USDC balance (USD)
   */
  usdcBalance: number;
  /**
   * Unix ts of last USDC transfer
   */
  lastTransferAt?: number | null | undefined;
  /**
   * Unix ts the wallet was first observed
   */
  createdAt?: number | null | undefined;
  /**
   * Unix ts profile was last refreshed from Gamma
   */
  profileFetchedAt?: number | null | undefined;
};

/** @internal */
export const WalletIdentity$inboundSchema: z.ZodMiniType<
  WalletIdentity,
  unknown
> = z.pipe(
  z.object({
    address: types.string(),
    signer: z.optional(z.nullable(types.string())),
    type: z.optional(z.nullable(types.string())),
    display_name: z.optional(z.nullable(types.string())),
    pseudonym: z.optional(z.nullable(types.string())),
    bio: z.optional(z.nullable(types.string())),
    profile_image: z.optional(z.nullable(types.string())),
    x_username: z.optional(z.nullable(types.string())),
    verified_badge: z._default(types.boolean(), false),
    is_creator: z._default(types.boolean(), false),
    is_mod: z._default(types.boolean(), false),
    usdc_balance: z._default(types.number(), 0),
    last_transfer_at: z.optional(z.nullable(types.number())),
    created_at: z.optional(z.nullable(types.number())),
    profile_fetched_at: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "display_name": "displayName",
      "profile_image": "profileImage",
      "x_username": "xUsername",
      "verified_badge": "verifiedBadge",
      "is_creator": "isCreator",
      "is_mod": "isMod",
      "usdc_balance": "usdcBalance",
      "last_transfer_at": "lastTransferAt",
      "created_at": "createdAt",
      "profile_fetched_at": "profileFetchedAt",
    });
  }),
);

export function walletIdentityFromJSON(
  jsonString: string,
): SafeParseResult<WalletIdentity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletIdentity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletIdentity' from JSON`,
  );
}
