/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  WalletIdentity,
  WalletIdentity$inboundSchema,
} from "./wallet-identity.js";

/**
 * Response for the single-wallet identity endpoint.
 */
export type WalletIdentityResponse = {
  /**
   * Requested wallet address (lowercased)
   */
  address: string;
  /**
   * Whether a wallet record was found
   */
  found: boolean;
  /**
   * Profile data if found
   */
  profile?: WalletIdentity | null | undefined;
};

/** @internal */
export const WalletIdentityResponse$inboundSchema: z.ZodMiniType<
  WalletIdentityResponse,
  unknown
> = z.object({
  address: types.string(),
  found: types.boolean(),
  profile: z.optional(z.nullable(WalletIdentity$inboundSchema)),
});

export function walletIdentityResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletIdentityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletIdentityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletIdentityResponse' from JSON`,
  );
}
