/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  VolumeChartGranularity,
  VolumeChartGranularity$inboundSchema,
} from "./volume-chart-granularity.js";
import {
  WalletVolumeChartDataPoint,
  WalletVolumeChartDataPoint$inboundSchema,
} from "./wallet-volume-chart-data-point.js";

/**
 * Wallet volume chart endpoint response.
 */
export type WalletVolumeChartResponse = {
  /**
   * Wallet address
   */
  walletAddress: string;
  /**
   * Granularity for volume chart endpoint.
   */
  granularity: VolumeChartGranularity;
  /**
   * Unix timestamp of first data point
   */
  startTime: number;
  /**
   * Unix timestamp of last data point
   */
  endTime: number;
  /**
   * Volume data points
   */
  data: Array<WalletVolumeChartDataPoint>;
};

/** @internal */
export const WalletVolumeChartResponse$inboundSchema: z.ZodMiniType<
  WalletVolumeChartResponse,
  unknown
> = z.pipe(
  z.object({
    wallet_address: types.string(),
    granularity: VolumeChartGranularity$inboundSchema,
    start_time: types.number(),
    end_time: types.number(),
    data: z.array(WalletVolumeChartDataPoint$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "wallet_address": "walletAddress",
      "start_time": "startTime",
      "end_time": "endTime",
    });
  }),
);

export function walletVolumeChartResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletVolumeChartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletVolumeChartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletVolumeChartResponse' from JSON`,
  );
}
