/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import {
  SimilarWalletEntry,
  SimilarWalletEntry$inboundSchema,
} from "./similar-wallet-entry.js";
import { TimeWindow, TimeWindow$inboundSchema } from "./time-window.js";

/**
 * Response for wallet similarity endpoint.
 */
export type WalletSimilarityResponse = {
  /**
   * The wallet we're finding similar wallets for
   */
  targetWallet: string;
  /**
   * Number of markets the target wallet has traded
   */
  targetMarketCount: number;
  /**
   * Time window for rolling metrics.
   */
  window: TimeWindow;
  /**
   * Wallets with similar market portfolios
   */
  similarWallets: Array<SimilarWalletEntry>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const WalletSimilarityResponse$inboundSchema: z.ZodMiniType<
  WalletSimilarityResponse,
  unknown
> = z.pipe(
  z.object({
    target_wallet: types.string(),
    target_market_count: types.number(),
    window: TimeWindow$inboundSchema,
    similar_wallets: z.array(SimilarWalletEntry$inboundSchema),
    pagination: CursorPagination$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "target_wallet": "targetWallet",
      "target_market_count": "targetMarketCount",
      "similar_wallets": "similarWallets",
    });
  }),
);

export function walletSimilarityResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletSimilarityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletSimilarityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletSimilarityResponse' from JSON`,
  );
}
