/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import { TimeWindow, TimeWindow$inboundSchema } from "./time-window.js";
import {
  WalletMarketEntry,
  WalletMarketEntry$inboundSchema,
} from "./wallet-market-entry.js";

/**
 * Response for wallet's per-market breakdown.
 */
export type WalletMarketsResponse = {
  /**
   * Wallet address
   */
  user: string;
  /**
   * Time window for rolling metrics.
   */
  window: TimeWindow;
  /**
   * Per-market metrics
   */
  markets: Array<WalletMarketEntry>;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const WalletMarketsResponse$inboundSchema: z.ZodMiniType<
  WalletMarketsResponse,
  unknown
> = z.object({
  user: types.string(),
  window: TimeWindow$inboundSchema,
  markets: z.array(WalletMarketEntry$inboundSchema),
  pagination: CursorPagination$inboundSchema,
});

export function walletMarketsResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletMarketsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletMarketsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletMarketsResponse' from JSON`,
  );
}
