/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  CursorPagination,
  CursorPagination$inboundSchema,
} from "./cursor-pagination.js";
import { Position, Position$inboundSchema } from "./position.js";
import {
  PositionsSummary,
  PositionsSummary$inboundSchema,
} from "./positions-summary.js";

/**
 * Wallet positions endpoint response.
 */
export type WalletPositionsResponse = {
  walletAddress: string;
  positions: Array<Position>;
  /**
   * Summary of all positions.
   */
  summary: PositionsSummary;
  /**
   * Cursor-based pagination for endpoints that don't support offset.
   */
  pagination: CursorPagination;
};

/** @internal */
export const WalletPositionsResponse$inboundSchema: z.ZodMiniType<
  WalletPositionsResponse,
  unknown
> = z.pipe(
  z.object({
    wallet_address: types.string(),
    positions: z.array(Position$inboundSchema),
    summary: PositionsSummary$inboundSchema,
    pagination: CursorPagination$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "wallet_address": "walletAddress",
    });
  }),
);

export function walletPositionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<WalletPositionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WalletPositionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WalletPositionsResponse' from JSON`,
  );
}
