/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Metrics for a specific time window.
 */
export type WindowMetrics = {
  /**
   * Realized profit/loss in USD (from closed positions)
   */
  realizedPnl: number;
  /**
   * Total PnL in USD (realized + unrealized - net fees)
   */
  totalPnl?: number | null | undefined;
  /**
   * Trading volume in USD
   */
  volume: number;
  /**
   * Return on investment (decimal, e.g., 0.5 = 50%)
   */
  roi: number;
  /**
   * Number of trades
   */
  trades: number;
  /**
   * Number of winning positions closed
   */
  wins: number;
  /**
   * Number of losing positions closed
   */
  losses: number;
  /**
   * Win rate (decimal, e.g., 0.6 = 60%)
   */
  winRate: number;
  /**
   * Profit factor (gross profit / gross loss)
   */
  profitFactor: number;
  /**
   * Number of positions closed
   */
  positionsClosed: number;
  /**
   * Volume-weighted average buy price (0-1)
   */
  avgBuyPrice?: number | null | undefined;
  /**
   * Volume-weighted average sell price (0-1)
   */
  avgSellPrice?: number | null | undefined;
  /**
   * Taker fees paid in USD
   */
  feesPaid: number;
  /**
   * DEPRECATED: always 0. Refunds are already netted into fees_paid.
   */
  feesRefunded: number;
};

/** @internal */
export const WindowMetrics$inboundSchema: z.ZodMiniType<
  WindowMetrics,
  unknown
> = z.pipe(
  z.object({
    realized_pnl: types.number(),
    total_pnl: z.optional(z.nullable(types.number())),
    volume: types.number(),
    roi: types.number(),
    trades: types.number(),
    wins: types.number(),
    losses: types.number(),
    win_rate: types.number(),
    profit_factor: types.number(),
    positions_closed: types.number(),
    avg_buy_price: z.optional(z.nullable(types.number())),
    avg_sell_price: z.optional(z.nullable(types.number())),
    fees_paid: z._default(types.number(), 0),
    fees_refunded: z._default(types.number(), 0),
  }),
  z.transform((v) => {
    return remap$(v, {
      "realized_pnl": "realizedPnl",
      "total_pnl": "totalPnl",
      "win_rate": "winRate",
      "profit_factor": "profitFactor",
      "positions_closed": "positionsClosed",
      "avg_buy_price": "avgBuyPrice",
      "avg_sell_price": "avgSellPrice",
      "fees_paid": "feesPaid",
      "fees_refunded": "feesRefunded",
    });
  }),
);

export function windowMetricsFromJSON(
  jsonString: string,
): SafeParseResult<WindowMetrics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WindowMetrics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WindowMetrics' from JSON`,
  );
}
