/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Detail = {
  /**
   * Short error code or title (human-readable string)
   */
  error: string;
  /**
   * Longer human-readable explanation of the error. May be absent on some endpoints.
   *
   * @remarks
   */
  message?: string | undefined;
};

/** @internal */
export const Detail$inboundSchema: z.ZodMiniType<Detail, unknown> = z.object({
  error: types.string(),
  message: types.optional(types.string()),
});

export function detailFromJSON(
  jsonString: string,
): SafeParseResult<Detail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Detail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Detail' from JSON`,
  );
}
