/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Stable machine-readable error code returned in `ApiError.error`. Snake_case, never renamed once shipped. Forward-compatible — new codes may be added over time.
 */
export const TradingErrorCode = {
  ValidationError: "validation_error",
  MissingField: "missing_field",
  InvalidField: "invalid_field",
  InvalidAmount: "invalid_amount",
  ParseError: "parse_error",
  Unauthorized: "unauthorized",
  InvalidApiKey: "invalid_api_key",
  Forbidden: "forbidden",
  AccountNotOwned: "account_not_owned",
  AccountNotFound: "account_not_found",
  OrderNotFound: "order_not_found",
  TransferNotFound: "transfer_not_found",
  EndpointNotFound: "endpoint_not_found",
  Conflict: "conflict",
  NonceReplay: "nonce_replay",
  InsufficientBalance: "insufficient_balance",
  MinNotionalNotMet: "min_notional_not_met",
  AmountBelowMinimum: "amount_below_minimum",
  PredexonNotRoutable: "predexon_not_routable",
  RouterUnavailable: "router_unavailable",
  NoAllocations: "no_allocations",
  LimitNoEligibleVenue: "limit_no_eligible_venue",
  SlippageBelowFloor: "slippage_below_floor",
  SlippageTooHigh: "slippage_too_high",
  UnsupportedRouteV1: "unsupported_route_v1",
  SameEndpoint: "same_endpoint",
  WithdrawViaDeposit: "withdraw_via_deposit",
  InboundRequiresQuote: "inbound_requires_quote",
  HyperliquidUsesAcross: "hyperliquid_uses_across",
  BridgeFailed: "bridge_failed",
  PayloadTooLarge: "payload_too_large",
  RateLimited: "rate_limited",
  InternalError: "internal_error",
  UpstreamTimeout: "upstream_timeout",
  UpstreamError: "upstream_error",
} as const;
/**
 * Stable machine-readable error code returned in `ApiError.error`. Snake_case, never renamed once shipped. Forward-compatible — new codes may be added over time.
 */
export type TradingErrorCode = OpenEnum<typeof TradingErrorCode>;

/** @internal */
export const TradingErrorCode$inboundSchema: z.ZodMiniType<
  TradingErrorCode,
  unknown
> = openEnums.inboundSchema(TradingErrorCode);
